export type AgentRuntimeKind = 'llm' | 'pipeline' | 'connector' | 'system';
export type AgentImplementationMode = 'implemented' | 'delegated' | 'stub';

export interface AgentCatalogEntry {
  id: string;
  slug: string;
  name: string;
  description: string;
  category:
    | 'orchestration'
    | 'ingest_intelligence'
    | 'resolution_reconciliation'
    | 'identity_customer_truth'
    | 'system_tool'
    | 'observability_communication';
  isSystem: number;
  isLocked: number;
  runtimeKind: AgentRuntimeKind;
  implementationMode: AgentImplementationMode;
  modelTier: 'none' | 'basic' | 'advanced';
  sortOrder: number;
  icon: string;
  iconColor: string;
  purpose: string;
  triggers: string[];
  dependencies: string[];
  ioLogic: {
    input: string;
    output: string;
  };
}

export const AGENT_CATALOG: AgentCatalogEntry[] = [
  {
    id: 'agent_supervisor',
    slug: 'supervisor',
    name: 'Supervisor',
    description: 'Orchestrates the overall agent flow.',
    category: 'orchestration',
    isSystem: 1,
    isLocked: 1,
    runtimeKind: 'system',
    implementationMode: 'delegated',
    modelTier: 'none',
    sortOrder: 10,
    icon: 'account_tree',
    iconColor: 'text-purple-600',
    purpose: 'Coordinates agent handoffs and protects the global case flow without performing domain actions directly.',
    triggers: ['New case created', 'Message received', 'Execution result received'],
    dependencies: ['Intent Router', 'Reconciliation Agent', 'Workflow Runtime Agent'],
    ioLogic: { input: 'Canonical case context', output: 'Deterministic handoff decision' },
  },
  {
    id: 'agent_approval_gk',
    slug: 'approval-gatekeeper',
    name: 'Approval Gatekeeper',
    description: 'Handles human approval requirements for high-risk actions.',
    category: 'orchestration',
    isSystem: 1,
    isLocked: 0,
    runtimeKind: 'llm',
    implementationMode: 'implemented',
    modelTier: 'basic',
    sortOrder: 20,
    icon: 'approval_delegation',
    iconColor: 'text-indigo-600',
    purpose: 'Applies approval policies and blocks sensitive execution until a human decision is available.',
    triggers: ['Sensitive action proposed', 'Confidence below threshold', 'Policy requires approval'],
    dependencies: ['QA / Policy Check', 'Case Resolution Planner', 'Approval policies'],
    ioLogic: { input: 'Proposed action + policy context', output: 'Approval decision or block' },
  },
  {
    id: 'agent_qa',
    slug: 'qa-policy-check',
    name: 'QA / Policy Check',
    description: 'Performs pre-send / pre-execution safety, policy, and quality validation.',
    category: 'orchestration',
    isSystem: 1,
    isLocked: 0,
    runtimeKind: 'llm',
    implementationMode: 'implemented',
    modelTier: 'basic',
    sortOrder: 30,
    icon: 'security',
    iconColor: 'text-blue-600',
    purpose: 'Validates policy compliance, brand constraints and safety packaging before execution or outbound communication.',
    triggers: ['Draft prepared', 'Action ready to execute', 'Conflict requires compliance review'],
    dependencies: ['Knowledge Retriever', 'Approval Gatekeeper'],
    ioLogic: { input: 'Draft/action candidate', output: 'Validated decision package' },
  },
  {
    id: 'agent_case_validation',
    slug: 'case-validation-agent',
    name: 'Case Validation Agent',
    description: 'Validates case completeness before approvals and execution.',
    category: 'resolution_reconciliation',
    isSystem: 1,
    isLocked: 0,
    runtimeKind: 'system',
    implementationMode: 'delegated',
    modelTier: 'none',
    sortOrder: 35,
    icon: 'fact_check',
    iconColor: 'text-violet-600',
    purpose: 'Checks that the case has the required provider context, policy evidence, and linked entities before a human or system action is allowed to continue.',
    triggers: ['Conflict package ready', 'Provider data incomplete', 'Pre-approval guard'],
    dependencies: ['Reconciliation Agent', 'Knowledge Retriever', 'Approval Gatekeeper'],
    ioLogic: { input: 'Canonical case bundle + provider context', output: 'Validation pass/fail with missing fields' },
  },
  {
    id: 'agent_channel_ingest',
    slug: 'channel-ingest',
    name: 'Channel Ingest',
    description: 'Receives inbound channel events and converts them into normalized intake events.',
    category: 'ingest_intelligence',
    isSystem: 1,
    isLocked: 0,
    runtimeKind: 'pipeline',
    implementationMode: 'delegated',
    modelTier: 'none',
    sortOrder: 40,
    icon: 'mail',
    iconColor: 'text-orange-600',
    purpose: 'Accepts raw events from email, chat and messaging channels and transforms them into intake jobs.',
    triggers: ['Inbound email', 'Inbound web chat', 'Inbound WhatsApp event'],
    dependencies: ['Webhook handlers', 'Canonicalizer'],
    ioLogic: { input: 'Raw channel payload', output: 'Normalized intake event' },
  },
  {
    id: 'agent_canonicalizer',
    slug: 'canonicalizer',
    name: 'Canonicalizer',
    description: 'Normalizes entities, fields, and event structure.',
    category: 'ingest_intelligence',
    isSystem: 1,
    isLocked: 0,
    runtimeKind: 'pipeline',
    implementationMode: 'delegated',
    modelTier: 'none',
    sortOrder: 50,
    icon: 'cleaning_services',
    iconColor: 'text-emerald-600',
    purpose: 'Standardizes customer, order, payment, refund and return data into the canonical case state.',
    triggers: ['Intake event ready', 'Webhook stored', 'Tool result received'],
    dependencies: ['Channel Ingest', 'Identity Mapping Agent'],
    ioLogic: { input: 'Raw or semi-structured event', output: 'Canonical state update' },
  },
  {
    id: 'agent_intent_router',
    slug: 'intent-router',
    name: 'Intent Router',
    description: 'Classifies the task and routes it to the correct next agent.',
    category: 'ingest_intelligence',
    isSystem: 1,
    isLocked: 0,
    runtimeKind: 'llm',
    implementationMode: 'implemented',
    modelTier: 'basic',
    sortOrder: 60,
    icon: 'split_scene',
    iconColor: 'text-cyan-600',
    purpose: 'Classifies the customer need and decides the next specialist or workflow branch.',
    triggers: ['Canonical context ready', 'New customer message', 'Case updated'],
    dependencies: ['Canonicalizer', 'Supervisor'],
    ioLogic: { input: 'Canonical case context', output: 'Intent + next route' },
  },
  {
    id: 'agent_knowledge',
    slug: 'knowledge-retriever',
    name: 'Knowledge Retriever',
    description: 'Fetches relevant policies, SOPs, and operational guidance.',
    category: 'ingest_intelligence',
    isSystem: 1,
    isLocked: 0,
    runtimeKind: 'llm',
    implementationMode: 'implemented',
    modelTier: 'basic',
    sortOrder: 70,
    icon: 'menu_book',
    iconColor: 'text-amber-600',
    purpose: 'Retrieves the minimal policy and SOP set needed by planning, QA and communication agents.',
    triggers: ['Policy lookup needed', 'Contradiction detected', 'Pre-send validation'],
    dependencies: ['Knowledge module', 'Intent Router'],
    ioLogic: { input: 'Context + retrieval query', output: 'Knowledge bundle with citations' },
  },
  {
    id: 'agent_crm_case_link',
    slug: 'crm-case-link-agent',
    name: 'CRM / Case Link Agent',
    description: 'Links CRM identity, case context, and operational references.',
    category: 'identity_customer_truth',
    isSystem: 1,
    isLocked: 0,
    runtimeKind: 'system',
    implementationMode: 'delegated',
    modelTier: 'none',
    sortOrder: 145,
    icon: 'link',
    iconColor: 'text-sky-600',
    purpose: 'Ensures the case is attached to the right customer, thread, and provider references before downstream agents make decisions.',
    triggers: ['Customer identity loaded', 'Case needs CRM linking', 'External reference missing'],
    dependencies: ['CRM / Customer Identity Agent', 'Channel Ingest', 'Canonicalizer'],
    ioLogic: { input: 'Case identifiers + CRM context', output: 'Validated case/customer linkage' },
  },
  {
    id: 'agent_composer',
    slug: 'composer-translator',
    name: 'Composer + Translator',
    description: 'Drafts and localizes internal and customer-facing messages.',
    category: 'ingest_intelligence',
    isSystem: 1,
    isLocked: 0,
    runtimeKind: 'llm',
    implementationMode: 'implemented',
    modelTier: 'advanced',
    sortOrder: 80,
    icon: 'edit_note',
    iconColor: 'text-pink-600',
    purpose: 'Creates customer-facing and internal drafts using approved context, localized tone and policy constraints.',
    triggers: ['Draft requested', 'Customer update required', 'Internal note needed'],
    dependencies: ['Knowledge Retriever', 'Customer Communication Agent', 'QA / Policy Check'],
    ioLogic: { input: 'Approved objective + context', output: 'Drafted localized message' },
  },
  {
    id: 'agent_customer_history',
    slug: 'customer-history-analyst',
    name: 'Customer History Analyst',
    description: 'Summarizes prior customer activity, exceptions, and approvals.',
    category: 'identity_customer_truth',
    isSystem: 0,
    isLocked: 0,
    runtimeKind: 'llm',
    implementationMode: 'delegated',
    modelTier: 'basic',
    sortOrder: 150,
    icon: 'history',
    iconColor: 'text-slate-600',
    purpose: 'Condenses the customer’s historical orders, approvals, refunds, and risk signals so the current case can be judged in context.',
    triggers: ['Customer loaded', 'Historical risk needed', 'Repeat exception detected'],
    dependencies: ['CRM / Customer Identity Agent', 'Knowledge Retriever'],
    ioLogic: { input: 'Customer history bundle', output: 'Historical summary and risk signals' },
  },
  {
    id: 'agent_reconciliation',
    slug: 'reconciliation-agent',
    name: 'Reconciliation Agent',
    description: 'Detects contradictions across systems.',
    category: 'resolution_reconciliation',
    isSystem: 1,
    isLocked: 1,
    runtimeKind: 'system',
    implementationMode: 'delegated',
    modelTier: 'none',
    sortOrder: 90,
    icon: 'compare_arrows',
    iconColor: 'text-rose-600',
    purpose: 'Compares state across systems, identifies source-of-truth contradictions and opens structured conflict context.',
    triggers: ['Cross-system update', 'Resolve mode opened', 'ID mismatch detected'],
    dependencies: ['Stripe Agent', 'Shopify Agent', 'OMS / ERP Agent', 'Identity Mapping Agent'],
    ioLogic: { input: 'System states + mappings', output: 'Conflict summary + root cause' },
  },
  {
    id: 'agent_case_resolution',
    slug: 'case-resolution-planner',
    name: 'Case Resolution Planner',
    description: 'Converts detected contradictions into resolution plans.',
    category: 'resolution_reconciliation',
    isSystem: 1,
    isLocked: 0,
    runtimeKind: 'system',
    implementationMode: 'stub',
    modelTier: 'advanced',
    sortOrder: 100,
    icon: 'schema',
    iconColor: 'text-fuchsia-600',
    purpose: 'Transforms conflict context into a safe resolution plan with ownership, approval gates and expected final state.',
    triggers: ['Conflict opened', 'Policy blocker detected', 'Manual intervention requested'],
    dependencies: ['Reconciliation Agent', 'Approval Gatekeeper', 'Knowledge Retriever'],
    ioLogic: { input: 'Conflict package + policy context', output: 'Resolution plan' },
  },
  {
    id: 'agent_executor',
    slug: 'resolution-executor',
    name: 'Resolution Executor',
    description: 'Executes the approved external/system-facing resolution steps.',
    category: 'resolution_reconciliation',
    isSystem: 1,
    isLocked: 0,
    runtimeKind: 'system',
    implementationMode: 'delegated',
    modelTier: 'none',
    sortOrder: 110,
    icon: 'play_circle',
    iconColor: 'text-lime-600',
    purpose: 'Executes approved writebacks, idempotent tool actions and recovery steps across connected systems.',
    triggers: ['Approval granted', 'Execution requested', 'Retry requested'],
    dependencies: ['Case Resolution Planner', 'Approval Gatekeeper', 'Connector agents'],
    ioLogic: { input: 'Approved execution plan', output: 'Execution outcome + state update' },
  },
  {
    id: 'agent_workflow_runtime',
    slug: 'workflow-runtime-agent',
    name: 'Workflow Runtime Agent',
    description: 'Manages internal workflow progression after reconciliation and execution.',
    category: 'resolution_reconciliation',
    isSystem: 1,
    isLocked: 0,
    runtimeKind: 'system',
    implementationMode: 'implemented',
    modelTier: 'none',
    sortOrder: 120,
    icon: 'account_tree',
    iconColor: 'text-indigo-600',
    purpose: 'Advances, pauses, resumes and unblocks internal workflow state as external execution completes.',
    triggers: ['Execution completed', 'Conflict resolved', 'Approval state changed'],
    dependencies: ['Resolution Executor', 'Workflows module'],
    ioLogic: { input: 'Execution result + workflow context', output: 'Updated workflow state' },
  },
  {
    id: 'agent_finance_reconciler',
    slug: 'finance-reconciler',
    name: 'Finance Reconciler',
    description: 'Checks refunds, writebacks, and ledger alignment for finance-sensitive cases.',
    category: 'resolution_reconciliation',
    isSystem: 0,
    isLocked: 0,
    runtimeKind: 'llm',
    implementationMode: 'delegated',
    modelTier: 'basic',
    sortOrder: 125,
    icon: 'account_balance',
    iconColor: 'text-emerald-600',
    purpose: 'Validates that financial writebacks, refund states, and dispute handling remain aligned before the case is finalized.',
    triggers: ['Refund proposed', 'Ledger mismatch detected', 'Finance review required'],
    dependencies: ['Approval Gatekeeper', 'Case Validation Agent', 'Knowledge Retriever'],
    ioLogic: { input: 'Case + payment + refund context', output: 'Finance validation package' },
  },
  {
    id: 'agent_identity_mapping',
    slug: 'identity-mapping-agent',
    name: 'Identity Mapping Agent',
    description: 'Resolves entity and identity links across systems.',
    category: 'identity_customer_truth',
    isSystem: 1,
    isLocked: 0,
    runtimeKind: 'llm',
    implementationMode: 'implemented',
    modelTier: 'basic',
    sortOrder: 130,
    icon: 'fingerprint',
    iconColor: 'text-teal-600',
    purpose: 'Matches customer, order, payment, refund and return identities across systems and blocks unsafe propagation when identity is unclear.',
    triggers: ['Missing external ID', 'Duplicate match', 'Ambiguous reference detected'],
    dependencies: ['CRM / Customer Identity Agent', 'Shopify Agent', 'Stripe Agent'],
    ioLogic: { input: 'Cross-system references', output: 'Canonical mapping or blocker' },
  },
  {
    id: 'agent_customer_identity',
    slug: 'customer-identity-agent',
    name: 'CRM / Customer Identity Agent',
    description: 'Provides canonical customer truth from CRM/identity source.',
    category: 'identity_customer_truth',
    isSystem: 1,
    isLocked: 0,
    runtimeKind: 'llm',
    implementationMode: 'implemented',
    modelTier: 'basic',
    sortOrder: 140,
    icon: 'contact_page',
    iconColor: 'text-slate-600',
    purpose: 'Supplies customer truth, segmentation, VIP/risk context and linked identities to downstream agents.',
    triggers: ['Customer loaded', 'Identity conflict detected', 'Case linked to customer'],
    dependencies: ['CRM connector', 'Identity Mapping Agent'],
    ioLogic: { input: 'Customer identifiers', output: 'Canonical customer profile' },
  },
  {
    id: 'agent_helpdesk',
    slug: 'helpdesk-agent',
    name: 'Helpdesk Agent',
    description: 'Reads/writes tickets, tags, notes, and support metadata in the helpdesk system.',
    category: 'system_tool',
    isSystem: 1,
    isLocked: 0,
    runtimeKind: 'connector',
    implementationMode: 'implemented',
    modelTier: 'none',
    sortOrder: 150,
    icon: 'support_agent',
    iconColor: 'text-sky-600',
    purpose: 'Synchronizes support-side thread state, notes and tags with the canonical operational case.',
    triggers: ['Ticket created', 'Internal note added', 'Reply approved'],
    dependencies: ['Customer Communication Agent', 'Composer + Translator'],
    ioLogic: { input: 'Support update intent', output: 'Helpdesk synchronization result' },
  },
  {
    id: 'agent_returns_specialist',
    slug: 'returns-specialist',
    name: 'Returns Specialist',
    description: 'Handles return inspection, approval, and refund timing.',
    category: 'resolution_reconciliation',
    isSystem: 0,
    isLocked: 0,
    runtimeKind: 'system',
    implementationMode: 'delegated',
    modelTier: 'none',
    sortOrder: 195,
    icon: 'assignment_return',
    iconColor: 'text-orange-600',
    purpose: 'Keeps return inspection, approval, and refund timing aligned with the canonical case state.',
    triggers: ['Return received', 'Inspection completed', 'Refund timing decision needed'],
    dependencies: ['Returns Agent', 'Finance Reconciler', 'Approval Gatekeeper'],
    ioLogic: { input: 'Return case context', output: 'Return decision state' },
  },
  {
    id: 'agent_stripe',
    slug: 'stripe-connector',
    name: 'Stripe Connector',
    description: 'Reads and updates payment, refund, dispute, and subscription state in Stripe.',
    category: 'system_tool',
    isSystem: 1,
    isLocked: 0,
    runtimeKind: 'connector',
    implementationMode: 'implemented',
    modelTier: 'none',
    sortOrder: 160,
    icon: 'credit_card',
    iconColor: 'text-indigo-600',
    purpose: 'Provides payment and refund truth and executes approved Stripe-side actions.',
    triggers: ['Payment inquiry', 'Refund contradiction', 'Approved Stripe writeback'],
    dependencies: ['Stripe connector', 'Resolution Executor'],
    ioLogic: { input: 'Stripe action/read request', output: 'Stripe state/result' },
  },
  {
    id: 'agent_shopify',
    slug: 'shopify-connector',
    name: 'Shopify Connector',
    description: 'Reads and updates order, customer, and commerce state in Shopify.',
    category: 'system_tool',
    isSystem: 1,
    isLocked: 0,
    runtimeKind: 'connector',
    implementationMode: 'implemented',
    modelTier: 'none',
    sortOrder: 170,
    icon: 'shopping_bag',
    iconColor: 'text-emerald-600',
    purpose: 'Provides order, customer and fulfillment truth and executes approved commerce-side actions.',
    triggers: ['Order inquiry', 'Order contradiction', 'Approved commerce writeback'],
    dependencies: ['Shopify connector', 'Resolution Executor'],
    ioLogic: { input: 'Shopify action/read request', output: 'Shopify state/result' },
  },
  {
    id: 'agent_oms_erp',
    slug: 'oms-erp-agent',
    name: 'OMS / ERP Agent',
    description: 'Handles back-office order/refund/return records in OMS/ERP.',
    category: 'system_tool',
    isSystem: 1,
    isLocked: 0,
    runtimeKind: 'connector',
    implementationMode: 'implemented',
    modelTier: 'none',
    sortOrder: 180,
    icon: 'inventory',
    iconColor: 'text-stone-600',
    purpose: 'Maintains back-office truth for order, refund and return references and executes approved ERP writebacks.',
    triggers: ['Back-office mismatch', 'Missing ERP reference', 'Approved writeback'],
    dependencies: ['Resolution Executor', 'Identity Mapping Agent'],
    ioLogic: { input: 'Back-office sync request', output: 'OMS/ERP result' },
  },
  {
    id: 'agent_returns',
    slug: 'returns-agent',
    name: 'Returns Agent',
    description: 'Handles return lifecycle state, block/unblock logic, label/inspection/restock progression.',
    category: 'system_tool',
    isSystem: 1,
    isLocked: 0,
    runtimeKind: 'system',
    implementationMode: 'implemented',
    modelTier: 'none',
    sortOrder: 190,
    icon: 'assignment_return',
    iconColor: 'text-orange-600',
    purpose: 'Owns return progression, dependency checks and unblock logic once refund and logistics truth are aligned.',
    triggers: ['Return requested', 'Label created', 'Warehouse update', 'Refund reconciled'],
    dependencies: ['Shopify Agent', 'OMS / ERP Agent', 'Logistics / Tracking Agent'],
    ioLogic: { input: 'Return state + dependencies', output: 'Return progression state' },
  },
  {
    id: 'agent_subscription',
    slug: 'subscription-agent',
    name: 'Recharge / Subscription Agent',
    description: 'Handles subscription/renewal/charge state for subscription commerce.',
    category: 'system_tool',
    isSystem: 1,
    isLocked: 0,
    runtimeKind: 'connector',
    implementationMode: 'implemented',
    modelTier: 'none',
    sortOrder: 200,
    icon: 'autorenew',
    iconColor: 'text-violet-600',
    purpose: 'Reads subscription truth and performs authorized subscription lifecycle changes.',
    triggers: ['Subscription case', 'Renewal issue', 'Billing contradiction'],
    dependencies: ['Stripe Agent', 'Shopify Agent'],
    ioLogic: { input: 'Subscription request', output: 'Subscription state/result' },
  },
  {
    id: 'agent_logistics',
    slug: 'logistics-tracking-agent',
    name: 'Logistics / Tracking Agent',
    description: 'Handles shipment/tracking/address-related logistics signals.',
    category: 'system_tool',
    isSystem: 1,
    isLocked: 0,
    runtimeKind: 'connector',
    implementationMode: 'implemented',
    modelTier: 'none',
    sortOrder: 210,
    icon: 'local_shipping',
    iconColor: 'text-blue-600',
    purpose: 'Reads tracking and shipping signals, detects logistics contradictions and supports downstream return decisions.',
    triggers: ['Shipment update', 'Delivery event', 'Address issue', 'Return logistics event'],
    dependencies: ['Shopify Agent', 'Returns Agent'],
    ioLogic: { input: 'Tracking/logistics query', output: 'Logistics truth' },
  },
  {
    id: 'agent_sla_escalation',
    slug: 'sla-escalation-agent',
    name: 'SLA & Escalation Agent',
    description: 'Monitors aging cases, stalled resolutions, delayed approvals, and blocked flows.',
    category: 'observability_communication',
    isSystem: 1,
    isLocked: 0,
    runtimeKind: 'system',
    implementationMode: 'implemented',
    modelTier: 'none',
    sortOrder: 220,
    icon: 'warning',
    iconColor: 'text-red-600',
    purpose: 'Tracks breach risk and escalates blocked operational flows to the correct owner or team.',
    triggers: ['SLA threshold exceeded', 'Approval delayed', 'Workflow stalled'],
    dependencies: ['Workflow Runtime Agent', 'Approval Gatekeeper', 'Audit & Observability Agent'],
    ioLogic: { input: 'Open conflicts + SLA policy', output: 'Escalation event' },
  },
  {
    id: 'agent_customer_communication',
    slug: 'customer-communication-agent',
    name: 'Customer Communication Agent',
    description: 'Decides when customer-facing communication should happen based on real reconciled operational state.',
    category: 'observability_communication',
    isSystem: 1,
    isLocked: 0,
    runtimeKind: 'system',
    implementationMode: 'implemented',
    modelTier: 'none',
    sortOrder: 230,
    icon: 'chat',
    iconColor: 'text-blue-600',
    purpose: 'Chooses when communication is safe, necessary and aligned with the reconciled truth before drafting or sending.',
    triggers: ['Resolution progressed', 'Customer waiting too long', 'Update required'],
    dependencies: ['Composer + Translator', 'QA / Policy Check', 'Helpdesk Agent', 'Follow-up Agent'],
    ioLogic: { input: 'Reconciled operational truth', output: 'Communication objective' },
  },
  {
    id: 'agent_follow_up',
    slug: 'follow-up-agent',
    name: 'Follow-up Agent',
    description: 'Coordinates post-resolution nudges, reminders, and closure follow-ups.',
    category: 'observability_communication',
    isSystem: 0,
    isLocked: 0,
    runtimeKind: 'system',
    implementationMode: 'delegated',
    modelTier: 'none',
    sortOrder: 235,
    icon: 'follow_the_signs',
    iconColor: 'text-fuchsia-600',
    purpose: 'Schedules and prepares follow-up actions once the main customer communication has been sent.',
    triggers: ['Approval resolved', 'Customer still waiting', 'Case reopened'],
    dependencies: ['Customer Communication Agent', 'Workflow Runtime Agent', 'SLA & Escalation Agent'],
    ioLogic: { input: 'Case outcome + comms state', output: 'Follow-up action plan' },
  },
  {
    id: 'agent_audit',
    slug: 'audit-observability',
    name: 'Audit & Observability Agent',
    description: 'Records executions, failures, retries, overrides, and recurring contradictions.',
    category: 'observability_communication',
    isSystem: 1,
    isLocked: 1,
    runtimeKind: 'system',
    implementationMode: 'implemented',
    modelTier: 'none',
    sortOrder: 240,
    icon: 'visibility',
    iconColor: 'text-gray-600',
    purpose: 'Captures runtime evidence, failure signals and recurring issues for operations, reporting and debugging.',
    triggers: ['Any important runtime event', 'Retry triggered', 'Execution completed'],
    dependencies: ['All runtime agents', 'Operations reports'],
    ioLogic: { input: 'Runtime event', output: 'Audit/observability record' },
  },
];

export function getCatalogEntryBySlug(slug: string): AgentCatalogEntry | undefined {
  return AGENT_CATALOG.find((entry) => entry.slug === slug);
}
