// Extracted from Workflows.tsx — pure data, safe to import from non-React code (tests).

export const TEMPLATES = [
  {
    id: 'refund_guarded',
    label: 'Guarded refund',
    category: 'Payments & risk',
    description: 'Evaluate policy, route high-value refunds to approval, and execute safe refunds.',
    nodes: [
      { type: 'trigger', key: 'message.received', label: 'Refund request', position: { x: 100, y: 240 } },
      { type: 'policy', key: 'policy.evaluate', label: 'Check refund policy', position: { x: 420, y: 220 }, config: { policy: 'refund_policy' } },
      { type: 'condition', key: 'amount.threshold', label: 'Amount under threshold', position: { x: 760, y: 220 }, config: { field: 'payment.amount', operator: '<=', value: 250 } },
      { type: 'action', key: 'payment.refund', label: 'Issue refund', position: { x: 1100, y: 150 }, config: { amount: '{{payment.amount}}', reason: '{{case.reason}}' } },
      { type: 'action', key: 'approval.create', label: 'Request approval', position: { x: 1100, y: 330 }, config: { queue: 'manager' } },
    ],
    edges: [
      { source: 0, target: 1, label: 'next' },
      { source: 1, target: 2, label: 'next' },
      { source: 2, target: 3, label: 'true', sourceHandle: 'true' },
      { source: 2, target: 4, label: 'false', sourceHandle: 'false' },
    ],
  },
  {
    id: 'packing_guard',
    label: 'Damaged shipment guard',
    category: 'Orders & fulfillment',
    description: 'Detect damaged shipment cases, search policy, and create a guided internal note.',
    nodes: [
      { type: 'trigger', key: 'order.updated', label: 'Order updated', position: { x: 120, y: 260 } },
      { type: 'knowledge', key: 'knowledge.search', label: 'Damage policy', position: { x: 440, y: 240 }, config: { query: 'damaged shipment premium replacement' } },
      { type: 'action', key: 'case.note', label: 'Create internal note', position: { x: 780, y: 240 }, config: { content: 'Damage policy reviewed. Replacement evidence required before refund.' } },
    ],
  },
  {
    id: 'payment_dispute',
    label: 'Payment dispute review',
    category: 'Payments & risk',
    description: 'Pause risky payment disputes, call PSP connector, and ask finance approval.',
    nodes: [
      { type: 'trigger', key: 'payment.failed', label: 'Payment failed', position: { x: 100, y: 260 } },
      { type: 'integration', key: 'connector.call', label: 'Check PSP event', position: { x: 420, y: 240 }, config: { capability: 'payment.lookup' } },
      { type: 'condition', key: 'risk.level', label: 'High risk?', position: { x: 760, y: 240 }, config: { field: 'payment.risk_level', value: 'high' } },
      { type: 'action', key: 'approval.create', label: 'Finance approval', position: { x: 1100, y: 240 }, config: { queue: 'finance', action_type: 'payment_dispute_review' } },
    ],
  },
  {
    id: 'flow_orchestration',
    label: 'Flow orchestration',
    category: 'Orchestration & data',
    description: 'Filter, branch, wait, merge and hand off to reusable workflows.',
    nodes: [
      { type: 'trigger', key: 'case.created', label: 'Case created', position: { x: 100, y: 260 } },
      { type: 'condition', key: 'flow.filter', label: 'Filter eligible cases', position: { x: 390, y: 240 }, config: { expression: 'case.priority >= 2' } },
      { type: 'condition', key: 'flow.switch', label: 'Route by segment', position: { x: 720, y: 240 }, config: { branch: 'customer.segment', comparison: 'vip|standard|enterprise' } },
      { type: 'utility', key: 'flow.wait', label: 'Wait for SLA window', position: { x: 1040, y: 140 }, config: { timeout: '2h' } },
      { type: 'utility', key: 'flow.subworkflow', label: 'Call review sub-workflow', position: { x: 1040, y: 300 }, config: { workflow: 'review_case_flow' } },
      { type: 'utility', key: 'flow.merge', label: 'Merge branches', position: { x: 1360, y: 240 }, config: { mode: 'wait-all' } },
      { type: 'utility', key: 'flow.stop_error', label: 'Stop on error', position: { x: 1680, y: 240 }, config: { errorMessage: 'Flow stopped after failed policy check.' } },
    ],
    edges: [
      { source: 0, target: 1, label: 'next' },
      { source: 1, target: 2, label: 'next' },
      { source: 2, target: 3, label: 'vip', sourceHandle: 'vip' },
      { source: 2, target: 4, label: 'standard', sourceHandle: 'standard' },
      { source: 2, target: 6, label: 'other', sourceHandle: 'other' },
      { source: 3, target: 5, label: 'next' },
      { source: 4, target: 5, label: 'next' },
      { source: 5, target: 6, label: 'next' },
    ],
  },
  {
    id: 'vip_escalation',
    label: 'VIP escalation',
    category: 'Support operations',
    description: 'Detect VIP cases, assign to senior support, and create a clear note.',
    nodes: [
      { type: 'trigger', key: 'case.created', label: 'Case created', position: { x: 100, y: 260 } },
      { type: 'condition', key: 'status.matches', label: 'VIP customer', position: { x: 420, y: 240 }, config: { field: 'customer.segment', value: 'vip' } },
      { type: 'action', key: 'case.assign', label: 'Assign senior team', position: { x: 760, y: 160 }, config: { teamId: 'senior_support' } },
      { type: 'action', key: 'case.note', label: 'Create VIP note', position: { x: 760, y: 340 }, config: { content: 'VIP escalation workflow triggered.' } },
    ],
  },
  {
    id: 'sla_breach',
    label: 'SLA breach',
    category: 'Support operations',
    description: 'Delay, evaluate SLA policy, and escalate stale cases.',
    nodes: [
      { type: 'trigger', key: 'case.created', label: 'Case created', position: { x: 100, y: 260 } },
      { type: 'utility', key: 'delay', label: 'Wait SLA window', position: { x: 420, y: 240 }, config: { duration: '2h' } },
      { type: 'policy', key: 'policy.evaluate', label: 'Evaluate SLA', position: { x: 740, y: 240 }, config: { policy: 'sla_response' } },
      { type: 'action', key: 'approval.create', label: 'Manager review', position: { x: 1060, y: 240 }, config: { queue: 'manager', action_type: 'sla_breach' } },
    ],
  },
  {
    id: 'return_inspection',
    label: 'Return inspection',
    category: 'Returns & recovery',
    description: 'Create return, search inspection policy, and route high-value returns.',
    nodes: [
      { type: 'trigger', key: 'return.created', label: 'Return created', position: { x: 100, y: 260 } },
      { type: 'knowledge', key: 'knowledge.search', label: 'Inspection policy', position: { x: 420, y: 240 }, config: { query: 'return inspection policy' } },
      { type: 'condition', key: 'amount.threshold', label: 'Value above limit?', position: { x: 760, y: 240 }, config: { field: 'return.total_amount', operator: '>', value: 250 } },
      { type: 'action', key: 'approval.create', label: 'Inspection approval', position: { x: 1100, y: 240 }, config: { queue: 'returns' } },
    ],
  },
  {
    id: 'fraud_risk_review',
    label: 'Fraud risk review',
    category: 'Payments & risk',
    description: 'Run risk agent, branch by confidence, and block unsafe automation.',
    nodes: [
      { type: 'trigger', key: 'order.updated', label: 'Order updated', position: { x: 100, y: 260 } },
      { type: 'agent', key: 'agent.run', label: 'Risk agent', position: { x: 420, y: 240 }, config: { agent: 'risk-agent' } },
      { type: 'condition', key: 'risk.level', label: 'Critical risk?', position: { x: 760, y: 240 }, config: { field: 'agent.risk_level', value: 'critical' } },
      { type: 'action', key: 'approval.create', label: 'Risk approval', position: { x: 1100, y: 240 }, config: { queue: 'risk' } },
    ],
  },
  {
    id: 'agent_triage',
    label: 'Auto-triage with agent',
    category: 'AI & knowledge',
    description: 'Run a specialist agent, check confidence, and escalate when needed.',
    nodes: [
      { type: 'trigger', key: 'case.created', label: 'Case created', position: { x: 110, y: 260 } },
      { type: 'agent', key: 'agent.run', label: 'AI Agent', position: { x: 420, y: 220 }, config: { agent: 'triage-agent' } },
      { type: 'knowledge', key: 'knowledge.search', label: 'Search knowledge', position: { x: 720, y: 390 }, config: { query: '{{case.intent}}' } },
      { type: 'condition', key: 'risk.level', label: 'High risk?', position: { x: 780, y: 200 }, config: { field: 'agent.risk_level', value: 'high' } },
      { type: 'action', key: 'approval.create', label: 'Request approval', position: { x: 1120, y: 200 }, config: { queue: 'manager' } },
    ],
  },
  // ─── Production-grade default templates ──────────────────────────────────
  {
    id: 'tpl_refund_guarded_v2',
    label: 'Reembolso automático con aprobación bajo umbral',
    category: 'Payments & risk',
    description: 'Reembolsos rápidos cuando la política lo permite y bajo umbral; el resto va a aprobación humana. Cierra el caso con respuesta y email.',
    nodes: [
      { type: 'trigger', key: 'case.created', label: 'Caso de reembolso', position: { x: 80, y: 260 }, config: { tag: 'refund_request' } },
      { type: 'knowledge', key: 'knowledge.search', label: 'Buscar política reembolsos', position: { x: 340, y: 240 }, config: { query: 'política de reembolsos plazos elegibilidad' } },
      { type: 'policy', key: 'policy.evaluate', label: 'Evaluar política', position: { x: 600, y: 240 }, config: { policy: 'refund_policy', field: 'payment.amount', operator: '<=', blockValue: '100' } },
      { type: 'condition', key: 'flow.if', label: 'Política aprueba reembolso', position: { x: 860, y: 240 }, config: { field: 'policy.allow', operator: '==', value: 'true' } },
      { type: 'action', key: 'payment.refund', label: 'Emitir reembolso', position: { x: 1140, y: 120 }, config: { paymentId: '{{payment.id}}', amount: '{{payment.amount}}', reason: 'Reembolso automático aprobado por política' } },
      { type: 'action', key: 'case.reply', label: 'Confirmar al cliente', position: { x: 1400, y: 120 }, config: { content: 'Hola {{customer.name}}, hemos procesado tu reembolso de {{payment.amount}} EUR. Lo verás reflejado en 3-5 días.' } },
      { type: 'action', key: 'notification.email', label: 'Email confirmación', position: { x: 1660, y: 120 }, config: { to: '{{customer.email}}', subject: 'Reembolso confirmado — pedido {{order.id}}', content: 'Hola {{customer.name}},\n\nTu reembolso por {{payment.amount}} EUR ha sido procesado.\n\nGracias.' } },
      { type: 'action', key: 'approval.create', label: 'Aprobación humana', position: { x: 1140, y: 380 }, config: { queue: 'manager', action_type: 'payment_refund_approval', priority: 'normal', reason: 'Reembolso fuera de política automática' } },
      { type: 'action', key: 'case.update_status', label: 'Esperando aprobación', position: { x: 1400, y: 380 }, config: { status: 'pending', reason: 'Awaiting approval' } },
    ],
    edges: [
      { source: 0, target: 1, label: 'next' },
      { source: 1, target: 2, label: 'next' },
      { source: 2, target: 3, label: 'next' },
      { source: 3, target: 4, label: 'true', sourceHandle: 'true' },
      { source: 4, target: 5, label: 'next' },
      { source: 5, target: 6, label: 'next' },
      { source: 3, target: 7, label: 'false', sourceHandle: 'false' },
      { source: 7, target: 8, label: 'next' },
    ],
  },
  {
    id: 'tpl_onboarding_v1',
    label: 'Onboarding de cliente nuevo (multi-canal)',
    category: 'Customer lifecycle',
    description: 'Da la bienvenida a clientes nuevos con secuencia de emails y un SMS de re-engagement si no han vuelto a entrar tras 4 días.',
    nodes: [
      { type: 'trigger', key: 'webhook.received', label: 'Cliente registrado', position: { x: 80, y: 260 }, config: { event: 'customer.signed_up' } },
      { type: 'utility', key: 'data.set_fields', label: 'Enriquecer perfil', position: { x: 340, y: 240 }, config: { field: 'customer.segment', value: 'new' } },
      { type: 'action', key: 'notification.email', label: 'Email de bienvenida', position: { x: 600, y: 240 }, config: { to: '{{customer.email}}', subject: 'Bienvenido a CRM-AI, {{customer.name}}', content: 'Hola {{customer.name}},\n\nNos alegra tenerte. Aquí tienes los primeros pasos para empezar...' } },
      { type: 'utility', key: 'flow.wait', label: 'Esperar 1 día', position: { x: 860, y: 240 }, config: { timeout: '1d', mode: 'auto' } },
      { type: 'action', key: 'notification.email', label: 'Tips & tutoriales', position: { x: 1120, y: 240 }, config: { to: '{{customer.email}}', subject: '5 trucos para sacar partido a CRM-AI', content: 'Hola {{customer.name}},\n\nAquí tienes nuestros mejores consejos...' } },
      { type: 'utility', key: 'flow.wait', label: 'Esperar 3 días', position: { x: 1380, y: 240 }, config: { timeout: '3d', mode: 'auto' } },
      { type: 'condition', key: 'flow.if', label: '¿Cliente activo?', position: { x: 1640, y: 240 }, config: { field: 'customer.last_seen_within', operator: '<=', value: '2d' } },
      { type: 'utility', key: 'flow.noop', label: 'Activo: fin', position: { x: 1900, y: 140 } },
      { type: 'action', key: 'notification.sms', label: 'SMS re-engagement', position: { x: 1900, y: 360 }, config: { to: '{{customer.phone}}', content: 'Hola {{customer.name}}, ¿necesitas ayuda para empezar? Responde a este SMS.' } },
    ],
    edges: [
      { source: 0, target: 1, label: 'next' },
      { source: 1, target: 2, label: 'next' },
      { source: 2, target: 3, label: 'next' },
      { source: 3, target: 4, label: 'next' },
      { source: 4, target: 5, label: 'next' },
      { source: 5, target: 6, label: 'next' },
      { source: 6, target: 7, label: 'true', sourceHandle: 'true' },
      { source: 6, target: 8, label: 'false', sourceHandle: 'false' },
    ],
  },
  {
    id: 'tpl_vip_escalation_v2',
    label: 'Escalamiento de cases VIP',
    category: 'Support operations',
    description: 'Detecta clientes VIP, los asigna al equipo senior con notificación a Slack, y avisa por SMS al on-call si la urgencia es crítica.',
    nodes: [
      { type: 'trigger', key: 'case.created', label: 'Caso creado', position: { x: 80, y: 280 } },
      { type: 'knowledge', key: 'knowledge.search', label: 'Contexto del cliente', position: { x: 340, y: 260 }, config: { query: 'cliente {{customer.id}} historial VIP' } },
      { type: 'condition', key: 'flow.if', label: '¿Es VIP?', position: { x: 600, y: 260 }, config: { field: 'customer.segment', operator: '==', value: 'VIP' } },
      { type: 'action', key: 'case.assign', label: 'Asignar equipo VIP', position: { x: 880, y: 100 }, config: { teamId: 'vip_support' } },
      { type: 'integration', key: 'message.slack', label: 'Avisar #vip-support', position: { x: 1140, y: 100 }, config: { channel: '#vip-support', content: ':star: Caso VIP {{case.case_number}} de {{customer.name}} — {{case.subject}}' } },
      { type: 'agent', key: 'agent.classify', label: 'Clasificar urgencia', position: { x: 1400, y: 100 }, config: { text: '{{case.description}}', intent: 'urgency' } },
      { type: 'condition', key: 'flow.if', label: '¿Urgente?', position: { x: 1660, y: 100 }, config: { field: 'agent.priority', operator: '==', value: 'critical' } },
      { type: 'action', key: 'notification.sms', label: 'SMS al on-call', position: { x: 1920, y: 60 }, config: { to: '{{oncall.phone}}', content: 'URGENTE: caso VIP {{case.case_number}} requiere atención inmediata.' } },
      { type: 'agent', key: 'agent.classify', label: 'Clasificar prioridad', position: { x: 880, y: 420 }, config: { text: '{{case.description}}' } },
      { type: 'action', key: 'case.set_priority', label: 'Aplicar prioridad', position: { x: 1140, y: 420 }, config: { priority: 'medium' } },
      { type: 'action', key: 'case.assign', label: 'Asignar round-robin', position: { x: 1400, y: 420 }, config: { teamId: 'general_support' } },
    ],
    edges: [
      { source: 0, target: 1, label: 'next' },
      { source: 1, target: 2, label: 'next' },
      { source: 2, target: 3, label: 'true', sourceHandle: 'true' },
      { source: 3, target: 4, label: 'next' },
      { source: 4, target: 5, label: 'next' },
      { source: 5, target: 6, label: 'next' },
      { source: 6, target: 7, label: 'true', sourceHandle: 'true' },
      { source: 2, target: 8, label: 'false', sourceHandle: 'false' },
      { source: 8, target: 9, label: 'next' },
      { source: 9, target: 10, label: 'next' },
    ],
  },
  {
    id: 'tpl_post_resolution_nps',
    label: 'Seguimiento post-resolución con NPS',
    category: 'Support operations',
    description: 'Tras resolver un caso, espera y envía encuesta NPS por Gmail; reacciona a detractores con escalación interna y a promotores con invitación al programa de advocacy.',
    nodes: [
      { type: 'trigger', key: 'case.updated', label: 'Caso resuelto', position: { x: 80, y: 260 }, config: { status: 'resolved' } },
      { type: 'utility', key: 'flow.wait', label: 'Esperar 24h', position: { x: 340, y: 240 }, config: { timeout: '24h', mode: 'auto' } },
      { type: 'integration', key: 'message.gmail', label: 'Encuesta NPS (Gmail)', position: { x: 600, y: 240 }, config: { to: '{{customer.email}}', subject: '¿Cómo lo hicimos? — caso {{case.case_number}}', content: 'Hola {{customer.name}},\n\n¿Recomendarías nuestro soporte? https://crm.ai/nps/{{case.id}}\n\nGracias.', replyToCaseId: '{{case.id}}' } },
      { type: 'utility', key: 'flow.wait', label: 'Esperar 7 días', position: { x: 860, y: 240 }, config: { timeout: '7d', mode: 'auto' } },
      { type: 'condition', key: 'flow.switch', label: 'Rango NPS', position: { x: 1120, y: 240 }, config: { field: 'nps.score', comparison: 'detractor|promoter|neutral' } },
      { type: 'action', key: 'case.note', label: 'Crear seguimiento detractor', position: { x: 1380, y: 100 }, config: { content: 'Cliente detractor (NPS {{nps.score}}). Revisar internamente.' } },
      { type: 'integration', key: 'message.slack', label: 'Avisar #cs-leadership', position: { x: 1640, y: 100 }, config: { channel: '#cs-leadership', content: ':warning: Detractor NPS {{nps.score}} — caso {{case.case_number}}' } },
      { type: 'action', key: 'notification.email', label: 'Email agradecimiento', position: { x: 1380, y: 260 }, config: { to: '{{customer.email}}', subject: '¡Gracias por tu valoración!', content: 'Hola {{customer.name}}, gracias por puntuarnos. Te invitamos a nuestro programa de advocacy: https://crm.ai/advocacy' } },
      { type: 'utility', key: 'flow.noop', label: 'Sin acción', position: { x: 1380, y: 420 } },
    ],
    edges: [
      { source: 0, target: 1, label: 'next' },
      { source: 1, target: 2, label: 'next' },
      { source: 2, target: 3, label: 'next' },
      { source: 3, target: 4, label: 'next' },
      { source: 4, target: 5, label: 'detractor', sourceHandle: 'detractor' },
      { source: 5, target: 6, label: 'next' },
      { source: 4, target: 7, label: 'promoter', sourceHandle: 'promoter' },
      { source: 4, target: 8, label: 'neutral', sourceHandle: 'neutral' },
    ],
  },
  {
    id: 'tpl_fraud_order_validation',
    label: 'Validación de pedidos sospechosos (fraude)',
    category: 'Payments & risk',
    description: 'Para pedidos > 500€, llama a un servicio antifraude vía connector y enruta el riesgo (low/medium/high) a aprobación, hold + caso o auto-aprobación.',
    nodes: [
      { type: 'trigger', key: 'order.updated', label: 'Pedido > 500€', position: { x: 80, y: 280 }, config: { event: 'order.created', minAmount: 500 } },
      { type: 'utility', key: 'data.http_request', label: 'Llamar API antifraude', position: { x: 340, y: 260 }, config: { url: 'https://api.fraudshield.io/v1/score', method: 'POST', body: '{"orderId":"{{order.id}}","amount":{{order.total_amount}}}' } },
      { type: 'integration', key: 'connector.call', label: 'Conector fraude (fallback)', position: { x: 600, y: 260 }, config: { connector: 'fraudshield', capability: 'score_order', input: '{"orderId":"{{order.id}}"}' } },
      { type: 'condition', key: 'flow.switch', label: 'Score de riesgo', position: { x: 880, y: 260 }, config: { field: 'fraud.risk_score', comparison: 'low|medium|high' } },
      { type: 'action', key: 'order.release', label: 'Auto-aprobar', position: { x: 1180, y: 100 }, config: { orderId: '{{order.id}}', reason: 'Antifraude: riesgo bajo' } },
      { type: 'action', key: 'approval.create', label: 'Revisión manual', position: { x: 1180, y: 280 }, config: { queue: 'risk', action_type: 'fraud_manual_review', priority: 'normal' } },
      { type: 'action', key: 'order.hold', label: 'Bloquear pedido', position: { x: 1180, y: 460 }, config: { orderId: '{{order.id}}', reason: 'Antifraude: riesgo alto', requires_approval: 'true' } },
      { type: 'action', key: 'notification.email', label: 'Avisar al cliente', position: { x: 1460, y: 460 }, config: { to: '{{customer.email}}', subject: 'Verificación de tu pedido {{order.id}}', content: 'Hola {{customer.name}}, hemos detectado actividad inusual y necesitamos verificar tu pedido.' } },
      { type: 'action', key: 'case.note', label: 'Caso para investigación', position: { x: 1740, y: 460 }, config: { content: 'Pedido {{order.id}} bloqueado por riesgo alto antifraude. Score: {{fraud.risk_score}}.' } },
    ],
    edges: [
      { source: 0, target: 1, label: 'next' },
      { source: 1, target: 2, label: 'next' },
      { source: 2, target: 3, label: 'next' },
      { source: 3, target: 4, label: 'low', sourceHandle: 'low' },
      { source: 3, target: 5, label: 'medium', sourceHandle: 'medium' },
      { source: 3, target: 6, label: 'high', sourceHandle: 'high' },
      { source: 6, target: 7, label: 'next' },
      { source: 7, target: 8, label: 'next' },
    ],
  },
  {
    id: 'tpl_abandoned_cart_v1',
    label: 'Recordatorio de carrito abandonado',
    category: 'Customer lifecycle',
    description: 'Cada hora busca carritos abandonados (>1h, <24h) y envía recordatorio con descuento por email o WhatsApp según preferencia del cliente.',
    nodes: [
      { type: 'trigger', key: 'trigger.schedule', label: 'Cada hora', position: { x: 80, y: 260 }, config: { cron: '0 * * * *' } },
      { type: 'integration', key: 'connector.call', label: 'Carritos abandonados', position: { x: 340, y: 240 }, config: { connector: 'shop', capability: 'list_abandoned_carts', input: '{"olderThan":"1h","youngerThan":"24h"}' } },
      { type: 'utility', key: 'flow.loop', label: 'Iterar carritos', position: { x: 600, y: 240 }, config: { source: 'data.carts', batchSize: 1, maxIterations: 500 } },
      { type: 'condition', key: 'flow.if', label: '¿Email opt-in?', position: { x: 880, y: 240 }, config: { field: 'item.customer.email_opt_in', operator: '==', value: 'true' } },
      { type: 'action', key: 'notification.email', label: 'Email recordatorio', position: { x: 1160, y: 100 }, config: { to: '{{item.customer.email}}', subject: '¿Olvidaste algo? Aquí tienes 10% de descuento', content: 'Hola {{item.customer.name}}, tu carrito te espera. Usa COMEBACK10 al pagar.' } },
      { type: 'condition', key: 'flow.if', label: '¿Tiene WhatsApp?', position: { x: 1160, y: 380 }, config: { field: 'item.customer.phone', operator: 'exists', value: 'true' } },
      { type: 'action', key: 'notification.whatsapp', label: 'WhatsApp recordatorio', position: { x: 1440, y: 380 }, config: { to: '{{item.customer.phone}}', content: 'Hola {{item.customer.name}}, tu carrito sigue ahí. 10% de descuento con COMEBACK10.' } },
      { type: 'utility', key: 'flow.noop', label: 'Sin canal', position: { x: 1440, y: 520 } },
      { type: 'policy', key: 'core.audit_log', label: 'Auditar envío', position: { x: 1720, y: 240 }, config: { action: 'CART_REMINDER_SENT', entityType: 'customer', entityId: '{{item.customer.id}}' } },
    ],
    edges: [
      { source: 0, target: 1, label: 'next' },
      { source: 1, target: 2, label: 'next' },
      { source: 2, target: 3, label: 'item' },
      { source: 3, target: 4, label: 'true', sourceHandle: 'true' },
      { source: 3, target: 5, label: 'false', sourceHandle: 'false' },
      { source: 5, target: 6, label: 'true', sourceHandle: 'true' },
      { source: 5, target: 7, label: 'false', sourceHandle: 'false' },
      { source: 4, target: 8, label: 'next' },
      { source: 6, target: 8, label: 'next' },
    ],
  },
  {
    id: 'tpl_returns_processing',
    label: 'Procesamiento de devoluciones',
    category: 'Returns & recovery',
    description: 'Evalúa la ventana de devolución, crea la devolución y envía la etiqueta; al recibir el paquete dispara reembolso. Si está fuera de plazo, responde y cierra.',
    nodes: [
      { type: 'trigger', key: 'return.created', label: 'Devolución solicitada', position: { x: 80, y: 260 } },
      { type: 'policy', key: 'policy.evaluate', label: 'Ventana de devolución', position: { x: 340, y: 240 }, config: { policy: 'return_window', field: 'order.delivered_days_ago', operator: '<=', blockValue: '30' } },
      { type: 'condition', key: 'flow.if', label: '¿Dentro de plazo?', position: { x: 620, y: 240 }, config: { field: 'policy.allow', operator: '==', value: 'true' } },
      { type: 'action', key: 'return.create', label: 'Crear devolución', position: { x: 900, y: 100 }, config: { reason: '{{return.reason}}', amount: '{{order.total_amount}}', method: 'original_payment' } },
      { type: 'action', key: 'notification.email', label: 'Enviar etiqueta', position: { x: 1160, y: 100 }, config: { to: '{{customer.email}}', subject: 'Tu etiqueta de devolución — pedido {{order.id}}', content: 'Hola {{customer.name}}, adjuntamos la etiqueta. Imprímela y entrégala en tu punto de envío.' } },
      { type: 'utility', key: 'flow.wait', label: 'Esperar recepción', position: { x: 1420, y: 100 }, config: { timeout: '14d', mode: 'manual_resume' } },
      { type: 'action', key: 'payment.refund', label: 'Emitir reembolso', position: { x: 1680, y: 100 }, config: { paymentId: '{{payment.id}}', amount: '{{return.amount}}', reason: 'Devolución recibida' } },
      { type: 'action', key: 'case.reply', label: 'Explicar política', position: { x: 900, y: 400 }, config: { content: 'Hola {{customer.name}}, lamentamos no poder aceptar la devolución: el plazo de 30 días ha expirado.' } },
      { type: 'action', key: 'case.update_status', label: 'Cerrar caso', position: { x: 1160, y: 400 }, config: { status: 'resolved', reason: 'Fuera de plazo de devolución' } },
    ],
    edges: [
      { source: 0, target: 1, label: 'next' },
      { source: 1, target: 2, label: 'next' },
      { source: 2, target: 3, label: 'true', sourceHandle: 'true' },
      { source: 3, target: 4, label: 'next' },
      { source: 4, target: 5, label: 'next' },
      { source: 5, target: 6, label: 'next' },
      { source: 2, target: 7, label: 'false', sourceHandle: 'false' },
      { source: 7, target: 8, label: 'next' },
    ],
  },
  {
    id: 'tpl_nightly_crm_sync',
    label: 'Sincronización CRM nocturna',
    category: 'Orchestration & data',
    description: 'Cada noche a las 2:00 trae cambios del CRM externo, los mapea y aplica a clientes/casos, registra auditoría y publica resumen diario en Slack.',
    nodes: [
      { type: 'trigger', key: 'trigger.schedule', label: 'Diario 02:00', position: { x: 80, y: 280 }, config: { cron: '0 2 * * *' } },
      { type: 'integration', key: 'connector.call', label: 'Fetch CRM externo', position: { x: 340, y: 260 }, config: { connector: 'salesforce', capability: 'list_updated_records', input: '{"since":"{{trigger.previous_run_at}}"}' } },
      { type: 'utility', key: 'flow.loop', label: 'Iterar registros', position: { x: 620, y: 260 }, config: { source: 'data.records', batchSize: 50, maxIterations: 5000 } },
      { type: 'utility', key: 'data.map_fields', label: 'Mapear campos', position: { x: 900, y: 260 }, config: { mapping: '{"customerId":"item.Id","name":"item.Name","email":"item.Email"}' } },
      { type: 'condition', key: 'flow.if', label: '¿Es caso o cliente?', position: { x: 1180, y: 260 }, config: { field: 'item.type', operator: '==', value: 'case' } },
      { type: 'action', key: 'case.update_status', label: 'Actualizar caso', position: { x: 1460, y: 140 }, config: { status: '{{item.status}}', reason: 'Nightly sync' } },
      { type: 'utility', key: 'data.set_fields', label: 'Actualizar cliente', position: { x: 1460, y: 380 }, config: { field: 'customer.external_id', value: '{{item.customerId}}' } },
      { type: 'utility', key: 'data.aggregate', label: 'Contar resultados', position: { x: 1740, y: 260 }, config: { source: 'data.records', field: 'id', operation: 'count', target: 'syncCount' } },
      { type: 'policy', key: 'core.audit_log', label: 'Auditar sync', position: { x: 2020, y: 260 }, config: { action: 'NIGHTLY_CRM_SYNC', message: 'Sincronizados {{data.syncCount}} registros', entityType: 'workflow' } },
      { type: 'integration', key: 'message.slack', label: 'Resumen #ops-daily', position: { x: 2300, y: 260 }, config: { channel: '#ops-daily', content: ':sparkles: Nightly CRM sync — {{data.syncCount}} registros procesados.' } },
    ],
    edges: [
      { source: 0, target: 1, label: 'next' },
      { source: 1, target: 2, label: 'next' },
      { source: 2, target: 3, label: 'item' },
      { source: 3, target: 4, label: 'next' },
      { source: 4, target: 5, label: 'true', sourceHandle: 'true' },
      { source: 4, target: 6, label: 'false', sourceHandle: 'false' },
      { source: 5, target: 7, label: 'done' },
      { source: 6, target: 7, label: 'done' },
      { source: 7, target: 8, label: 'next' },
      { source: 8, target: 9, label: 'next' },
    ],
  },
] as const;
