import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

dotenv.config({ path: '.env.local' });

const url = process.env.SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) throw new Error('Missing Supabase env vars');

const supabase = createClient(url, key, { auth: { persistSession: false } });
const tenantId = 'org_default';
const workspaceId = 'ws_default';
const now = {
  customer: '2026-04-18T07:50:00+00:00',
  history1: '2026-03-16T11:30:00+00:00',
  history2: '2026-04-02T11:40:00+00:00',
  current: '2026-04-18T08:10:00+00:00',
  msg1: '2026-04-18T08:14:00+00:00',
  msg2: '2026-04-18T08:19:00+00:00',
  msg3: '2026-04-18T08:31:00+00:00',
  msg4: '2026-04-18T08:41:00+00:00',
  approval: '2026-04-18T08:55:00+00:00',
  draft: '2026-04-18T08:58:00+00:00',
};

async function upsertRows(table: string, rows: any[]) {
  if (!rows.length) return;
  const normalizedRows = rows.map((row) => normalizeRecord(row));
  const { error } = await supabase.from(table).upsert(normalizedRows, { onConflict: 'id' });
  if (error) throw new Error(`${table}: ${error.message}`);
}

async function patch(table: string, match: Record<string, any>, values: Record<string, any>) {
  const { error } = await supabase.from(table).update(normalizeRecord(values)).match(match);
  if (error) throw new Error(`${table}: ${error.message}`);
}

function normalizeRecord<T extends Record<string, any>>(record: T): T {
  const normalized: Record<string, any> = {};
  for (const [key, value] of Object.entries(record)) {
    normalized[key] = normalizeValue(value);
  }
  return normalized as T;
}

function normalizeValue(value: any): any {
  if (Array.isArray(value) || (value && typeof value === 'object' && !(value instanceof Date))) {
    return JSON.stringify(value);
  }
  return value;
}

function baseOrder(id: string, external_order_id: string, customer_id: string, total_amount: number, order_date: string, status: string, summary: string, conflict = false, extra: any = {}) {
  return {
    id,
    external_order_id,
    customer_id,
    tenant_id: tenantId,
    workspace_id: workspaceId,
    status,
    fulfillment_status: extra.fulfillment_status ?? status,
    tracking_number: extra.tracking_number ?? `TRK-${external_order_id.slice(-5)}`,
    tracking_url: extra.tracking_url ?? `https://tracking.example.com/${external_order_id}`,
    shipping_address: extra.shipping_address ?? 'Calle Velázquez 10, Madrid',
    system_states: extra.system_states ?? { canonical: status, shopify: status, stripe: extra.stripe_state ?? 'captured', wms: extra.wms_state ?? status, policy: extra.policy_state ?? 'ok' },
    total_amount,
    currency: 'USD',
    country: 'ES',
    brand: 'Acme Store',
    channel: extra.channel ?? 'web',
    order_date,
    has_conflict: conflict ? 1 : 0,
    conflict_domain: extra.conflict_domain ?? null,
    conflict_detected: extra.conflict_detected ?? null,
    recommended_action: extra.recommended_action ?? 'No action needed',
    risk_level: extra.risk_level ?? (conflict ? 'high' : 'low'),
    order_type: extra.order_type ?? 'standard',
    approval_status: extra.approval_status ?? (conflict ? 'approval_needed' : 'not_required'),
    summary,
    last_sync_at: extra.last_sync_at ?? order_date,
    last_update: extra.last_update ?? order_date,
    badges: extra.badges ?? [],
    tab: extra.tab ?? 'all',
    created_at: extra.created_at ?? order_date,
    updated_at: extra.updated_at ?? order_date,
  };
}

function basePayment(id: string, external_payment_id: string, order_id: string, customer_id: string, amount: number, created_at: string, status: string, summary: string, conflict = false, extra: any = {}) {
  return {
    id,
    external_payment_id,
    order_id,
    customer_id,
    tenant_id: tenantId,
    workspace_id: workspaceId,
    amount,
    currency: 'USD',
    payment_method: extra.payment_method ?? 'Visa •••• 7744',
    psp: extra.psp ?? 'stripe',
    status,
    system_states: extra.system_states ?? { canonical: status, stripe: extra.stripe_state ?? status, oms: extra.oms_state ?? 'delivered' },
    dispute_id: extra.dispute_id ?? null,
    refund_ids: extra.refund_ids ?? [],
    risk_level: extra.risk_level ?? (conflict ? 'high' : 'low'),
    payment_type: extra.payment_type ?? 'standard',
    approval_status: extra.approval_status ?? (conflict ? 'approval_needed' : 'approved'),
    summary,
    has_conflict: conflict ? 1 : 0,
    conflict_detected: extra.conflict_detected ?? null,
    recommended_action: extra.recommended_action ?? 'No action needed',
    badges: extra.badges ?? [],
    tab: extra.tab ?? 'all',
    authorized_at: extra.authorized_at ?? created_at,
    captured_at: extra.captured_at ?? created_at,
    refund_status: extra.refund_status ?? null,
    refund_details: extra.refund_details ?? [],
    reconciliation_details: extra.reconciliation_details ?? {},
    refund_amount: extra.refund_amount ?? null,
    refund_type: extra.refund_type ?? null,
    dispute_reference: extra.dispute_reference ?? null,
    chargeback_amount: extra.chargeback_amount ?? null,
    created_at,
    updated_at: extra.updated_at ?? created_at,
    last_update: extra.last_update ?? created_at,
  };
}

function baseReturn(id: string, external_return_id: string, order_id: string, customer_id: string, return_value: number, created_at: string, status: string, summary: string, conflict = false, extra: any = {}) {
  return {
    id,
    external_return_id,
    order_id,
    customer_id,
    tenant_id: tenantId,
    workspace_id: workspaceId,
    type: extra.type ?? 'return',
    return_reason: extra.return_reason ?? 'Damaged item',
    return_value,
    status,
    inspection_status: extra.inspection_status ?? 'pending',
    refund_status: extra.refund_status ?? 'pending_review',
    carrier_status: extra.carrier_status ?? 'delivered',
    has_conflict: conflict ? 1 : 0,
    approval_status: extra.approval_status ?? (conflict ? 'approval_needed' : 'not_required'),
    risk_level: extra.risk_level ?? (conflict ? 'high' : 'low'),
    linked_refund_id: extra.linked_refund_id ?? null,
    linked_shipment_id: extra.linked_shipment_id ?? null,
    system_states: extra.system_states ?? { canonical: status, warehouse: status, policy: extra.policy_state ?? 'ok' },
    conflict_detected: extra.conflict_detected ?? null,
    recommended_action: extra.recommended_action ?? 'No action needed',
    summary,
    badges: extra.badges ?? [],
    tab: extra.tab ?? 'all',
    method: extra.method ?? 'carrier_pickup',
    received_at_warehouse: extra.received_at_warehouse ?? created_at,
    brand: extra.brand ?? 'Acme Store',
    country: extra.country ?? 'ES',
    currency: 'USD',
    last_update: extra.last_update ?? created_at,
    created_at,
    updated_at: extra.updated_at ?? created_at,
  };
}

async function main() {
  await upsertRows('customers', [{
    id: 'cust_maya',
    tenant_id: tenantId,
    workspace_id: workspaceId,
    canonical_email: 'maya.ortega@example.com',
    email: 'maya.ortega@example.com',
    phone: '+34 600 100 205',
    canonical_name: 'Maya Ortega',
    segment: 'vip',
    risk_level: 'medium',
    lifetime_value: 4860.25,
    currency: 'USD',
    preferred_channel: 'whatsapp',
    dispute_rate: 0.05,
    refund_rate: 0.22,
    chargeback_count: 0,
    total_orders: 18,
    total_spent: 4860.25,
    created_at: now.customer,
    updated_at: now.approval,
  }]);

  await upsertRows('linked_identities', [
    { id: 'li_maya_shopify', customer_id: 'cust_maya', tenant_id: tenantId, workspace_id: workspaceId, system: 'shopify', external_id: 'shopify-customer-55223', confidence: 0.99, verified: 1, verified_at: now.customer, created_at: now.customer },
    { id: 'li_maya_whatsapp', customer_id: 'cust_maya', tenant_id: tenantId, workspace_id: workspaceId, system: 'whatsapp', external_id: 'whatsapp:+34600100205', confidence: 0.97, verified: 1, verified_at: now.customer, created_at: now.customer },
  ]);

  await upsertRows('knowledge_domains', [{
    id: 'kd_repeat_exceptions',
    tenant_id: tenantId,
    workspace_id: workspaceId,
    name: 'Repeat Exceptions',
    description: 'Policies for repeated goodwill credits and manager escalations.',
    created_at: now.current,
  }]);

  await upsertRows('knowledge_articles', [
    {
      id: 'ka_repeat_goodwill_policy',
      tenant_id: tenantId,
      workspace_id: workspaceId,
      domain_id: 'kd_repeat_exceptions',
      title: 'Repeat goodwill exception policy',
      content: 'If a VIP customer has already received two goodwill exceptions in the last 120 days, any new replacement or credit must be escalated to a human manager. The assistant may explain the policy and draft the reply, but must not promise a credit before approval.',
      content_structured: { summary: 'Repeat exceptions over threshold require manager approval', threshold: { prior_exceptions_120d: 2, max_auto_credit_usd: 50 } },
      type: 'article',
      status: 'published',
      owner_user_id: 'user_alex',
      review_cycle_days: 45,
      last_reviewed_at: now.current,
      next_review_at: '2026-05-30T08:00:00+00:00',
      version: 1,
      citation_count: 7,
      last_cited_at: now.approval,
      outdated_flag: 0,
      linked_workflow_ids: ['wfd_006'],
      linked_approval_policy_ids: ['pr_repeat_goodwill_approval'],
      created_at: now.current,
      updated_at: now.approval,
    },
    {
      id: 'ka_manager_escalation_playbook',
      tenant_id: tenantId,
      workspace_id: workspaceId,
      domain_id: 'kd_repeat_exceptions',
      title: 'Manager escalation playbook',
      content: 'Summarize the current order, the earlier exceptions, and the exact reason a human is needed. Keep the reply minimal, calm, and decisive.',
      content_structured: { summary: 'How to escalate repeat exceptions cleanly' },
      type: 'article',
      status: 'published',
      owner_user_id: 'user_sarah',
      review_cycle_days: 60,
      last_reviewed_at: now.current,
      next_review_at: '2026-06-18T08:00:00+00:00',
      version: 1,
      citation_count: 4,
      last_cited_at: now.approval,
      outdated_flag: 0,
      linked_workflow_ids: ['wfd_006'],
      linked_approval_policy_ids: ['pr_repeat_goodwill_approval'],
      created_at: now.current,
      updated_at: now.approval,
    },
  ]);

  await upsertRows('policy_rules', [{
    id: 'pr_repeat_goodwill_approval',
    tenant_id: tenantId,
    workspace_id: workspaceId,
    knowledge_article_id: 'ka_repeat_goodwill_policy',
    name: 'Repeat goodwill exception rule',
    description: 'Customers with two or more courtesy exceptions in 120 days require manager approval.',
    entity_type: 'case',
    conditions: [
      { field: 'customer.prior_goodwill_exceptions_120d', operator: 'gte', value: 2 },
      { field: 'request.goodwill_credit_amount', operator: 'gt', value: 50 },
    ],
    action_mapping: { explain_policy: true, gather_evidence: true, draft_reply: true, never_auto_commit: true },
    approval_mapping: { requires_approval: true, approver_role: 'manager', max_auto_credit_usd: 0 },
    escalation_mapping: { route_to: 'team_support', priority: 'high', human_review: true },
    is_active: 1,
    version: 1,
    created_at: now.current,
  }]);

  const historyOrders = [
    baseOrder('order_009', 'ORD-55199', 'cust_maya', 129, '2026-03-16', 'delivered', 'Delivered order with a resolved replacement issue', false, { fulfillment_status: 'delivered', badges: ['Delivered', 'Resolved'] }),
    baseOrder('order_010', 'ORD-55207', 'cust_maya', 84, '2026-04-02', 'delivered', 'Delivered order with a courtesy delay credit', false, { channel: 'whatsapp', fulfillment_status: 'delivered', badges: ['Delivered', 'Courtesy Credit'] }),
    baseOrder('order_011', 'ORD-55223', 'cust_maya', 189, '2026-04-18', 'delivered', 'Delivered order with missing accessory and repeat-exception policy conflict', true, {
      channel: 'whatsapp',
      conflict_domain: 'policy',
      conflict_detected: 'Repeat goodwill exception request exceeds the human-approval threshold',
      recommended_action: 'Escalate to a manager before committing to replacement or credit',
      risk_level: 'high',
      approval_status: 'approval_needed',
      badges: ['Delivered', 'Policy Review', 'High Value'],
      tab: 'attention',
      policy_state: 'requires_approval',
      stripe_state: 'captured',
      wms_state: 'received',
    }),
  ];

  const historyPayments = [
    basePayment('pay_009', 'pi_009', 'order_009', 'cust_maya', 129, now.history1, 'refunded', 'Refund completed after the earlier replacement issue', false, { payment_method: 'Visa •••• 4432', refund_ids: ['refund_009'], refund_status: 'succeeded', refund_details: [{ attempt: 1, initiated_at: '2026-03-18T09:15:00Z', amount: 20, status: 'succeeded', psp_ref: 're_009_a' }], refund_amount: 20, refund_type: 'partial', badges: ['Refunded', 'Matched'], tab: 'refunds' }),
    basePayment('pay_010', 'pi_010', 'order_010', 'cust_maya', 84, now.history2, 'refunded', 'Partial courtesy refund completed for a delay complaint', false, { payment_method: 'Apple Pay', refund_ids: ['refund_010'], refund_status: 'succeeded', refund_details: [{ attempt: 1, initiated_at: '2026-04-03T11:40:00Z', amount: 15, status: 'succeeded', psp_ref: 're_010_a' }], refund_amount: 15, refund_type: 'partial', badges: ['Refunded', 'Courtesy'], tab: 'refunds' }),
    basePayment('pay_011', 'pi_011', 'order_011', 'cust_maya', 189, now.current, 'settled', 'Payment settled but the courtesy credit needs manager approval', true, { payment_method: 'Visa •••• 7744', refund_ids: ['refund_011'], approval_status: 'approval_needed', conflict_detected: 'Goodwill credit exceeds the repeat-exception threshold', recommended_action: 'Hold the credit until a manager reviews the case', badges: ['Captured', 'Policy Review', 'Repeat Customer'], tab: 'reconciliation', refund_status: 'pending_approval', refund_details: [{ attempt: 1, initiated_at: '2026-04-18T08:55:00Z', amount: 75, status: 'pending_approval', psp_ref: 're_011_a' }], refund_amount: 75, refund_type: 'partial', reconciliation_details: { status: 'pending', notes: 'Captured payment; courtesy credit is blocked until approval.' } }),
  ];

  const historyReturns = [
    baseReturn('return_009', 'RT-55199', 'order_009', 'cust_maya', 129, now.history1, 'received', 'Prior return closed cleanly', false, { inspection_status: 'inspected', refund_status: 'succeeded', linked_refund_id: 'refund_009', received_at_warehouse: '2026-03-19T10:00:00+00:00', badges: ['Received', 'Closed'] }),
    baseReturn('return_010', 'RT-55207', 'order_010', 'cust_maya', 84, now.history2, 'received', 'Second historical return already closed', false, { inspection_status: 'inspected', refund_status: 'succeeded', linked_refund_id: 'refund_010', received_at_warehouse: '2026-04-04T10:00:00+00:00', badges: ['Received', 'Closed'] }),
    baseReturn('return_011', 'RT-55223', 'order_011', 'cust_maya', 189, now.current, 'received', 'Return received, but the next step needs approval', true, { return_reason: 'Missing premium accessory and damaged box', inspection_status: 'pending', refund_status: 'pending_approval', linked_refund_id: 'refund_011', conflict_detected: 'Replacement and goodwill credit require approval because the customer already used two exceptions', recommended_action: 'Escalate to manager and avoid promising a credit', badges: ['Received', 'Policy Review', 'Approval Needed'], tab: 'refund_pending', policy_state: 'requires_approval', received_at_warehouse: '2026-04-18T08:25:00+00:00' }),
  ];

  await upsertRows('orders', historyOrders);
  await upsertRows('payments', historyPayments);
  await upsertRows('returns', historyReturns);
  await upsertRows('refunds', [
    { id: 'refund_009', external_refund_id: 'rf_009', payment_id: 'pay_009', order_id: 'order_009', customer_id: 'cust_maya', tenant_id: tenantId, amount: 20, currency: 'USD', type: 'partial', status: 'settled', reason: 'Resolved replacement credit from the earlier case', initiated_by: 'copilot', initiated_by_type: 'agent', approval_request_id: null, idempotency_key: 'refund-pay-009', created_at: now.history1, updated_at: now.history1 },
    { id: 'refund_010', external_refund_id: 'rf_010', payment_id: 'pay_010', order_id: 'order_010', customer_id: 'cust_maya', tenant_id: tenantId, amount: 15, currency: 'USD', type: 'partial', status: 'settled', reason: 'Courtesy delay credit', initiated_by: 'copilot', initiated_by_type: 'agent', approval_request_id: null, idempotency_key: 'refund-pay-010', created_at: now.history2, updated_at: now.history2 },
  ]);

  await upsertRows('cases', [{
    id: 'case_005',
    case_number: 'CAS-88223',
    tenant_id: tenantId,
    workspace_id: workspaceId,
    status: 'open',
    priority: 'high',
    severity: 'S1',
    risk_level: 'high',
    risk_score: 96,
    customer_id: 'cust_maya',
    conversation_id: 'conv_005',
    created_at: now.current,
    updated_at: now.current,
    last_activity_at: now.current,
  }]);

  const conversation = { id: 'conv_005', case_id: 'case_005', customer_id: 'cust_maya', channel: 'whatsapp', status: 'open', subject: 'Repeat replacement review for Maya Ortega', external_thread_id: 'wa-thread-55223', first_message_at: now.msg1, last_message_at: now.msg4, created_at: now.current, updated_at: now.approval, tenant_id: tenantId, workspace_id: workspaceId };
  const messages = [
    { id: 'msg_005_1', conversation_id: 'conv_005', case_id: 'case_005', customer_id: 'cust_maya', type: 'customer', direction: 'inbound', sender_id: 'cust_maya', sender_name: 'Maya Ortega', content: 'Hi, this is happening again. The premium accessory is missing and I would like the replacement handled without another delay.', content_type: 'text', channel: 'whatsapp', external_message_id: 'wa-msg-55223-1', sentiment: 'frustrated', sentiment_score: -0.42, attachments: [], sent_at: now.msg1, created_at: now.msg1, delivered_at: now.msg1, read_at: now.msg1, tenant_id: tenantId },
    { id: 'msg_005_2', conversation_id: 'conv_005', case_id: 'case_005', customer_id: 'cust_maya', type: 'agent', direction: 'outbound', sender_id: 'agent_copilot', sender_name: 'Copilot', content: 'I can see the earlier accommodations on the account. I am checking the policy and your current order history before I promise any credit.', content_type: 'text', channel: 'whatsapp', external_message_id: 'wa-msg-55223-2', sentiment: 'neutral', sentiment_score: 0.12, attachments: [], sent_at: now.msg2, created_at: now.msg2, delivered_at: now.msg2, read_at: now.msg2, tenant_id: tenantId },
    { id: 'msg_005_3', conversation_id: 'conv_005', case_id: 'case_005', customer_id: 'cust_maya', type: 'customer', direction: 'inbound', sender_id: 'cust_maya', sender_name: 'Maya Ortega', content: 'Understood. This is the second time in a short period, so I want to make sure the replacement is handled properly and the missing piece is replaced.', content_type: 'text', channel: 'whatsapp', external_message_id: 'wa-msg-55223-3', sentiment: 'concerned', sentiment_score: -0.18, attachments: [], sent_at: now.msg3, created_at: now.msg3, delivered_at: now.msg3, read_at: now.msg3, tenant_id: tenantId },
    { id: 'msg_005_4', conversation_id: 'conv_005', case_id: 'case_005', customer_id: 'cust_maya', type: 'agent', direction: 'outbound', sender_id: 'agent_qa_policy_check', sender_name: 'Policy Check', content: 'I have escalated this to a manager because the repeat-exception policy requires a human decision before any courtesy credit can be issued.', content_type: 'text', channel: 'whatsapp', external_message_id: 'wa-msg-55223-4', sentiment: 'steady', sentiment_score: 0.24, attachments: [], sent_at: now.msg4, created_at: now.msg4, delivered_at: now.msg4, read_at: now.msg4, tenant_id: tenantId },
  ];
  await upsertRows('conversations', [conversation]);
  await upsertRows('messages', messages);

  const caseRow = {
    id: 'case_005',
    case_number: 'CAS-88223',
    tenant_id: tenantId,
    workspace_id: workspaceId,
    source_system: 'whatsapp',
    source_channel: 'whatsapp',
    source_entity_id: 'wa-thread-55223',
    type: 'replacement_request',
    sub_type: 'repeat_customer_exception',
    intent: 'replacement_with_goodwill_credit',
    intent_confidence: 0.98,
    status: 'open',
    priority: 'high',
    severity: 'S1',
    risk_level: 'high',
    risk_score: 96,
    fraud_flag: 0,
    assigned_user_id: 'user_alex',
    assigned_team_id: 'team_support',
    created_by_user_id: 'user_alex',
    sla_policy_id: null,
    sla_first_response_deadline: '2026-04-18T08:25:00+00:00',
    sla_resolution_deadline: '2026-04-19T08:30:00+00:00',
    sla_status: 'at_risk',
    customer_id: 'cust_maya',
    order_ids: ['order_011'],
    payment_ids: ['pay_011'],
    return_ids: ['return_011'],
    conversation_id: 'conv_005',
    ai_diagnosis: 'Recurring VIP customer requesting another courtesy replacement and credit after multiple earlier exceptions.',
    ai_root_cause: 'Repeat goodwill threshold exceeded; human manager required before any credit is issued.',
    ai_confidence: 0.98,
    ai_recommended_action: 'Escalate to a manager, confirm the replacement path, and do not auto-commit the goodwill credit.',
    ai_evidence_refs: ['msg_005_3', 'peval_006', 'apr_006', 'ckl_006_1'],
    approval_state: 'pending',
    active_approval_request_id: 'apr_006',
    execution_state: 'waiting_approval',
    active_execution_plan_id: 'plan_006',
    resolution_state: 'unresolved',
    resolved_by: null,
    resolution_notes: null,
    resolution_at: null,
    has_reconciliation_conflicts: 1,
    conflict_severity: 'high',
    tags: ['vip', 'repeat_customer', 'goodwill_credit', 'human_approval'],
    created_at: now.current,
    updated_at: now.approval,
    first_response_at: now.msg2,
    last_activity_at: now.approval,
    closed_at: null,
  };

  await upsertRows('cases', [caseRow]);

  await upsertRows('case_status_history', [
    { id: 'csh_005_1', case_id: 'case_005', from_status: null, to_status: 'open', changed_by: 'shopify', changed_by_type: 'system', reason: 'Shopify order and WhatsApp thread entered the inbox', created_at: '2026-04-18T08:12:00+00:00', tenant_id: tenantId },
    { id: 'csh_005_2', case_id: 'case_005', from_status: 'open', to_status: 'investigating', changed_by: 'agent_channel_ingest', changed_by_type: 'agent', reason: 'Inbound customer message matched the existing customer record and historical orders', created_at: '2026-04-18T08:22:00+00:00', tenant_id: tenantId },
    { id: 'csh_005_3', case_id: 'case_005', from_status: 'investigating', to_status: 'approval_pending', changed_by: 'agent_qa_policy_check', changed_by_type: 'agent', reason: 'Repeat goodwill policy requires manager approval before any credit or replacement promise', created_at: now.approval, tenant_id: tenantId },
  ]);

  await upsertRows('execution_plans', [{
    id: 'plan_006',
    case_id: 'case_005',
    tenant_id: tenantId,
    generated_by: 'copilot',
    generated_at: now.approval,
    status: 'awaiting_approval',
    steps: [
      { step: 'confirm_history', action: 'Summarize prior goodwill exceptions and current evidence' },
      { step: 'manager_decision', action: 'Wait for a human approval or rejection' },
      { step: 'post_decision', action: 'Either release the replacement and credit or send a rejection summary' },
    ],
    dry_run_result: { expected: 'human approval required', risk: 'high' },
    approval_request_id: 'apr_006',
    started_at: now.approval,
    completed_at: null,
  }]);

  await upsertRows('approval_requests', [{
    id: 'apr_006',
    case_id: 'case_005',
    tenant_id: tenantId,
    workspace_id: workspaceId,
    requested_by: 'agent_qa_policy_check',
    requested_by_type: 'agent',
    action_type: 'goodwill_credit_and_replacement',
    action_payload: { order_id: 'order_011', payment_id: 'pay_011', return_id: 'return_011', replacement: true, goodwill_credit_amount: 75, reason: 'repeat goodwill threshold exceeded', customer_history: { prior_goodwill_exceptions_120d: 2, prior_orders: 2 } },
    risk_level: 'high',
    policy_rule_id: 'pr_repeat_goodwill_approval',
    evidence_package: { summary: 'VIP customer already used two goodwill exceptions in the last 120 days.', customer_id: 'cust_maya', customer_name: 'Maya Ortega', order_id: 'order_011', message_ids: ['msg_005_1', 'msg_005_3'], knowledge_articles: ['ka_repeat_goodwill_policy', 'ka_manager_escalation_playbook'] },
    status: 'pending',
    assigned_to: 'user_alex',
    assigned_team_id: 'team_support',
    decision_by: null,
    decision_at: null,
    decision_note: null,
    expires_at: '2026-04-19T08:55:00+00:00',
    execution_plan_id: 'plan_006',
    created_at: now.approval,
    updated_at: now.approval,
  }]);

  await patch('execution_plans', { id: 'plan_006', tenant_id: tenantId }, { approval_request_id: 'apr_006' });
  await patch('cases', { id: 'case_005', tenant_id: tenantId, workspace_id: workspaceId }, {
    active_approval_request_id: 'apr_006',
    active_execution_plan_id: 'plan_006',
    approval_state: 'pending',
    execution_state: 'waiting_approval',
    ai_evidence_refs: ['msg_005_3', 'peval_006', 'apr_006', 'ckl_006_1'],
    updated_at: now.approval,
  });

  await upsertRows('policy_evaluations', [{
    id: 'peval_006',
    tenant_id: tenantId,
    workspace_id: workspaceId,
    entity_type: 'case',
    action_type: 'goodwill_credit_and_replacement',
    case_id: 'case_005',
    input_context: { customer: { id: 'cust_maya', segment: 'vip', prior_goodwill_exceptions_120d: 2 }, request: { goodwill_credit_amount: 75, type: 'replacement_and_credit' }, order: { id: 'order_011', total_amount: 189, status: 'delivered' } },
    evaluated_rules: [{ rule_id: 'pr_repeat_goodwill_approval', outcome: 'match', reason: 'Two prior goodwill exceptions and a new credit request above threshold.' }],
    matched_rule_id: 'pr_repeat_goodwill_approval',
    decision: 'requires_approval',
    requires_approval: 1,
    conflict_detected: 1,
    conflicting_rule_ids: [],
    reason: 'The case crosses the repeat-exception threshold and must be reviewed by a human manager.',
    created_at: now.approval,
  }]);

  await upsertRows('reconciliation_issues', [{
    id: 'ri_006',
    case_id: 'case_005',
    tenant_id: tenantId,
    workspace_id: workspaceId,
    entity_type: 'case',
    entity_id: 'case_005',
    conflict_domain: 'policy',
    severity: 'high',
    status: 'open',
    conflicting_systems: ['shopify', 'stripe', 'wms', 'policy_engine'],
    expected_state: 'A single goodwill exception or no credit until manager review',
    actual_states: { shopify: 'delivered', stripe: 'captured', wms: 'received', customer_history: 'two prior goodwill exceptions', policy: 'requires human approval' },
    source_of_truth_system: 'policy_engine',
    resolution_plan: 'Wait for manager approval before issuing replacement or goodwill credit.',
    detected_at: now.approval,
    resolved_at: null,
    detected_by: 'agent_qa_policy_check',
  }]);

  await upsertRows('draft_replies', [{
    id: 'dr_005',
    case_id: 'case_005',
    conversation_id: 'conv_005',
    content: 'Thanks for your patience, Maya. I have checked the order history and the policy, and this one needs a manager review before we promise a courtesy credit. I will keep the case moving and update you as soon as the approval is confirmed.',
    generated_by: 'agent_copilot',
    generated_at: now.draft,
    tone: 'empathetic',
    confidence: 0.86,
    has_policies: 1,
    citations: ['ka_repeat_goodwill_policy', 'ka_manager_escalation_playbook'],
    status: 'pending_review',
    reviewed_by: null,
    reviewed_at: null,
    sent_at: null,
    updated_at: now.draft,
    tenant_id: tenantId,
    workspace_id: workspaceId,
  }]);

  await upsertRows('internal_notes', [{
    id: 'note_005',
    case_id: 'case_005',
    content: 'Maya has already had two goodwill exceptions in the last 120 days. Do not auto-approve any replacement or credit. Let the manager decide, then send the drafted reply.',
    created_by: 'agent_qa_policy_check',
    created_by_type: 'agent',
    created_at: '2026-04-18T08:57:00+00:00',
    tenant_id: tenantId,
    workspace_id: workspaceId,
  }]);

  await upsertRows('order_events', [
    { id: 'oe_009_1', order_id: 'order_009', type: 'order_placed', content: 'Order ORD-55199 placed by Maya Ortega', system: 'Shopify', time: '2026-03-16T11:30:00+00:00', tenant_id: tenantId },
    { id: 'oe_009_2', order_id: 'order_009', type: 'payment_captured', content: 'Payment captured successfully', system: 'Stripe', time: '2026-03-16T11:30:20+00:00', tenant_id: tenantId },
    { id: 'oe_009_3', order_id: 'order_009', type: 'delivered', content: 'Carrier confirmed delivery at the customer address', system: 'Carrier', time: '2026-03-18T09:20:00+00:00', tenant_id: tenantId },
    { id: 'oe_009_4', order_id: 'order_009', type: 'refund_closed', content: 'Courtesy refund completed and case closed', system: 'OMS', time: '2026-03-19T10:15:00+00:00', tenant_id: tenantId },
    { id: 'oe_010_1', order_id: 'order_010', type: 'order_placed', content: 'Order ORD-55207 placed by Maya Ortega', system: 'Shopify', time: '2026-04-02T11:40:00+00:00', tenant_id: tenantId },
    { id: 'oe_010_2', order_id: 'order_010', type: 'payment_captured', content: 'Payment captured successfully', system: 'Stripe', time: '2026-04-02T11:40:20+00:00', tenant_id: tenantId },
    { id: 'oe_010_3', order_id: 'order_010', type: 'delivered', content: 'Carrier confirmed delivery at the customer address', system: 'Carrier', time: '2026-04-04T08:20:00+00:00', tenant_id: tenantId },
    { id: 'oe_010_4', order_id: 'order_010', type: 'refund_closed', content: 'Courtesy refund completed and case closed', system: 'OMS', time: '2026-04-04T10:05:00+00:00', tenant_id: tenantId },
    { id: 'oe_011_1', order_id: 'order_011', type: 'order_placed', content: 'Order ORD-55223 placed by Maya Ortega', system: 'Shopify', time: '2026-04-18T08:08:00+00:00', tenant_id: tenantId },
    { id: 'oe_011_2', order_id: 'order_011', type: 'payment_captured', content: 'Payment captured successfully', system: 'Stripe', time: '2026-04-18T08:09:35+00:00', tenant_id: tenantId },
    { id: 'oe_011_3', order_id: 'order_011', type: 'delivered', content: 'Carrier confirmed delivery at the customer address', system: 'Carrier', time: '2026-04-18T08:13:00+00:00', tenant_id: tenantId },
    { id: 'oe_011_4', order_id: 'order_011', type: 'return_requested', content: 'Customer requested a replacement through support', system: 'Intercom', time: '2026-04-18T08:18:00+00:00', tenant_id: tenantId },
    { id: 'oe_011_5', order_id: 'order_011', type: 'policy_hold', content: 'Policy engine held the courtesy credit for manager approval', system: 'System', time: now.approval, tenant_id: tenantId },
    { id: 'oe_011_6', order_id: 'order_011', type: 'draft_reply_prepared', content: 'Copilot prepared a customer reply pending manager review', system: 'Copilot', time: now.draft, tenant_id: tenantId },
  ]);

  await upsertRows('payment_events', [
    { id: 'pe_009_1', payment_id: 'pay_009', type: 'authorized', content: 'Payment authorized — $129.00', system: 'Stripe', time: '2026-03-16T11:30:10+00:00', tenant_id: tenantId },
    { id: 'pe_009_2', payment_id: 'pay_009', type: 'captured', content: 'Payment captured successfully', system: 'Stripe', time: '2026-03-16T11:30:20+00:00', tenant_id: tenantId },
    { id: 'pe_009_3', payment_id: 'pay_009', type: 'refund_succeeded', content: 'Courtesy refund of $20 succeeded', system: 'Stripe', time: '2026-03-19T10:15:00+00:00', tenant_id: tenantId },
    { id: 'pe_010_1', payment_id: 'pay_010', type: 'authorized', content: 'Payment authorized — $84.00', system: 'Stripe', time: '2026-04-02T11:40:10+00:00', tenant_id: tenantId },
    { id: 'pe_010_2', payment_id: 'pay_010', type: 'captured', content: 'Payment captured successfully', system: 'Stripe', time: '2026-04-02T11:40:20+00:00', tenant_id: tenantId },
    { id: 'pe_010_3', payment_id: 'pay_010', type: 'refund_succeeded', content: 'Courtesy refund of $15 succeeded', system: 'Stripe', time: '2026-04-04T10:05:00+00:00', tenant_id: tenantId },
    { id: 'pe_011_1', payment_id: 'pay_011', type: 'authorized', content: 'Payment authorized — $189.00', system: 'Stripe', time: '2026-04-18T08:09:10+00:00', tenant_id: tenantId },
    { id: 'pe_011_2', payment_id: 'pay_011', type: 'captured', content: 'Payment captured successfully', system: 'Stripe', time: '2026-04-18T08:09:35+00:00', tenant_id: tenantId },
    { id: 'pe_011_3', payment_id: 'pay_011', type: 'refund_requested', content: 'Goodwill credit requested, awaiting manager approval', system: 'System', time: now.approval, tenant_id: tenantId },
    { id: 'pe_011_4', payment_id: 'pay_011', type: 'refund_pending', content: 'Refund remains pending until approval is granted', system: 'System', time: '2026-04-18T08:56:00+00:00', tenant_id: tenantId },
  ]);

  await upsertRows('return_events', [
    { id: 're_009_1', return_id: 'return_009', type: 'received', content: 'Warehouse received the returned item', system: 'WMS', time: '2026-03-18T09:30:00+00:00', tenant_id: tenantId },
    { id: 're_009_2', return_id: 'return_009', type: 'inspected', content: 'Inspection completed with no blockers', system: 'WMS', time: '2026-03-19T09:00:00+00:00', tenant_id: tenantId },
    { id: 're_009_3', return_id: 'return_009', type: 'refund_succeeded', content: 'Refund settled and case closed', system: 'Stripe', time: '2026-03-19T10:15:00+00:00', tenant_id: tenantId },
    { id: 're_010_1', return_id: 'return_010', type: 'received', content: 'Warehouse received the returned item', system: 'WMS', time: '2026-04-04T08:35:00+00:00', tenant_id: tenantId },
    { id: 're_010_2', return_id: 'return_010', type: 'inspected', content: 'Inspection completed with no blockers', system: 'WMS', time: '2026-04-04T09:50:00+00:00', tenant_id: tenantId },
    { id: 're_010_3', return_id: 'return_010', type: 'refund_succeeded', content: 'Refund settled and case closed', system: 'Stripe', time: '2026-04-04T10:05:00+00:00', tenant_id: tenantId },
    { id: 're_011_1', return_id: 'return_011', type: 'created', content: 'Replacement return created in the support flow', system: 'Intercom', time: '2026-04-18T08:18:00+00:00', tenant_id: tenantId },
    { id: 're_011_2', return_id: 'return_011', type: 'received', content: 'Warehouse marked the item as received', system: 'WMS', time: '2026-04-18T08:25:00+00:00', tenant_id: tenantId },
    { id: 're_011_3', return_id: 'return_011', type: 'policy_hold', content: 'Courtesy credit paused until manager review completes', system: 'System', time: now.approval, tenant_id: tenantId },
  ]);

  await upsertRows('order_events', [
    { id: 'oe_009_1', order_id: 'order_009', type: 'order_placed', content: 'Order ORD-55199 placed by Maya Ortega', system: 'Shopify', time: '2026-03-16T11:30:00+00:00', tenant_id: tenantId },
    { id: 'oe_009_2', order_id: 'order_009', type: 'payment_captured', content: 'Payment captured successfully', system: 'Stripe', time: '2026-03-16T11:30:20+00:00', tenant_id: tenantId },
    { id: 'oe_009_3', order_id: 'order_009', type: 'delivered', content: 'Carrier confirmed delivery at the customer address', system: 'Carrier', time: '2026-03-18T09:20:00+00:00', tenant_id: tenantId },
    { id: 'oe_009_4', order_id: 'order_009', type: 'refund_closed', content: 'Courtesy refund completed and case closed', system: 'OMS', time: '2026-03-19T10:15:00+00:00', tenant_id: tenantId },
    { id: 'oe_010_1', order_id: 'order_010', type: 'order_placed', content: 'Order ORD-55207 placed by Maya Ortega', system: 'Shopify', time: '2026-04-02T11:40:00+00:00', tenant_id: tenantId },
    { id: 'oe_010_2', order_id: 'order_010', type: 'payment_captured', content: 'Payment captured successfully', system: 'Stripe', time: '2026-04-02T11:40:20+00:00', tenant_id: tenantId },
    { id: 'oe_010_3', order_id: 'order_010', type: 'delivered', content: 'Carrier confirmed delivery at the customer address', system: 'Carrier', time: '2026-04-04T08:20:00+00:00', tenant_id: tenantId },
    { id: 'oe_010_4', order_id: 'order_010', type: 'refund_closed', content: 'Courtesy refund completed and case closed', system: 'OMS', time: '2026-04-04T10:05:00+00:00', tenant_id: tenantId },
    { id: 'oe_011_1', order_id: 'order_011', type: 'order_placed', content: 'Order ORD-55223 placed by Maya Ortega', system: 'Shopify', time: '2026-04-18T08:08:00+00:00', tenant_id: tenantId },
    { id: 'oe_011_2', order_id: 'order_011', type: 'payment_captured', content: 'Payment captured successfully', system: 'Stripe', time: '2026-04-18T08:09:35+00:00', tenant_id: tenantId },
    { id: 'oe_011_3', order_id: 'order_011', type: 'delivered', content: 'Carrier confirmed delivery at the customer address', system: 'Carrier', time: '2026-04-18T08:13:00+00:00', tenant_id: tenantId },
    { id: 'oe_011_4', order_id: 'order_011', type: 'return_requested', content: 'Customer requested a replacement through support', system: 'Intercom', time: '2026-04-18T08:18:00+00:00', tenant_id: tenantId },
    { id: 'oe_011_5', order_id: 'order_011', type: 'policy_hold', content: 'Policy engine held the courtesy credit for manager approval', system: 'System', time: now.approval, tenant_id: tenantId },
    { id: 'oe_011_6', order_id: 'order_011', type: 'draft_reply_prepared', content: 'Copilot prepared a customer reply pending manager review', system: 'Copilot', time: now.draft, tenant_id: tenantId },
  ]);

  await upsertRows('payment_events', [
    { id: 'pe_009_1', payment_id: 'pay_009', type: 'authorized', content: 'Payment authorized — $129.00', system: 'Stripe', time: '2026-03-16T11:30:10+00:00', tenant_id: tenantId },
    { id: 'pe_009_2', payment_id: 'pay_009', type: 'captured', content: 'Payment captured successfully', system: 'Stripe', time: '2026-03-16T11:30:20+00:00', tenant_id: tenantId },
    { id: 'pe_009_3', payment_id: 'pay_009', type: 'refund_succeeded', content: 'Courtesy refund of $20 succeeded', system: 'Stripe', time: '2026-03-19T10:15:00+00:00', tenant_id: tenantId },
    { id: 'pe_010_1', payment_id: 'pay_010', type: 'authorized', content: 'Payment authorized — $84.00', system: 'Stripe', time: '2026-04-02T11:40:10+00:00', tenant_id: tenantId },
    { id: 'pe_010_2', payment_id: 'pay_010', type: 'captured', content: 'Payment captured successfully', system: 'Stripe', time: '2026-04-02T11:40:20+00:00', tenant_id: tenantId },
    { id: 'pe_010_3', payment_id: 'pay_010', type: 'refund_succeeded', content: 'Courtesy refund of $15 succeeded', system: 'Stripe', time: '2026-04-04T10:05:00+00:00', tenant_id: tenantId },
    { id: 'pe_011_1', payment_id: 'pay_011', type: 'authorized', content: 'Payment authorized — $189.00', system: 'Stripe', time: '2026-04-18T08:09:10+00:00', tenant_id: tenantId },
    { id: 'pe_011_2', payment_id: 'pay_011', type: 'captured', content: 'Payment captured successfully', system: 'Stripe', time: '2026-04-18T08:09:35+00:00', tenant_id: tenantId },
    { id: 'pe_011_3', payment_id: 'pay_011', type: 'refund_requested', content: 'Goodwill credit requested, awaiting manager approval', system: 'System', time: now.approval, tenant_id: tenantId },
    { id: 'pe_011_4', payment_id: 'pay_011', type: 'refund_pending', content: 'Refund remains pending until approval is granted', system: 'System', time: '2026-04-18T08:56:00+00:00', tenant_id: tenantId },
  ]);

  await upsertRows('return_events', [
    { id: 're_009_1', return_id: 'return_009', type: 'received', content: 'Warehouse received the returned item', system: 'WMS', time: '2026-03-18T09:30:00+00:00', tenant_id: tenantId },
    { id: 're_009_2', return_id: 'return_009', type: 'inspected', content: 'Inspection completed with no blockers', system: 'WMS', time: '2026-03-19T09:00:00+00:00', tenant_id: tenantId },
    { id: 're_009_3', return_id: 'return_009', type: 'refund_succeeded', content: 'Refund settled and case closed', system: 'Stripe', time: '2026-03-19T10:15:00+00:00', tenant_id: tenantId },
    { id: 're_010_1', return_id: 'return_010', type: 'received', content: 'Warehouse received the returned item', system: 'WMS', time: '2026-04-04T08:35:00+00:00', tenant_id: tenantId },
    { id: 're_010_2', return_id: 'return_010', type: 'inspected', content: 'Inspection completed with no blockers', system: 'WMS', time: '2026-04-04T09:50:00+00:00', tenant_id: tenantId },
    { id: 're_010_3', return_id: 'return_010', type: 'refund_succeeded', content: 'Refund settled and case closed', system: 'Stripe', time: '2026-04-04T10:05:00+00:00', tenant_id: tenantId },
    { id: 're_011_1', return_id: 'return_011', type: 'created', content: 'Replacement return created in the support flow', system: 'Intercom', time: '2026-04-18T08:18:00+00:00', tenant_id: tenantId },
    { id: 're_011_2', return_id: 'return_011', type: 'received', content: 'Warehouse marked the item as received', system: 'WMS', time: '2026-04-18T08:25:00+00:00', tenant_id: tenantId },
    { id: 're_011_3', return_id: 'return_011', type: 'policy_hold', content: 'Courtesy credit paused until manager review completes', system: 'System', time: now.approval, tenant_id: tenantId },
  ]);

  await upsertRows('refunds', [
    { id: 'refund_009', external_refund_id: 'rf_009', payment_id: 'pay_009', order_id: 'order_009', customer_id: 'cust_maya', tenant_id: tenantId, amount: 20, currency: 'USD', type: 'partial', status: 'settled', reason: 'Resolved replacement credit from the earlier case', initiated_by: 'copilot', initiated_by_type: 'agent', approval_request_id: null, idempotency_key: 'refund-pay-009', created_at: now.history1, updated_at: now.history1 },
    { id: 'refund_010', external_refund_id: 'rf_010', payment_id: 'pay_010', order_id: 'order_010', customer_id: 'cust_maya', tenant_id: tenantId, amount: 15, currency: 'USD', type: 'partial', status: 'settled', reason: 'Courtesy delay credit', initiated_by: 'copilot', initiated_by_type: 'agent', approval_request_id: null, idempotency_key: 'refund-pay-010', created_at: now.history2, updated_at: now.history2 },
    { id: 'refund_011', external_refund_id: 'rf_011', payment_id: 'pay_011', order_id: 'order_011', customer_id: 'cust_maya', tenant_id: tenantId, amount: 75, currency: 'USD', type: 'partial', status: 'pending', reason: 'Goodwill credit awaiting manager approval', initiated_by: 'agent_qa_policy_check', initiated_by_type: 'agent', approval_request_id: 'apr_006', idempotency_key: 'refund-pay-011', created_at: now.approval, updated_at: now.approval },
  ]);

  await upsertRows('execution_plans', [{
    id: 'plan_006',
    case_id: 'case_005',
    tenant_id: tenantId,
    generated_by: 'copilot',
    generated_at: now.approval,
    status: 'awaiting_approval',
    steps: [
      { step: 'confirm_history', action: 'Summarize prior goodwill exceptions and current evidence' },
      { step: 'manager_decision', action: 'Wait for a human approval or rejection' },
      { step: 'post_decision', action: 'Either release the replacement and credit or send a rejection summary' },
    ],
    dry_run_result: { expected: 'human approval required', risk: 'high' },
    approval_request_id: 'apr_006',
    started_at: now.approval,
    completed_at: null,
  }]);

  await upsertRows('approval_requests', [{
    id: 'apr_006',
    case_id: 'case_005',
    tenant_id: tenantId,
    workspace_id: workspaceId,
    requested_by: 'agent_qa_policy_check',
    requested_by_type: 'agent',
    action_type: 'goodwill_credit_and_replacement',
    action_payload: { order_id: 'order_011', payment_id: 'pay_011', return_id: 'return_011', replacement: true, goodwill_credit_amount: 75, reason: 'repeat goodwill threshold exceeded', customer_history: { prior_goodwill_exceptions_120d: 2, prior_orders: 2 } },
    risk_level: 'high',
    policy_rule_id: 'pr_repeat_goodwill_approval',
    evidence_package: { summary: 'VIP customer already used two goodwill exceptions in the last 120 days.', customer_id: 'cust_maya', customer_name: 'Maya Ortega', order_id: 'order_011', message_ids: ['msg_005_1', 'msg_005_3'], knowledge_articles: ['ka_repeat_goodwill_policy', 'ka_manager_escalation_playbook'] },
    status: 'pending',
    assigned_to: 'user_alex',
    assigned_team_id: 'team_support',
    decision_by: null,
    decision_at: null,
    decision_note: null,
    expires_at: '2026-04-19T08:55:00+00:00',
    execution_plan_id: 'plan_006',
    created_at: now.approval,
    updated_at: now.approval,
  }]);

  await patch('execution_plans', { id: 'plan_006', tenant_id: tenantId }, { approval_request_id: 'apr_006' });
  await patch('cases', { id: 'case_005', tenant_id: tenantId, workspace_id: workspaceId }, {
    active_approval_request_id: 'apr_006',
    active_execution_plan_id: 'plan_006',
    approval_state: 'pending',
    execution_state: 'waiting_approval',
    ai_evidence_refs: ['msg_005_3', 'peval_006', 'apr_006', 'ckl_006_1'],
    updated_at: now.approval,
  });

  await upsertRows('policy_evaluations', [{
    id: 'peval_006',
    tenant_id: tenantId,
    workspace_id: workspaceId,
    entity_type: 'case',
    action_type: 'goodwill_credit_and_replacement',
    case_id: 'case_005',
    input_context: { customer: { id: 'cust_maya', segment: 'vip', prior_goodwill_exceptions_120d: 2 }, request: { goodwill_credit_amount: 75, type: 'replacement_and_credit' }, order: { id: 'order_011', total_amount: 189, status: 'delivered' } },
    evaluated_rules: [{ rule_id: 'pr_repeat_goodwill_approval', outcome: 'match', reason: 'Two prior goodwill exceptions and a new credit request above threshold.' }],
    matched_rule_id: 'pr_repeat_goodwill_approval',
    decision: 'requires_approval',
    requires_approval: 1,
    conflict_detected: 1,
    conflicting_rule_ids: [],
    reason: 'The case crosses the repeat-exception threshold and must be reviewed by a human manager.',
    created_at: now.approval,
  }]);

  await upsertRows('reconciliation_issues', [{
    id: 'ri_006',
    case_id: 'case_005',
    tenant_id: tenantId,
    workspace_id: workspaceId,
    entity_type: 'case',
    entity_id: 'case_005',
    conflict_domain: 'policy',
    severity: 'high',
    status: 'open',
    conflicting_systems: ['shopify', 'stripe', 'wms', 'policy_engine'],
    expected_state: 'A single goodwill exception or no credit until manager review',
    actual_states: { shopify: 'delivered', stripe: 'captured', wms: 'received', customer_history: 'two prior goodwill exceptions', policy: 'requires human approval' },
    source_of_truth_system: 'policy_engine',
    resolution_plan: 'Wait for manager approval before issuing replacement or goodwill credit.',
    detected_at: now.approval,
    resolved_at: null,
    detected_by: 'agent_qa_policy_check',
  }]);

  await upsertRows('draft_replies', [{
    id: 'dr_005',
    case_id: 'case_005',
    conversation_id: 'conv_005',
    content: 'Thanks for your patience, Maya. I have checked the order history and the policy, and this one needs a manager review before we promise a courtesy credit. I will keep the case moving and update you as soon as the approval is confirmed.',
    generated_by: 'agent_copilot',
    generated_at: now.draft,
    tone: 'empathetic',
    confidence: 0.86,
    has_policies: 1,
    citations: ['ka_repeat_goodwill_policy', 'ka_manager_escalation_playbook'],
    status: 'pending_review',
    reviewed_by: null,
    reviewed_at: null,
    sent_at: null,
    updated_at: now.draft,
    tenant_id: tenantId,
    workspace_id: workspaceId,
  }]);

  await upsertRows('internal_notes', [{
    id: 'note_005',
    case_id: 'case_005',
    content: 'Maya has already had two goodwill exceptions in the last 120 days. Do not auto-approve any replacement or credit. Let the manager decide, then send the drafted reply.',
    created_by: 'agent_qa_policy_check',
    created_by_type: 'agent',
    created_at: '2026-04-18T08:57:00+00:00',
    tenant_id: tenantId,
    workspace_id: workspaceId,
  }]);

  await upsertRows('workflow_definitions', [{
    id: 'wfd_006',
    tenant_id: tenantId,
    workspace_id: workspaceId,
    name: 'Repeat goodwill escalation flow',
    description: 'A compact workflow that ingests the case, checks knowledge policy, and pauses for human approval when the customer already exhausted goodwill exceptions.',
    current_version_id: null,
    created_by: 'agent_copilot',
    created_at: now.current,
    updated_at: now.approval,
  }]);

  await upsertRows('workflow_versions', [{
    id: 'wfv_006_1',
    workflow_id: 'wfd_006',
    version_number: 1,
    status: 'published',
    nodes: [
      { id: 'ingest_case', type: 'task', label: 'Ingest case' },
      { id: 'load_history', type: 'task', label: 'Load customer history' },
      { id: 'retrieve_knowledge', type: 'task', label: 'Retrieve policy articles' },
      { id: 'policy_check', type: 'decision', label: 'Check goodwill threshold' },
      { id: 'human_review', type: 'approval', label: 'Manager approval' },
      { id: 'customer_update', type: 'task', label: 'Draft customer response' },
    ],
    edges: [
      { from: 'ingest_case', to: 'load_history' },
      { from: 'load_history', to: 'retrieve_knowledge' },
      { from: 'retrieve_knowledge', to: 'policy_check' },
      { from: 'policy_check', to: 'human_review', condition: 'requires_approval' },
      { from: 'human_review', to: 'customer_update', condition: 'approved' },
    ],
    trigger: { type: 'case_event', event: 'case_created', case_id: 'case_005' },
    published_by: 'user_alex',
    published_at: now.approval,
    tenant_id: tenantId,
  }]);

  await patch('workflow_definitions', { id: 'wfd_006', tenant_id: tenantId, workspace_id: workspaceId }, { current_version_id: 'wfv_006_1' });

  await upsertRows('workflow_runs', [{
    id: 'wfr_006',
    workflow_version_id: 'wfv_006_1',
    case_id: 'case_005',
    tenant_id: tenantId,
    trigger_type: 'case_event',
    trigger_payload: {
      case_id: 'case_005',
      customer_id: 'cust_maya',
      order_id: 'order_011',
      approval_request_id: 'apr_006',
      policy_rule_id: 'pr_repeat_goodwill_approval',
    },
    status: 'running',
    current_node_id: 'human_review',
    context: {
      customer_id: 'cust_maya',
      prior_goodwill_exceptions_120d: 2,
      knowledge_articles: ['ka_repeat_goodwill_policy', 'ka_manager_escalation_playbook'],
      approval_request_id: 'apr_006',
    },
    started_at: now.approval,
    ended_at: null,
    error: null,
  }]);

  await upsertRows('workflow_run_steps', [
    {
      id: 'wfrs_006_1',
      workflow_run_id: 'wfr_006',
      node_id: 'ingest_case',
      node_type: 'task',
      status: 'completed',
      input: { case_id: 'case_005' },
      output: { summary: 'Case ingested and scoped to Maya Ortega' },
      started_at: now.approval,
      ended_at: '2026-04-18T08:55:20+00:00',
      error: null,
    },
    {
      id: 'wfrs_006_2',
      workflow_run_id: 'wfr_006',
      node_id: 'load_history',
      node_type: 'task',
      status: 'completed',
      input: { customer_id: 'cust_maya' },
      output: { summary: 'Found two prior goodwill exceptions and three prior orders' },
      started_at: '2026-04-18T08:55:20+00:00',
      ended_at: '2026-04-18T08:55:36+00:00',
      error: null,
    },
    {
      id: 'wfrs_006_3',
      workflow_run_id: 'wfr_006',
      node_id: 'retrieve_knowledge',
      node_type: 'task',
      status: 'completed',
      input: { knowledge_articles: ['ka_repeat_goodwill_policy', 'ka_manager_escalation_playbook'] },
      output: { summary: 'Retrieved the two policy articles that govern repeat goodwill cases' },
      started_at: '2026-04-18T08:55:36+00:00',
      ended_at: '2026-04-18T08:55:48+00:00',
      error: null,
    },
    {
      id: 'wfrs_006_4',
      workflow_run_id: 'wfr_006',
      node_id: 'policy_check',
      node_type: 'decision',
      status: 'completed',
      input: { rule_id: 'pr_repeat_goodwill_approval', goodwill_credit_amount: 75 },
      output: { decision: 'requires_approval', reason: 'Threshold exceeded' },
      started_at: '2026-04-18T08:55:48+00:00',
      ended_at: '2026-04-18T08:56:00+00:00',
      error: null,
    },
    {
      id: 'wfrs_006_5',
      workflow_run_id: 'wfr_006',
      node_id: 'human_review',
      node_type: 'approval',
      status: 'running',
      input: { approval_request_id: 'apr_006' },
      output: { summary: 'Waiting for manager decision' },
      started_at: '2026-04-18T08:56:00+00:00',
      ended_at: null,
      error: null,
    },
  ]);

  await upsertRows('agents', [
    { id: 'agent_copilot', tenant_id: tenantId, name: 'Copilot', slug: 'copilot', category: 'orchestration', description: 'Primary support copilot for the demo tenant.', is_system: 1, is_locked: 0, is_active: 1, current_version_id: null, created_at: now.current, updated_at: now.approval },
    { id: 'agent_channel_ingest', tenant_id: tenantId, name: 'Channel Ingest', slug: 'channel-ingest', category: 'ingest', description: 'Ingests messages from web chat, email, and messaging channels.', is_system: 1, is_locked: 0, is_active: 1, current_version_id: null, created_at: now.current, updated_at: now.approval },
    { id: 'agent_canonicalizer', tenant_id: tenantId, name: 'Canonicalizer', slug: 'canonicalizer', category: 'ingest', description: 'Normalizes cross-system payloads into canonical state.', is_system: 1, is_locked: 0, is_active: 1, current_version_id: null, created_at: now.current, updated_at: now.approval },
    { id: 'agent_intent_router', tenant_id: tenantId, name: 'Intent Router', slug: 'intent-router', category: 'ingest', description: 'Routes inbound intent to the correct agent and case flow.', is_system: 1, is_locked: 0, is_active: 1, current_version_id: null, created_at: now.current, updated_at: now.approval },
    { id: 'agent_knowledge', tenant_id: tenantId, name: 'Knowledge Retriever', slug: 'knowledge-retriever', category: 'ingest', description: 'Retrieves policy articles and supporting evidence for cases.', is_system: 1, is_locked: 0, is_active: 1, current_version_id: null, created_at: now.current, updated_at: now.approval },
    { id: 'agent_qa_policy_check', tenant_id: tenantId, name: 'QA / Policy Check', slug: 'qa-policy-check', category: 'policy', description: 'Checks policies and quality thresholds before actions proceed.', is_system: 1, is_locked: 0, is_active: 1, current_version_id: null, created_at: now.current, updated_at: now.approval },
    { id: 'agent_approval_gatekeeper', tenant_id: tenantId, name: 'Approval Gatekeeper', slug: 'approval-gatekeeper', category: 'policy', description: 'Determines whether actions require manual review.', is_system: 1, is_locked: 0, is_active: 1, current_version_id: null, created_at: now.current, updated_at: now.approval },
    { id: 'agent_returns_specialist', tenant_id: tenantId, name: 'Returns Specialist', slug: 'returns-specialist', category: 'specialist', description: 'Handles return inspection, approval, and refund timing.', is_system: 0, is_locked: 0, is_active: 1, current_version_id: null, created_at: now.current, updated_at: now.approval },
  ]);

  await upsertRows('agent_runs', [
    {
      id: 'ar_007',
      case_id: 'case_005',
      tenant_id: tenantId,
      workspace_id: workspaceId,
      agent_id: 'agent_channel_ingest',
      agent_version_id: null,
      trigger_event: 'case_created',
      trigger_type: 'case_event',
      status: 'completed',
      outcome_status: 'completed',
      confidence: 0.97,
      summary: 'Channel ingest normalized the inbound conversation and created the case context',
      output: { summary: 'Inbound case normalized from Shopify and support events' },
      evidence_refs: ['ce_006_1', 'ce_006_2'],
      execution_decision: 'proceed',
      tokens_used: 1120,
      cost_credits: 0.24,
      error: null,
      error_message: null,
      started_at: '2026-04-18T08:52:00+00:00',
      ended_at: '2026-04-18T08:52:30+00:00',
      finished_at: '2026-04-18T08:52:30+00:00',
    },
    {
      id: 'ar_008',
      case_id: 'case_005',
      tenant_id: tenantId,
      workspace_id: workspaceId,
      agent_id: 'agent_canonicalizer',
      agent_version_id: null,
      trigger_event: 'case_created',
      trigger_type: 'case_event',
      status: 'completed',
      outcome_status: 'completed',
      confidence: 0.96,
      summary: 'Canonicalizer merged Shopify, Stripe, WMS, and support into one case timeline',
      output: { summary: 'Unified canonical state for order, payment, and return' },
      evidence_refs: ['ce_006_2', 'ce_006_3', 'ce_006_4'],
      execution_decision: 'proceed',
      tokens_used: 1410,
      cost_credits: 0.31,
      error: null,
      error_message: null,
      started_at: '2026-04-18T08:52:30+00:00',
      ended_at: '2026-04-18T08:53:05+00:00',
      finished_at: '2026-04-18T08:53:05+00:00',
    },
    {
      id: 'ar_009',
      case_id: 'case_005',
      tenant_id: tenantId,
      workspace_id: workspaceId,
      agent_id: 'agent_intent_router',
      agent_version_id: null,
      trigger_event: 'case_created',
      trigger_type: 'case_event',
      status: 'completed',
      outcome_status: 'completed',
      confidence: 0.95,
      summary: 'Intent router classified the request as repeat goodwill escalation',
      output: { summary: 'Routed to policy, knowledge, and approval flow' },
      evidence_refs: ['msg_005_1', 'msg_005_3'],
      execution_decision: 'proceed',
      tokens_used: 860,
      cost_credits: 0.18,
      error: null,
      error_message: null,
      started_at: '2026-04-18T08:53:05+00:00',
      ended_at: '2026-04-18T08:53:30+00:00',
      finished_at: '2026-04-18T08:53:30+00:00',
    },
    {
      id: 'ar_010',
      case_id: 'case_005',
      tenant_id: tenantId,
      workspace_id: workspaceId,
      agent_id: 'agent_knowledge',
      agent_version_id: null,
      trigger_event: 'policy_check',
      trigger_type: 'case_event',
      status: 'completed',
      outcome_status: 'completed',
      confidence: 0.98,
      summary: 'Knowledge retriever surfaced the two strict policy articles needed for the case',
      output: { summary: 'Policy articles found and linked to the case' },
      evidence_refs: ['ka_repeat_goodwill_policy', 'ka_manager_escalation_playbook'],
      execution_decision: 'proceed',
      tokens_used: 640,
      cost_credits: 0.12,
      error: null,
      error_message: null,
      started_at: '2026-04-18T08:53:30+00:00',
      ended_at: '2026-04-18T08:53:50+00:00',
      finished_at: '2026-04-18T08:53:50+00:00',
    },
    {
      id: 'ar_011',
      case_id: 'case_005',
      tenant_id: tenantId,
      workspace_id: workspaceId,
      agent_id: 'agent_qa_policy_check',
      agent_version_id: null,
      trigger_event: 'policy_check',
      trigger_type: 'case_event',
      status: 'completed',
      outcome_status: 'completed',
      confidence: 0.99,
      summary: 'Policy check detected the repeat goodwill threshold and escalated the case',
      output: { summary: 'Approval required before any replacement or credit is sent' },
      evidence_refs: ['pr_repeat_goodwill_approval', 'ka_repeat_goodwill_policy'],
      execution_decision: 'hold',
      tokens_used: 980,
      cost_credits: 0.21,
      error: null,
      error_message: null,
      started_at: '2026-04-18T08:54:00+00:00',
      ended_at: '2026-04-18T08:54:25+00:00',
      finished_at: '2026-04-18T08:54:25+00:00',
    },
    {
      id: 'ar_012',
      case_id: 'case_005',
      tenant_id: tenantId,
      workspace_id: workspaceId,
      agent_id: 'agent_approval_gatekeeper',
      agent_version_id: null,
      trigger_event: 'approval_requested',
      trigger_type: 'approval_event',
      status: 'running',
      outcome_status: 'running',
      confidence: 0.94,
      summary: 'Approval gatekeeper is waiting for the manager decision on the goodwill exception',
      output: { summary: 'Approval request pending in inbox' },
      evidence_refs: ['apr_006', 'peval_006'],
      execution_decision: 'pause',
      tokens_used: 720,
      cost_credits: 0.16,
      error: null,
      error_message: null,
      started_at: '2026-04-18T08:54:30+00:00',
      ended_at: null,
      finished_at: null,
    },
    {
      id: 'ar_013',
      case_id: 'case_005',
      tenant_id: tenantId,
      workspace_id: workspaceId,
      agent_id: 'agent_returns_specialist',
      agent_version_id: null,
      trigger_event: 'return_registered',
      trigger_type: 'case_event',
      status: 'completed',
      outcome_status: 'completed',
      confidence: 0.93,
      summary: 'Returns specialist confirmed the return is valid but must wait for policy approval',
      output: { summary: 'Return qualifies, replacement remains blocked until human review' },
      evidence_refs: ['return_011', 'ka_repeat_goodwill_policy'],
      execution_decision: 'hold',
      tokens_used: 1040,
      cost_credits: 0.23,
      error: null,
      error_message: null,
      started_at: '2026-04-18T08:54:35+00:00',
      ended_at: '2026-04-18T08:54:55+00:00',
      finished_at: '2026-04-18T08:54:55+00:00',
    },
    {
      id: 'ar_014',
      case_id: 'case_005',
      tenant_id: tenantId,
      workspace_id: workspaceId,
      agent_id: 'agent_copilot',
      agent_version_id: null,
      trigger_event: 'reply_requested',
      trigger_type: 'case_event',
      status: 'completed',
      outcome_status: 'completed',
      confidence: 0.98,
      summary: 'Copilot drafted the customer update and manager-facing summary',
      output: { summary: 'Drafted response explains the approval wait and next step' },
      evidence_refs: ['dr_005', 'note_005'],
      execution_decision: 'proceed',
      tokens_used: 1580,
      cost_credits: 0.39,
      error: null,
      error_message: null,
      started_at: '2026-04-18T08:55:50+00:00',
      ended_at: '2026-04-18T08:56:20+00:00',
      finished_at: '2026-04-18T08:56:20+00:00',
    },
  ]);

  await upsertRows('webhook_events', [
    {
      id: 'wh_006_1',
      connector_id: null,
      tenant_id: tenantId,
      source_system: 'shopify',
      event_type: 'orders/create',
      raw_payload: { order_id: 'ORD-55223', customer_email: 'maya.ortega@example.com', tags: ['vip', 'repeat-customer'] },
      received_at: '2026-04-18T08:51:40+00:00',
      processed_at: '2026-04-18T08:51:55+00:00',
      status: 'processed',
      canonical_event_id: 'ce_006_1',
      dedupe_key: 'shopify:orders/create:ORD-55223',
    },
    {
      id: 'wh_006_2',
      connector_id: null,
      tenant_id: tenantId,
      source_system: 'stripe',
      event_type: 'payment_intent.succeeded',
      raw_payload: { payment_id: 'pay_011', amount: 189, currency: 'USD' },
      received_at: '2026-04-18T08:52:05+00:00',
      processed_at: '2026-04-18T08:52:20+00:00',
      status: 'processed',
      canonical_event_id: 'ce_006_2',
      dedupe_key: 'stripe:payment_intent.succeeded:pay_011',
    },
    {
      id: 'wh_006_3',
      connector_id: null,
      tenant_id: tenantId,
      source_system: 'wms',
      event_type: 'return.received',
      raw_payload: { return_id: 'return_011', condition: 'opened_and_used' },
      received_at: '2026-04-18T08:52:30+00:00',
      processed_at: '2026-04-18T08:52:38+00:00',
      status: 'processed',
      canonical_event_id: 'ce_006_3',
      dedupe_key: 'wms:return.received:return_011',
    },
    {
      id: 'wh_006_4',
      connector_id: null,
      tenant_id: tenantId,
      source_system: 'intercom',
      event_type: 'message.created',
      raw_payload: { conversation_id: 'conv_005', sender: 'maya.ortega@example.com' },
      received_at: '2026-04-18T08:53:00+00:00',
      processed_at: '2026-04-18T08:53:10+00:00',
      status: 'processed',
      canonical_event_id: 'ce_006_4',
      dedupe_key: 'intercom:message.created:conv_005:1',
    },
    {
      id: 'wh_006_5',
      connector_id: null,
      tenant_id: tenantId,
      source_system: 'policy-engine',
      event_type: 'policy.violation',
      raw_payload: { rule_id: 'pr_repeat_goodwill_approval', outcome: 'requires_approval' },
      received_at: '2026-04-18T08:54:10+00:00',
      processed_at: '2026-04-18T08:54:18+00:00',
      status: 'processed',
      canonical_event_id: 'ce_006_5',
      dedupe_key: 'policy-engine:policy.violation:case_005',
    },
    {
      id: 'wh_006_6',
      connector_id: null,
      tenant_id: tenantId,
      source_system: 'support',
      event_type: 'approval.requested',
      raw_payload: { approval_request_id: 'apr_006', case_id: 'case_005' },
      received_at: '2026-04-18T08:54:35+00:00',
      processed_at: '2026-04-18T08:54:40+00:00',
      status: 'processed',
      canonical_event_id: 'ce_006_6',
      dedupe_key: 'support:approval.requested:apr_006',
    },
  ]);

  await upsertRows('canonical_events', [
    {
      id: 'ce_006_1',
      dedupe_key: 'shopify:orders/create:ORD-55223',
      tenant_id: tenantId,
      workspace_id: workspaceId,
      source_system: 'shopify',
      source_entity_type: 'order',
      source_entity_id: 'ORD-55223',
      event_type: 'order_created',
      event_category: 'inbox',
      occurred_at: '2026-04-18T08:51:40+00:00',
      ingested_at: '2026-04-18T08:51:55+00:00',
      processed_at: '2026-04-18T08:51:55+00:00',
      canonical_entity_type: 'order',
      canonical_entity_id: 'order_011',
      correlation_id: 'case_005',
      case_id: 'case_005',
      normalized_payload: { order_id: 'order_011', customer_id: 'cust_maya', status: 'open' },
      confidence: 0.99,
      mapping_version: '1.0',
      status: 'processed',
      updated_at: '2026-04-18T08:51:55+00:00',
    },
    {
      id: 'ce_006_2',
      dedupe_key: 'stripe:payment_intent.succeeded:pay_011',
      tenant_id: tenantId,
      workspace_id: workspaceId,
      source_system: 'stripe',
      source_entity_type: 'payment',
      source_entity_id: 'pay_011',
      event_type: 'payment_captured',
      event_category: 'payments',
      occurred_at: '2026-04-18T08:52:05+00:00',
      ingested_at: '2026-04-18T08:52:20+00:00',
      processed_at: '2026-04-18T08:52:20+00:00',
      canonical_entity_type: 'payment',
      canonical_entity_id: 'pay_011',
      correlation_id: 'case_005',
      case_id: 'case_005',
      normalized_payload: { payment_id: 'pay_011', amount: 189, status: 'captured' },
      confidence: 0.99,
      mapping_version: '1.0',
      status: 'processed',
      updated_at: '2026-04-18T08:52:20+00:00',
    },
    {
      id: 'ce_006_3',
      dedupe_key: 'wms:return.received:return_011',
      tenant_id: tenantId,
      workspace_id: workspaceId,
      source_system: 'wms',
      source_entity_type: 'return',
      source_entity_id: 'return_011',
      event_type: 'return_received',
      event_category: 'returns',
      occurred_at: '2026-04-18T08:52:30+00:00',
      ingested_at: '2026-04-18T08:52:38+00:00',
      processed_at: '2026-04-18T08:52:38+00:00',
      canonical_entity_type: 'return',
      canonical_entity_id: 'return_011',
      correlation_id: 'case_005',
      case_id: 'case_005',
      normalized_payload: { return_id: 'return_011', inspection_status: 'pending_review' },
      confidence: 0.98,
      mapping_version: '1.0',
      status: 'processed',
      updated_at: '2026-04-18T08:52:38+00:00',
    },
    {
      id: 'ce_006_4',
      dedupe_key: 'intercom:message.created:conv_005:1',
      tenant_id: tenantId,
      workspace_id: workspaceId,
      source_system: 'intercom',
      source_entity_type: 'message',
      source_entity_id: 'msg_005_1',
      event_type: 'message_received',
      event_category: 'inbox',
      occurred_at: '2026-04-18T08:53:00+00:00',
      ingested_at: '2026-04-18T08:53:10+00:00',
      processed_at: '2026-04-18T08:53:10+00:00',
      canonical_entity_type: 'conversation',
      canonical_entity_id: 'conv_005',
      correlation_id: 'case_005',
      case_id: 'case_005',
      normalized_payload: { conversation_id: 'conv_005', message_id: 'msg_005_1' },
      confidence: 0.97,
      mapping_version: '1.0',
      status: 'processed',
      updated_at: '2026-04-18T08:53:10+00:00',
    },
    {
      id: 'ce_006_5',
      dedupe_key: 'policy-engine:policy.violation:case_005',
      tenant_id: tenantId,
      workspace_id: workspaceId,
      source_system: 'policy-engine',
      source_entity_type: 'case',
      source_entity_id: 'case_005',
      event_type: 'policy_violation_detected',
      event_category: 'approvals',
      occurred_at: '2026-04-18T08:54:10+00:00',
      ingested_at: '2026-04-18T08:54:18+00:00',
      processed_at: '2026-04-18T08:54:18+00:00',
      canonical_entity_type: 'case',
      canonical_entity_id: 'case_005',
      correlation_id: 'case_005',
      case_id: 'case_005',
      normalized_payload: { rule_id: 'pr_repeat_goodwill_approval', decision: 'requires_approval' },
      confidence: 1,
      mapping_version: '1.0',
      status: 'processed',
      updated_at: '2026-04-18T08:54:18+00:00',
    },
    {
      id: 'ce_006_6',
      dedupe_key: 'support:approval.requested:apr_006',
      tenant_id: tenantId,
      workspace_id: workspaceId,
      source_system: 'support',
      source_entity_type: 'approval_request',
      source_entity_id: 'apr_006',
      event_type: 'approval_requested',
      event_category: 'approvals',
      occurred_at: '2026-04-18T08:54:35+00:00',
      ingested_at: '2026-04-18T08:54:40+00:00',
      processed_at: '2026-04-18T08:54:40+00:00',
      canonical_entity_type: 'approval_request',
      canonical_entity_id: 'apr_006',
      correlation_id: 'case_005',
      case_id: 'case_005',
      normalized_payload: { approval_request_id: 'apr_006', status: 'pending' },
      confidence: 0.97,
      mapping_version: '1.0',
      status: 'processed',
      updated_at: '2026-04-18T08:54:40+00:00',
    },
    {
      id: 'ce_006_7',
      dedupe_key: 'cases:case_005:approval_wait',
      tenant_id: tenantId,
      workspace_id: workspaceId,
      source_system: 'case-engine',
      source_entity_type: 'case',
      source_entity_id: 'case_005',
      event_type: 'case_pending_approval',
      event_category: 'timeline',
      occurred_at: '2026-04-18T08:55:00+00:00',
      ingested_at: '2026-04-18T08:55:00+00:00',
      processed_at: null,
      canonical_entity_type: 'case',
      canonical_entity_id: 'case_005',
      correlation_id: 'case_005',
      case_id: 'case_005',
      normalized_payload: { approval_state: 'pending', execution_state: 'waiting_approval' },
      confidence: 0.95,
      mapping_version: '1.0',
      status: 'received',
      updated_at: '2026-04-18T08:55:00+00:00',
    },
  ]);

  await upsertRows('case_knowledge_links', [
    {
      id: 'ckl_006_1',
      case_id: 'case_005',
      article_id: 'ka_repeat_goodwill_policy',
      tenant_id: tenantId,
      relevance_score: 0.99,
      created_at: now.approval,
    },
    {
      id: 'ckl_006_2',
      case_id: 'case_005',
      article_id: 'ka_manager_escalation_playbook',
      tenant_id: tenantId,
      relevance_score: 0.95,
      created_at: now.approval,
    },
  ]);

  const verification = await supabase
    .from('cases')
    .select('id, case_number, status, approval_state, execution_state, customer_id, active_approval_request_id, active_execution_plan_id')
    .eq('id', 'case_005')
    .maybeSingle();
  if (verification.error) throw new Error(`verification: ${verification.error.message}`);
  console.log(JSON.stringify({
    ok: true,
    injected_case: verification.data,
    approvals: 'pending',
    knowledge_links: 2,
    workflow_run: 'wfr_006',
    agent_runs: 8,
  }, null, 2));
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
