import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

dotenv.config({ path: '.env.local' });

const url = process.env.SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) throw new Error('Missing Supabase env vars');

const supabase = createClient(url, key, { auth: { persistSession: false } });
const tenantId = 'org_default';
const workspaceId = 'ws_default';

const ids = {
  customer: 'cust_aurora',
  cases: {
    prevApproved: 'case_006_prev_1',
    prevRejected: 'case_006_prev_2',
    current: 'case_006',
  },
  conversations: {
    current: 'conv_006',
  },
  orders: {
    prevApproved: 'order_021',
    prevRejected: 'order_022',
    current: 'order_023',
  },
  payments: {
    prevApproved: 'pay_021',
    prevRejected: 'pay_022',
    current: 'pay_023',
  },
  returns: {
    prevApproved: 'return_021',
    prevRejected: 'return_022',
    current: 'return_023',
  },
  approvals: {
    prevApproved: 'apr_021',
    prevRejected: 'apr_022',
    currentManager: 'apr_023',
    currentFinance: 'apr_024',
  },
  plans: {
    current: 'plan_007',
  },
  workflows: {
    definition: 'wfd_007',
    version: 'wfv_007_1',
    run: 'wfr_007',
  },
  drafts: {
    current: 'dr_006',
  },
  policy: {
    main: 'pr_luxury_replacement_manager',
    finance: 'pr_luxury_finance_review',
  },
  knowledge: {
    domain: 'kd_luxury_exceptions',
    articles: {
      replacement: 'ka_luxury_replacement_policy',
      finance: 'ka_luxury_finance_playbook',
    },
  },
  evaluations: {
    current: 'peval_007',
  },
  issues: {
    current: 'ri_007',
  },
  notes: {
    current: 'note_006',
  },
  canonical: {
    order: ['ce_007_1', 'ce_007_2', 'ce_007_3', 'ce_007_4', 'ce_007_5', 'ce_007_6', 'ce_007_7'],
  },
  webhooks: {
    current: ['wh_007_1', 'wh_007_2', 'wh_007_3', 'wh_007_4', 'wh_007_5', 'wh_007_6', 'wh_007_7'],
  },
  agentRuns: {
    current: ['ar_021', 'ar_022', 'ar_023', 'ar_024', 'ar_025', 'ar_026', 'ar_027', 'ar_028', 'ar_029', 'ar_030'],
  },
};

const timeline = {
  prev1: {
    order: '2026-02-12T09:00:00+00:00',
    order2: '2026-02-12T09:01:20+00:00',
    order3: '2026-02-14T11:20:00+00:00',
    order4: '2026-02-15T07:30:00+00:00',
    payment1: '2026-02-12T09:01:20+00:00',
    payment2: '2026-02-15T07:30:00+00:00',
    return1: '2026-02-14T10:00:00+00:00',
    return2: '2026-02-14T11:20:00+00:00',
    approval: '2026-02-14T12:00:00+00:00',
  },
  prev2: {
    order: '2026-03-18T08:40:00+00:00',
    order2: '2026-03-18T08:41:10+00:00',
    order3: '2026-03-19T10:10:00+00:00',
    order4: '2026-03-19T12:00:00+00:00',
    payment1: '2026-03-18T08:41:10+00:00',
    payment2: '2026-03-19T12:00:00+00:00',
    return1: '2026-03-19T09:00:00+00:00',
    return2: '2026-03-19T10:10:00+00:00',
    approval: '2026-03-19T11:00:00+00:00',
  },
  current: {
    customer: '2026-04-19T07:55:00+00:00',
    order: '2026-04-19T08:03:00+00:00',
    order2: '2026-04-19T08:04:20+00:00',
    order3: '2026-04-19T08:06:10+00:00',
    order4: '2026-04-19T08:09:00+00:00',
    order5: '2026-04-19T08:12:40+00:00',
    order6: '2026-04-19T08:17:10+00:00',
    order7: '2026-04-19T08:23:00+00:00',
    order8: '2026-04-19T08:29:00+00:00',
    payment1: '2026-04-19T08:04:20+00:00',
    payment2: '2026-04-19T08:06:10+00:00',
    payment3: '2026-04-19T08:14:00+00:00',
    payment4: '2026-04-19T08:20:00+00:00',
    return1: '2026-04-19T08:12:40+00:00',
    return2: '2026-04-19T08:17:10+00:00',
    return3: '2026-04-19T08:23:00+00:00',
    msg1: '2026-04-19T08:05:00+00:00',
    msg2: '2026-04-19T08:08:00+00:00',
    msg3: '2026-04-19T08:13:00+00:00',
    msg4: '2026-04-19T08:18:30+00:00',
    msg5: '2026-04-19T08:27:00+00:00',
    approval: '2026-04-19T08:35:00+00:00',
    finance: '2026-04-19T08:39:00+00:00',
    draft: '2026-04-19T08:43:00+00:00',
  },
};

async function upsertRows(table: string, rows: any[]) {
  if (!rows.length) return;
  const normalizedRows = rows.map((row) => normalizeRecord(row));
  const { error } = await supabase.from(table).upsert(normalizedRows, { onConflict: 'id' });
  if (error) throw new Error(`${table}: ${error.message}`);
}

async function patch(table: string, match: Record<string, any>, values: Record<string, any>) {
  const { error } = await supabase.from(table).update(normalizeRecord(values)).match(match);
  if (error) throw new Error(`${table}: ${error.message}`);
}

function normalizeRecord<T extends Record<string, any>>(record: T): T {
  const normalized: Record<string, any> = {};
  for (const [key, value] of Object.entries(record)) {
    normalized[key] = normalizeValue(value);
  }
  return normalized as T;
}

function normalizeValue(value: any): any {
  if (Array.isArray(value) || (value && typeof value === 'object' && !(value instanceof Date))) {
    return JSON.stringify(value);
  }
  return value;
}

function buildOrder(
  id: string,
  external_order_id: string,
  customer_id: string,
  total_amount: number,
  order_date: string,
  status: string,
  summary: string,
  conflict = false,
  extra: any = {},
) {
  return {
    id,
    external_order_id,
    customer_id,
    tenant_id: tenantId,
    workspace_id: workspaceId,
    status,
    fulfillment_status: extra.fulfillment_status ?? status,
    tracking_number: extra.tracking_number ?? `TRK-${external_order_id.slice(-5)}`,
    tracking_url: extra.tracking_url ?? `https://tracking.example.com/${external_order_id}`,
    shipping_address: extra.shipping_address ?? 'Calle Serrano 88, Madrid',
    system_states: extra.system_states ?? { canonical: status, shopify: status, stripe: extra.stripe_state ?? 'captured', wms: extra.wms_state ?? status, policy: extra.policy_state ?? 'ok' },
    total_amount,
    currency: 'USD',
    country: 'ES',
    brand: 'Nimbus Atelier',
    channel: extra.channel ?? 'email',
    order_date,
    has_conflict: conflict ? 1 : 0,
    conflict_domain: extra.conflict_domain ?? null,
    conflict_detected: extra.conflict_detected ?? null,
    recommended_action: extra.recommended_action ?? 'No action needed',
    risk_level: extra.risk_level ?? (conflict ? 'high' : 'low'),
    order_type: extra.order_type ?? 'standard',
    approval_status: extra.approval_status ?? (conflict ? 'approval_needed' : 'not_required'),
    summary,
    last_sync_at: extra.last_sync_at ?? order_date,
    last_update: extra.last_update ?? order_date,
    badges: extra.badges ?? [],
    tab: extra.tab ?? 'all',
    created_at: extra.created_at ?? order_date,
    updated_at: extra.updated_at ?? order_date,
  };
}

function buildPayment(
  id: string,
  external_payment_id: string,
  order_id: string,
  customer_id: string,
  amount: number,
  created_at: string,
  status: string,
  summary: string,
  conflict = false,
  extra: any = {},
) {
  return {
    id,
    external_payment_id,
    order_id,
    customer_id,
    tenant_id: tenantId,
    workspace_id: workspaceId,
    amount,
    currency: 'USD',
    payment_method: extra.payment_method ?? 'Visa ···· 8841',
    psp: extra.psp ?? 'stripe',
    status,
    system_states: extra.system_states ?? { canonical: status, stripe: extra.stripe_state ?? status, oms: extra.oms_state ?? 'delivered' },
    dispute_id: extra.dispute_id ?? null,
    refund_ids: extra.refund_ids ?? [],
    risk_level: extra.risk_level ?? (conflict ? 'high' : 'low'),
    payment_type: extra.payment_type ?? 'standard',
    approval_status: extra.approval_status ?? (conflict ? 'approval_needed' : 'approved'),
    summary,
    has_conflict: conflict ? 1 : 0,
    conflict_detected: extra.conflict_detected ?? null,
    recommended_action: extra.recommended_action ?? 'No action needed',
    badges: extra.badges ?? [],
    tab: extra.tab ?? 'all',
    authorized_at: extra.authorized_at ?? created_at,
    captured_at: extra.captured_at ?? created_at,
    refund_status: extra.refund_status ?? null,
    refund_details: extra.refund_details ?? [],
    reconciliation_details: extra.reconciliation_details ?? {},
    refund_amount: extra.refund_amount ?? null,
    refund_type: extra.refund_type ?? null,
    dispute_reference: extra.dispute_reference ?? null,
    chargeback_amount: extra.chargeback_amount ?? null,
    created_at,
    updated_at: extra.updated_at ?? created_at,
    last_update: extra.last_update ?? created_at,
  };
}

function buildReturn(
  id: string,
  external_return_id: string,
  order_id: string,
  customer_id: string,
  return_value: number,
  created_at: string,
  status: string,
  summary: string,
  conflict = false,
  extra: any = {},
) {
  return {
    id,
    external_return_id,
    order_id,
    customer_id,
    tenant_id: tenantId,
    workspace_id: workspaceId,
    type: extra.type ?? 'return',
    return_reason: extra.return_reason ?? 'Damaged item',
    return_value,
    status,
    inspection_status: extra.inspection_status ?? 'pending',
    refund_status: extra.refund_status ?? 'pending_review',
    carrier_status: extra.carrier_status ?? 'delivered',
    has_conflict: conflict ? 1 : 0,
    approval_status: extra.approval_status ?? (conflict ? 'approval_needed' : 'not_required'),
    risk_level: extra.risk_level ?? (conflict ? 'high' : 'low'),
    linked_refund_id: extra.linked_refund_id ?? null,
    linked_shipment_id: extra.linked_shipment_id ?? null,
    system_states: extra.system_states ?? { canonical: status, warehouse: status, policy: extra.policy_state ?? 'ok' },
    conflict_detected: extra.conflict_detected ?? null,
    recommended_action: extra.recommended_action ?? 'No action needed',
    summary,
    badges: extra.badges ?? [],
    tab: extra.tab ?? 'all',
    method: extra.method ?? 'carrier_pickup',
    received_at_warehouse: extra.received_at_warehouse ?? created_at,
    brand: extra.brand ?? 'Nimbus Atelier',
    country: extra.country ?? 'ES',
    currency: 'USD',
    last_update: extra.last_update ?? created_at,
    created_at,
    updated_at: extra.updated_at ?? created_at,
  };
}

async function main() {
  await upsertRows('customers', [
    {
      id: ids.customer,
      tenant_id: tenantId,
      workspace_id: workspaceId,
      canonical_email: 'aurora.salazar@nimbusatelier.com',
      email: 'aurora.salazar@nimbusatelier.com',
      phone: '+34 600 222 910',
      canonical_name: 'Aurora Salazar',
      company: 'Nimbus Atelier',
      role: 'Founder & Ops Lead',
      location: 'Madrid, ES',
      timezone: 'Europe/Madrid',
      segment: 'vip',
      risk_level: 'critical',
      lifetime_value: 19420.5,
      total_spent: 19420.5,
      total_orders: 24,
      preferred_channel: 'email',
      dispute_rate: 0.08,
      refund_rate: 0.24,
      chargeback_count: 1,
      ai_impact_resolved: 19,
      ai_impact_approvals: 6,
      ai_impact_escalated: 3,
      top_issue: 'Luxury replacement exceptions',
      plan: 'Enterprise Plus',
      next_renewal: '2026-11-03T00:00:00+00:00',
      created_at: '2024-01-14T09:00:00+00:00',
      updated_at: timeline.current.approval,
    },
  ]);

  await upsertRows('linked_identities', [
    { id: 'li_aurora_shopify', customer_id: ids.customer, tenant_id: tenantId, workspace_id: workspaceId, system: 'shopify', external_id: 'shopify-customer-99023', confidence: 0.99, verified: 1, verified_at: timeline.current.customer, created_at: timeline.current.customer },
    { id: 'li_aurora_stripe', customer_id: ids.customer, tenant_id: tenantId, workspace_id: workspaceId, system: 'stripe', external_id: 'cus_aurora_99023', confidence: 0.98, verified: 1, verified_at: timeline.current.customer, created_at: timeline.current.customer },
    { id: 'li_aurora_email', customer_id: ids.customer, tenant_id: tenantId, workspace_id: workspaceId, system: 'email', external_id: 'aurora.salazar@nimbusatelier.com', confidence: 0.99, verified: 1, verified_at: timeline.current.customer, created_at: timeline.current.customer },
    { id: 'li_aurora_zendesk', customer_id: ids.customer, tenant_id: tenantId, workspace_id: workspaceId, system: 'zendesk', external_id: 'zd-1155', confidence: 0.95, verified: 1, verified_at: timeline.current.customer, created_at: timeline.current.customer },
    { id: 'li_aurora_whatsapp', customer_id: ids.customer, tenant_id: tenantId, workspace_id: workspaceId, system: 'whatsapp', external_id: 'whatsapp:+34600222910', confidence: 0.93, verified: 1, verified_at: timeline.current.customer, created_at: timeline.current.customer },
  ]);

  await upsertRows('users', [
    { id: 'user_alex', email: 'alex@acme.com', name: 'Alex Morgan', role: 'supervisor', avatar_url: null, is_system: 0, created_at: timeline.current.order },
    { id: 'user_sarah', email: 'sarah@acme.com', name: 'Sarah Kim', role: 'agent', avatar_url: null, is_system: 0, created_at: timeline.current.order },
    { id: 'user_maria', email: 'maria@acme.com', name: 'Maria Torres', role: 'finance', avatar_url: null, is_system: 0, created_at: timeline.current.order },
    { id: 'user_james', email: 'james@acme.com', name: 'James Liu', role: 'agent', avatar_url: null, is_system: 0, created_at: timeline.current.order },
  ]);

  await upsertRows('teams', [
    { id: 'team_support', workspace_id: workspaceId, name: 'Support Team', description: 'General support team', created_at: timeline.current.order },
    { id: 'team_finance', workspace_id: workspaceId, name: 'Finance Ops', description: 'Finance review and writeback team', created_at: timeline.current.order },
  ]);

  await upsertRows('knowledge_domains', [
    {
      id: ids.knowledge.domain,
      tenant_id: tenantId,
      name: 'Luxury Exceptions',
      description: 'Strict rules for expensive replacements, finance writebacks, and repeat exception handling.',
      created_at: timeline.current.approval,
    },
  ]);

  await upsertRows('knowledge_articles', [
    {
      id: ids.knowledge.articles.replacement,
      tenant_id: tenantId,
      workspace_id: workspaceId,
      domain_id: ids.knowledge.domain,
      title: 'Luxury replacement approval policy',
      content: 'When an order exceeds $250 USD, includes a premium accessory, or the customer has had a prior replacement in the last 90 days, any replacement or courtesy credit must wait for a manager. The assistant may explain the rule and draft a reply, but it must not promise a shipment or credit before approval.',
      content_structured: { summary: 'Luxury replacements require human review', threshold: { prior_replacements_90d: 1, max_auto_credit_usd: 0, order_value_usd: 250 } },
      type: 'article',
      status: 'published',
      owner_user_id: 'user_alex',
      review_cycle_days: 30,
      last_reviewed_at: timeline.current.approval,
      next_review_at: '2026-05-20T08:00:00+00:00',
      version: 3,
      citation_count: 18,
      last_cited_at: timeline.current.approval,
      outdated_flag: 0,
      linked_workflow_ids: [ids.workflows.definition],
      linked_approval_policy_ids: [ids.policy.main, ids.policy.finance],
      created_at: timeline.current.approval,
      updated_at: timeline.current.approval,
    },
    {
      id: ids.knowledge.articles.finance,
      tenant_id: tenantId,
      workspace_id: workspaceId,
      domain_id: ids.knowledge.domain,
      title: 'Finance writeback and dispute playbook',
      content: 'If a replacement or refund will touch the ledger, require finance review whenever the refund amount is above $100 USD, the order was partially fulfilled, or the customer has an open dispute. The next action should be evidence collection, not commit.',
      content_structured: { summary: 'Finance review before writeback', threshold: { refund_amount_usd: 100, open_dispute: true } },
      type: 'article',
      status: 'published',
      owner_user_id: 'user_maria',
      review_cycle_days: 45,
      last_reviewed_at: timeline.current.approval,
      next_review_at: '2026-06-04T08:00:00+00:00',
      version: 2,
      citation_count: 14,
      last_cited_at: timeline.current.finance,
      outdated_flag: 0,
      linked_workflow_ids: [ids.workflows.definition],
      linked_approval_policy_ids: [ids.policy.finance],
      created_at: timeline.current.approval,
      updated_at: timeline.current.approval,
    },
  ]);

  await upsertRows('policy_rules', [
    {
      id: ids.policy.main,
      tenant_id: tenantId,
      knowledge_article_id: ids.knowledge.articles.replacement,
      name: 'Luxury replacement manager approval',
      description: 'High-value replacements or repeat exceptions require manager approval.',
      entity_type: 'case',
      conditions: [
        { field: 'order.total_amount', operator: 'gte', value: 250 },
        { field: 'customer.prior_replacements_90d', operator: 'gte', value: 1 },
        { field: 'request.goodwill_credit_amount', operator: 'gt', value: 0 },
      ],
      action_mapping: { explain_policy: true, gather_evidence: true, draft_reply: true, never_auto_commit: true },
      approval_mapping: { requires_approval: true, approver_role: 'manager', max_auto_credit_usd: 0 },
      escalation_mapping: { route_to: 'team_support', priority: 'high', human_review: true },
      is_active: 1,
      version: 2,
      created_at: timeline.current.approval,
    },
    {
      id: ids.policy.finance,
      tenant_id: tenantId,
      knowledge_article_id: ids.knowledge.articles.finance,
      name: 'Finance writeback review',
      description: 'Large refunds or any dispute-sensitive writeback require finance review.',
      entity_type: 'payment',
      conditions: [
        { field: 'refund.amount', operator: 'gt', value: 100 },
        { field: 'payment.dispute_open', operator: 'eq', value: true },
      ],
      action_mapping: { explain_policy: true, gather_evidence: true, draft_reply: false, never_auto_commit: true },
      approval_mapping: { requires_approval: true, approver_role: 'finance', max_auto_credit_usd: 0 },
      escalation_mapping: { route_to: 'team_finance', priority: 'high', human_review: true },
      is_active: 1,
      version: 1,
      created_at: timeline.current.approval,
    },
  ]);

  const historyOrders = [
    buildOrder(
      ids.orders.prevApproved,
      'ORD-99021',
      ids.customer,
      320,
      '2026-02-12T09:00:00+00:00',
      'delivered',
      'First luxury shipment delivered after a minor packaging issue was already handled.',
      false,
      { fulfillment_status: 'delivered', badges: ['Delivered', 'Closed'], tab: 'all' },
    ),
    buildOrder(
      ids.orders.prevRejected,
      'ORD-99022',
      ids.customer,
      468,
      '2026-03-18T08:40:00+00:00',
      'delivered',
      'Second order had a partial refund and a rejected courtesy upgrade request.',
      true,
      {
        fulfillment_status: 'delivered',
        conflict_domain: 'policy',
        conflict_detected: 'Extra courtesy credit exceeded the finance playbook limit',
        recommended_action: 'Reject the extra credit and finish the standard refund flow',
        risk_level: 'high',
        approval_status: 'approval_needed',
        badges: ['Delivered', 'Policy Review', 'Rejected Credit'],
        tab: 'conflicts',
        policy_state: 'requires_approval',
      },
    ),
    buildOrder(
      ids.orders.current,
      'ORD-99023',
      ids.customer,
      920,
      timeline.current.order,
      'delivered',
      'Current luxury order delivered with a missing accessory, a damaged insert, and a repeat-exception policy hold.',
      true,
      {
        channel: 'email',
        fulfillment_status: 'delivered',
        conflict_domain: 'policy',
        conflict_detected: 'Replacement and goodwill credit require manager approval because the customer has already used prior exceptions',
        recommended_action: 'Escalate to manager and finance before promising replacement or credit',
        risk_level: 'critical',
        approval_status: 'approval_needed',
        badges: ['Delivered', 'Policy Hold', 'Finance Review', 'High Value'],
        tab: 'attention',
        policy_state: 'requires_approval',
        stripe_state: 'captured',
        wms_state: 'received',
      },
    ),
  ];

  const historyPayments = [
    buildPayment(
      ids.payments.prevApproved,
      'pi_99021',
      ids.orders.prevApproved,
      ids.customer,
      320,
      '2026-02-12T09:01:20+00:00',
      'refunded',
      'Earlier accessory issue resolved with a small approved credit.',
      false,
      {
        payment_method: 'Visa ···· 4411',
        refund_ids: ['refund_021'],
        refund_status: 'succeeded',
        refund_details: [{ attempt: 1, initiated_at: '2026-02-14T11:20:00Z', amount: 30, status: 'succeeded', psp_ref: 're_021_a' }],
        refund_amount: 30,
        refund_type: 'partial',
        badges: ['Refunded', 'Matched'],
        tab: 'refunds',
      },
    ),
    buildPayment(
      ids.payments.prevRejected,
      'pi_99022',
      ids.orders.prevRejected,
      ids.customer,
      468,
      '2026-03-18T08:41:10+00:00',
      'settled',
      'Settlement completed, but the extra courtesy upgrade request was rejected.',
      true,
      {
        payment_method: 'Mastercard ···· 2201',
        refund_ids: ['refund_022'],
        approval_status: 'rejected',
        conflict_detected: 'Finance disallowed an additional courtesy credit over the limit',
        recommended_action: 'Issue the standard refund only and close the extra credit request',
        refund_status: 'rejected',
        refund_details: [{ attempt: 1, initiated_at: '2026-03-19T11:00:00Z', amount: 55, status: 'rejected', psp_ref: 're_022_a' }],
        refund_amount: 55,
        refund_type: 'partial',
        reconciliation_details: { status: 'pending', notes: 'Refund processed, courtesy extension rejected.' },
        badges: ['Captured', 'Rejected Credit', 'Finance Review'],
        tab: 'reconciliation',
      },
    ),
    buildPayment(
      ids.payments.current,
      'pi_99023',
      ids.orders.current,
      ids.customer,
      920,
      timeline.current.payment1,
      'settled',
      'Luxury payment captured, but the writeback must wait for manager and finance review.',
      true,
      {
        payment_method: 'Amex ···· 8841',
        refund_ids: ['refund_023'],
        approval_status: 'approval_needed',
        conflict_detected: 'Refund and replacement exceed the automatic threshold for this customer segment',
        recommended_action: 'Hold writeback until the manager approves the replacement and finance validates the refund',
        refund_status: 'pending_approval',
        refund_details: [{ attempt: 1, initiated_at: timeline.current.approval, amount: 135, status: 'pending_approval', psp_ref: 're_023_a' }],
        refund_amount: 135,
        refund_type: 'partial',
        reconciliation_details: { status: 'pending', notes: 'Captured payment; refund and writeback are blocked by policy.' },
        badges: ['Captured', 'Manager Approval', 'Finance Review'],
        tab: 'reconciliation',
      },
    ),
  ];

  const historyReturns = [
    buildReturn(
      ids.returns.prevApproved,
      'RT-99021',
      ids.orders.prevApproved,
      ids.customer,
      320,
      '2026-02-14T10:00:00+00:00',
      'received',
      'Earlier return inspected and closed with an approved credit.',
      false,
      {
        inspection_status: 'inspected',
        refund_status: 'succeeded',
        linked_refund_id: 'refund_021',
        received_at_warehouse: '2026-02-14T10:30:00+00:00',
        badges: ['Received', 'Closed'],
      },
    ),
    buildReturn(
      ids.returns.prevRejected,
      'RT-99022',
      ids.orders.prevRejected,
      ids.customer,
      468,
      '2026-03-19T09:00:00+00:00',
      'received',
      'Second return was accepted, but the extra courtesy credit was rejected.',
      true,
      {
        return_reason: 'Damaged packaging and missing premium lining',
        inspection_status: 'pending',
        refund_status: 'rejected',
        conflict_detected: 'Extra credit exceeds the playbook limit',
        recommended_action: 'Process the standard refund only and reject the add-on courtesy request',
        linked_refund_id: 'refund_022',
        received_at_warehouse: '2026-03-19T10:10:00+00:00',
        badges: ['Received', 'Rejected Credit', 'Policy Review'],
        tab: 'refund_pending',
      },
    ),
    buildReturn(
      ids.returns.current,
      'RT-99023',
      ids.orders.current,
      ids.customer,
      920,
      timeline.current.return1,
      'received',
      'Current return received with a serial mismatch and a missing accessory.',
      true,
      {
        return_reason: 'Serial mismatch, damaged insert, and missing accessory',
        inspection_status: 'pending',
        refund_status: 'pending_approval',
        conflict_detected: 'Replacement and refund both require human approval',
        recommended_action: 'Escalate to manager and finance, then commit the writeback',
        linked_refund_id: 'refund_023',
        received_at_warehouse: timeline.current.return2,
        badges: ['Received', 'Policy Hold', 'Finance Review'],
        tab: 'refund_pending',
        policy_state: 'requires_approval',
      },
    ),
  ];

  await upsertRows('orders', historyOrders);
  await upsertRows('order_line_items', [
    { id: 'oli_021_1', order_id: ids.orders.prevApproved, tenant_id: tenantId, workspace_id: workspaceId, external_item_id: 'shopify:ORD-99021:1', product_id: 'prod_aurora_jacket', sku: 'NIM-REPLACE-01', name: 'Luxury jacket replacement', price: 320, quantity: 1, currency: 'USD', icon: 'checkroom', image_url: 'https://cdn.example.com/nimbus/jacket.png', created_at: timeline.prev1.order },
    { id: 'oli_022_1', order_id: ids.orders.prevRejected, tenant_id: tenantId, workspace_id: workspaceId, external_item_id: 'shopify:ORD-99022:1', product_id: 'prod_aurora_wrap', sku: 'NIM-CREDIT-01', name: 'Courtesy credit bundle', price: 468, quantity: 1, currency: 'USD', icon: 'local_offer', image_url: 'https://cdn.example.com/nimbus/credit.png', created_at: timeline.prev2.order },
    { id: 'oli_023_1', order_id: ids.orders.current, tenant_id: tenantId, workspace_id: workspaceId, external_item_id: 'shopify:ORD-99023:1', product_id: 'prod_aurora_coat', sku: 'NIM-COAT-01', name: 'Aurora coat', price: 620, quantity: 1, currency: 'USD', icon: 'checkroom', image_url: 'https://cdn.example.com/nimbus/coat.png', created_at: timeline.current.order },
    { id: 'oli_023_2', order_id: ids.orders.current, tenant_id: tenantId, workspace_id: workspaceId, external_item_id: 'shopify:ORD-99023:2', product_id: 'prod_aurora_accessory', sku: 'NIM-ACC-99', name: 'Premium accessory set', price: 300, quantity: 1, currency: 'USD', icon: 'diamond', image_url: 'https://cdn.example.com/nimbus/accessory.png', created_at: timeline.current.order },
  ]);
  await upsertRows('payments', historyPayments);
  await upsertRows('returns', historyReturns);
  await upsertRows('refunds', [
    { id: 'refund_021', external_refund_id: 'rf_021', payment_id: ids.payments.prevApproved, order_id: ids.orders.prevApproved, customer_id: ids.customer, tenant_id: tenantId, amount: 30, currency: 'USD', type: 'partial', status: 'settled', reason: 'Approved courtesy correction', initiated_by: 'copilot', initiated_by_type: 'agent', approval_request_id: ids.approvals.prevApproved, idempotency_key: 'refund-pay-021', created_at: timeline.prev1.approval, updated_at: timeline.prev1.approval },
    { id: 'refund_022', external_refund_id: 'rf_022', payment_id: ids.payments.prevRejected, order_id: ids.orders.prevRejected, customer_id: ids.customer, tenant_id: tenantId, amount: 55, currency: 'USD', type: 'partial', status: 'rejected', reason: 'Rejected extra courtesy credit', initiated_by: 'agent_qa_policy_check', initiated_by_type: 'agent', approval_request_id: ids.approvals.prevRejected, idempotency_key: 'refund-pay-022', created_at: timeline.prev2.approval, updated_at: timeline.prev2.approval },
  ]);

  await upsertRows('cases', [
    {
      id: ids.cases.prevApproved,
      case_number: 'CAS-99021',
      tenant_id: tenantId,
      workspace_id: workspaceId,
      source_system: 'email',
      source_channel: 'email',
      source_entity_id: 'msg-thread-99021',
      type: 'replacement_request',
      sub_type: 'approved_courtesy_replacement',
      intent: 'replacement_with_small_credit',
      intent_confidence: 0.94,
      status: 'closed',
      priority: 'medium',
      severity: 'S2',
      risk_level: 'medium',
      risk_score: 63,
      fraud_flag: 0,
      assigned_user_id: 'user_alex',
      assigned_team_id: 'team_support',
      created_by_user_id: 'user_alex',
      sla_policy_id: null,
      sla_first_response_deadline: '2026-02-12T10:00:00+00:00',
      sla_resolution_deadline: '2026-02-15T10:00:00+00:00',
      sla_status: 'met',
      customer_id: ids.customer,
      order_ids: [ids.orders.prevApproved],
      payment_ids: [ids.payments.prevApproved],
      return_ids: [ids.returns.prevApproved],
      conversation_id: null,
      ai_diagnosis: 'Packaging damage on a luxury order justified a one-time replacement and a small credit.',
      ai_root_cause: 'Shipping damage',
      ai_confidence: 0.97,
      ai_recommended_action: 'Approve the replacement and close the case after the credit writeback.',
      ai_evidence_refs: ['apr_021', 'ce_007_1'],
      approval_state: 'approved',
      active_approval_request_id: null,
      execution_state: 'completed',
      active_execution_plan_id: null,
      resolution_state: 'resolved',
      resolved_by: 'user_alex',
      resolution_notes: 'Approved and completed without escalation.',
      resolution_at: timeline.prev1.approval,
      has_reconciliation_conflicts: 0,
      conflict_severity: 'low',
      tags: ['resolved', 'approved', 'replacement'],
      created_at: timeline.prev1.order,
      updated_at: timeline.prev1.approval,
      first_response_at: timeline.prev1.order2,
      last_activity_at: timeline.prev1.approval,
      closed_at: timeline.prev1.approval,
    },
    {
      id: ids.cases.prevRejected,
      case_number: 'CAS-99022',
      tenant_id: tenantId,
      workspace_id: workspaceId,
      source_system: 'email',
      source_channel: 'email',
      source_entity_id: 'msg-thread-99022',
      type: 'refund_request',
      sub_type: 'policy_limited_credit',
      intent: 'refund_with_extra_credit',
      intent_confidence: 0.95,
      status: 'closed',
      priority: 'high',
      severity: 'S2',
      risk_level: 'high',
      risk_score: 71,
      fraud_flag: 0,
      assigned_user_id: 'user_alex',
      assigned_team_id: 'team_support',
      created_by_user_id: 'user_alex',
      sla_policy_id: null,
      sla_first_response_deadline: '2026-03-18T09:00:00+00:00',
      sla_resolution_deadline: '2026-03-20T09:00:00+00:00',
      sla_status: 'met',
      customer_id: ids.customer,
      order_ids: [ids.orders.prevRejected],
      payment_ids: [ids.payments.prevRejected],
      return_ids: [ids.returns.prevRejected],
      conversation_id: null,
      ai_diagnosis: 'The standard refund was valid, but the extra courtesy request exceeded the luxury exceptions policy.',
      ai_root_cause: 'Extra courtesy credit beyond policy',
      ai_confidence: 0.98,
      ai_recommended_action: 'Reject the extra credit and close the case on the standard path.',
      ai_evidence_refs: ['apr_022', 'pr_luxury_replacement_manager'],
      approval_state: 'rejected',
      active_approval_request_id: null,
      execution_state: 'completed',
      active_execution_plan_id: null,
      resolution_state: 'resolved',
      resolved_by: 'user_maria',
      resolution_notes: 'Standard refund completed; courtesy credit rejected.',
      resolution_at: timeline.prev2.approval,
      has_reconciliation_conflicts: 1,
      conflict_severity: 'medium',
      tags: ['resolved', 'rejected', 'finance_review'],
      created_at: timeline.prev2.order,
      updated_at: timeline.prev2.approval,
      first_response_at: timeline.prev2.order2,
      last_activity_at: timeline.prev2.approval,
      closed_at: timeline.prev2.approval,
    },
    {
      id: ids.cases.current,
      case_number: 'CAS-99023',
      tenant_id: tenantId,
      workspace_id: workspaceId,
      source_system: 'email',
      source_channel: 'email',
      source_entity_id: 'msg-thread-99023',
      type: 'replacement_request',
      sub_type: 'luxury_replacement_repeat_exception',
      intent: 'replacement_with_goodwill_credit',
      intent_confidence: 0.99,
      status: 'open',
      priority: 'high',
      severity: 'S1',
      risk_level: 'critical',
      risk_score: 99,
      fraud_flag: 0,
      assigned_user_id: 'user_alex',
      assigned_team_id: 'team_support',
      created_by_user_id: 'user_alex',
      sla_policy_id: null,
      sla_first_response_deadline: '2026-04-19T08:20:00+00:00',
      sla_resolution_deadline: '2026-04-20T08:45:00+00:00',
      sla_status: 'at_risk',
      customer_id: ids.customer,
      order_ids: [ids.orders.current],
      payment_ids: [ids.payments.current],
      return_ids: [ids.returns.current],
      conversation_id: ids.conversations.current,
      ai_diagnosis: 'Premium customer with a serial mismatch, missing accessory, and a repeat-exception policy block that must be handled by humans.',
      ai_root_cause: 'Repeat exception threshold exceeded and finance writeback required.',
      ai_confidence: 0.99,
      ai_recommended_action: 'Escalate to manager and finance, keep the case open, and do not promise a credit before approval.',
      ai_evidence_refs: ['msg_006_3', 'peval_007', 'apr_023', 'apr_024'],
      approval_state: 'pending',
      active_approval_request_id: ids.approvals.currentManager,
      execution_state: 'waiting_approval',
      active_execution_plan_id: ids.plans.current,
      resolution_state: 'unresolved',
      resolved_by: null,
      resolution_notes: null,
      resolution_at: null,
      has_reconciliation_conflicts: 1,
      conflict_severity: 'critical',
      tags: ['vip', 'repeat_customer', 'serial_mismatch', 'finance_review'],
      created_at: timeline.current.customer,
      updated_at: timeline.current.approval,
      first_response_at: timeline.current.msg2,
      last_activity_at: timeline.current.approval,
      closed_at: null,
    },
  ]);

  await upsertRows('conversations', [
    {
      id: ids.conversations.current,
      case_id: ids.cases.current,
      customer_id: ids.customer,
      channel: 'email',
      status: 'open',
      subject: 'Luxurious replacement request with finance hold',
      external_thread_id: 'email-thread-99023',
      first_message_at: timeline.current.msg1,
      last_message_at: timeline.current.msg5,
      created_at: timeline.current.customer,
      updated_at: timeline.current.approval,
      tenant_id: tenantId,
      workspace_id: workspaceId,
    },
  ]);

  await upsertRows('messages', [
    { id: 'msg_006_1', conversation_id: ids.conversations.current, case_id: ids.cases.current, customer_id: ids.customer, type: 'customer', direction: 'inbound', sender_id: ids.customer, sender_name: 'Aurora Salazar', content: 'The order arrived, but the premium insert is missing and the inner box is damaged. This is the second premium issue this quarter.', content_type: 'text', channel: 'email', external_message_id: 'em-msg-99023-1', sentiment: 'frustrated', sentiment_score: -0.45, attachments: [{ type: 'image', name: 'box_damage_photo.jpg' }], sent_at: timeline.current.msg1, created_at: timeline.current.msg1, delivered_at: timeline.current.msg1, read_at: timeline.current.msg1, tenant_id: tenantId },
    { id: 'msg_006_2', conversation_id: ids.conversations.current, case_id: ids.cases.current, customer_id: ids.customer, type: 'agent', direction: 'outbound', sender_id: 'agent_channel_ingest', sender_name: 'Channel Ingest', content: 'I have linked your email to the existing customer record and checked the previous replacements so we can review the full picture.', content_type: 'text', channel: 'email', external_message_id: 'em-msg-99023-2', sentiment: 'neutral', sentiment_score: 0.08, attachments: [], sent_at: timeline.current.msg2, created_at: timeline.current.msg2, delivered_at: timeline.current.msg2, read_at: timeline.current.msg2, tenant_id: tenantId },
    { id: 'msg_006_3', conversation_id: ids.conversations.current, case_id: ids.cases.current, customer_id: ids.customer, type: 'agent', direction: 'outbound', sender_id: 'agent_knowledge', sender_name: 'Knowledge Retriever', content: 'The policy articles confirm that replacements over $250 and repeat exceptions need a manager decision before any credit is promised.', content_type: 'text', channel: 'email', external_message_id: 'em-msg-99023-3', sentiment: 'steady', sentiment_score: 0.18, attachments: [], sent_at: timeline.current.msg3, created_at: timeline.current.msg3, delivered_at: timeline.current.msg3, read_at: timeline.current.msg3, tenant_id: tenantId },
    { id: 'msg_006_4', conversation_id: ids.conversations.current, case_id: ids.cases.current, customer_id: ids.customer, type: 'customer', direction: 'inbound', sender_id: ids.customer, sender_name: 'Aurora Salazar', content: 'Please proceed carefully. We need the replacement, but I understand that you may need approval before the credit is released.', content_type: 'text', channel: 'email', external_message_id: 'em-msg-99023-4', sentiment: 'concerned', sentiment_score: -0.16, attachments: [], sent_at: timeline.current.msg4, created_at: timeline.current.msg4, delivered_at: timeline.current.msg4, read_at: timeline.current.msg4, tenant_id: tenantId },
    { id: 'msg_006_5', conversation_id: ids.conversations.current, case_id: ids.cases.current, customer_id: ids.customer, type: 'agent', direction: 'outbound', sender_id: 'agent_qa_policy_check', sender_name: 'Policy Check', content: 'We have escalated this to the manager and finance queue. The case is moving, but we cannot promise the writeback until both reviews complete.', content_type: 'text', channel: 'email', external_message_id: 'em-msg-99023-5', sentiment: 'steady', sentiment_score: 0.22, attachments: [], sent_at: timeline.current.msg5, created_at: timeline.current.msg5, delivered_at: timeline.current.msg5, read_at: timeline.current.msg5, tenant_id: tenantId },
  ]);

  await upsertRows('case_status_history', [
    { id: 'csh_006_1', case_id: ids.cases.prevApproved, from_status: null, to_status: 'open', changed_by: 'shopify', changed_by_type: 'system', reason: 'Order and return signals entered the inbox', created_at: timeline.prev1.order, tenant_id: tenantId },
    { id: 'csh_006_2', case_id: ids.cases.prevApproved, from_status: 'open', to_status: 'approval_pending', changed_by: 'agent_qa_policy_check', changed_by_type: 'agent', reason: 'Manager approval requested for a replacement', created_at: timeline.prev1.order3, tenant_id: tenantId },
    { id: 'csh_006_3', case_id: ids.cases.prevApproved, from_status: 'approval_pending', to_status: 'closed', changed_by: 'user_alex', changed_by_type: 'human', reason: 'Approved replacement completed and written back', created_at: timeline.prev1.approval, tenant_id: tenantId },
    { id: 'csh_006_4', case_id: ids.cases.prevRejected, from_status: null, to_status: 'open', changed_by: 'shopify', changed_by_type: 'system', reason: 'Order, payment, and return arrived together', created_at: timeline.prev2.order, tenant_id: tenantId },
    { id: 'csh_006_5', case_id: ids.cases.prevRejected, from_status: 'open', to_status: 'approval_pending', changed_by: 'agent_qa_policy_check', changed_by_type: 'agent', reason: 'Extra courtesy credit exceeded the policy limit', created_at: timeline.prev2.order4, tenant_id: tenantId },
    { id: 'csh_006_6', case_id: ids.cases.prevRejected, from_status: 'approval_pending', to_status: 'closed', changed_by: 'user_maria', changed_by_type: 'human', reason: 'Rejected the extra courtesy credit and closed the case', created_at: timeline.prev2.approval, tenant_id: tenantId },
    { id: 'csh_006_7', case_id: ids.cases.current, from_status: null, to_status: 'open', changed_by: 'email', changed_by_type: 'system', reason: 'Email thread from Aurora Salazar entered the inbox', created_at: timeline.current.order, tenant_id: tenantId },
    { id: 'csh_006_8', case_id: ids.cases.current, from_status: 'open', to_status: 'investigating', changed_by: 'agent_channel_ingest', changed_by_type: 'agent', reason: 'Linked current thread to previous orders and returns', created_at: timeline.current.msg2, tenant_id: tenantId },
    { id: 'csh_006_9', case_id: ids.cases.current, from_status: 'investigating', to_status: 'approval_pending', changed_by: 'agent_qa_policy_check', changed_by_type: 'agent', reason: 'Luxury replacement and finance writeback exceed the approval threshold', created_at: timeline.current.approval, tenant_id: tenantId },
  ]);

  await upsertRows('execution_plans', [
    {
      id: ids.plans.current,
      case_id: ids.cases.current,
      tenant_id: tenantId,
      generated_by: 'copilot',
      generated_at: timeline.current.approval,
      status: 'awaiting_approval',
      steps: [
        { step: 'load_history', action: 'Review Aurora Salazar history and prior exceptions' },
        { step: 'inspect_evidence', action: 'Check photos, packaging, and previous approvals' },
        { step: 'manager_decision', action: 'Wait for a human approval on the replacement' },
        { step: 'finance_review', action: 'Validate refund writeback before settlement' },
        { step: 'reply_customer', action: 'Send the drafted customer update' },
      ],
      dry_run_result: { expected: 'human approval and finance review required', risk: 'critical' },
      approval_request_id: ids.approvals.currentManager,
      started_at: timeline.current.approval,
      completed_at: null,
    },
  ]);

  await upsertRows('approval_requests', [
    {
      id: ids.approvals.prevApproved,
      case_id: ids.cases.prevApproved,
      tenant_id: tenantId,
      workspace_id: workspaceId,
      requested_by: 'agent_qa_policy_check',
      requested_by_type: 'agent',
      action_type: 'replacement_and_small_credit',
      action_payload: { order_id: ids.orders.prevApproved, payment_id: ids.payments.prevApproved, return_id: ids.returns.prevApproved, replacement: true, goodwill_credit_amount: 30, reason: 'approved shipping damage', customer_history: { prior_replacements_90d: 0 } },
      risk_level: 'medium',
      policy_rule_id: ids.policy.main,
      evidence_package: { summary: 'Damaged packaging on the first order', customer_id: ids.customer, customer_name: 'Aurora Salazar', order_id: ids.orders.prevApproved, message_ids: [], knowledge_articles: [ids.knowledge.articles.replacement] },
      status: 'approved',
      assigned_to: 'user_alex',
      assigned_team_id: 'team_support',
      decision_by: 'user_alex',
      decision_at: timeline.prev1.approval,
      decision_note: 'Approved a one-time replacement with a small courtesy credit.',
      expires_at: timeline.prev1.approval,
      execution_plan_id: null,
      created_at: timeline.prev1.order3,
      updated_at: timeline.prev1.approval,
    },
    {
      id: ids.approvals.prevRejected,
      case_id: ids.cases.prevRejected,
      tenant_id: tenantId,
      workspace_id: workspaceId,
      requested_by: 'agent_qa_policy_check',
      requested_by_type: 'agent',
      action_type: 'extra_credit_rejection_review',
      action_payload: { order_id: ids.orders.prevRejected, payment_id: ids.payments.prevRejected, return_id: ids.returns.prevRejected, replacement: false, goodwill_credit_amount: 55, reason: 'extra credit over threshold', customer_history: { prior_replacements_90d: 1 } },
      risk_level: 'high',
      policy_rule_id: ids.policy.main,
      evidence_package: { summary: 'Extra courtesy credit exceeded the limit.', customer_id: ids.customer, customer_name: 'Aurora Salazar', order_id: ids.orders.prevRejected, message_ids: [], knowledge_articles: [ids.knowledge.articles.replacement] },
      status: 'rejected',
      assigned_to: 'user_maria',
      assigned_team_id: 'team_support',
      decision_by: 'user_maria',
      decision_at: timeline.prev2.approval,
      decision_note: 'Rejected the extra courtesy credit but allowed the standard refund.',
      expires_at: timeline.prev2.approval,
      execution_plan_id: null,
      created_at: timeline.prev2.order4,
      updated_at: timeline.prev2.approval,
    },
    {
      id: ids.approvals.currentManager,
      case_id: ids.cases.current,
      tenant_id: tenantId,
      workspace_id: workspaceId,
      requested_by: 'agent_qa_policy_check',
      requested_by_type: 'agent',
      action_type: 'replacement_and_goodwill_credit',
      action_payload: { order_id: ids.orders.current, payment_id: ids.payments.current, return_id: ids.returns.current, replacement: true, goodwill_credit_amount: 135, reason: 'repeat exception on luxury order', customer_history: { prior_replacements_90d: 1, prior_goodwill_exceptions_180d: 2 } },
      risk_level: 'critical',
      policy_rule_id: ids.policy.main,
      evidence_package: { summary: 'Luxury order with missing accessory and serial mismatch. Customer has prior exceptions.', customer_id: ids.customer, customer_name: 'Aurora Salazar', order_id: ids.orders.current, message_ids: ['msg_006_1', 'msg_006_4'], knowledge_articles: [ids.knowledge.articles.replacement, ids.knowledge.articles.finance] },
      status: 'pending',
      assigned_to: 'user_alex',
      assigned_team_id: 'team_support',
      decision_by: null,
      decision_at: null,
      decision_note: null,
      expires_at: '2026-04-20T08:40:00+00:00',
      execution_plan_id: ids.plans.current,
      created_at: timeline.current.approval,
      updated_at: timeline.current.approval,
    },
    {
      id: ids.approvals.currentFinance,
      case_id: ids.cases.current,
      tenant_id: tenantId,
      workspace_id: workspaceId,
      requested_by: 'agent_finance_reconciler',
      requested_by_type: 'agent',
      action_type: 'finance_writeback_review',
      action_payload: { order_id: ids.orders.current, payment_id: ids.payments.current, refund_amount: 135, reason: 'writeback after replacement approval', dispute_open: false },
      risk_level: 'high',
      policy_rule_id: ids.policy.finance,
      evidence_package: { summary: 'Ledger writeback pending manager approval and finance validation.', customer_id: ids.customer, customer_name: 'Aurora Salazar', order_id: ids.orders.current, knowledge_articles: [ids.knowledge.articles.finance] },
      status: 'pending',
      assigned_to: 'user_maria',
      assigned_team_id: 'team_finance',
      decision_by: null,
      decision_at: null,
      decision_note: null,
      expires_at: '2026-04-20T10:00:00+00:00',
      execution_plan_id: ids.plans.current,
      created_at: timeline.current.finance,
      updated_at: timeline.current.finance,
    },
  ]);

  await patch('execution_plans', { id: ids.plans.current, tenant_id: tenantId }, { approval_request_id: ids.approvals.currentManager });
  await patch('cases', { id: ids.cases.current, tenant_id: tenantId, workspace_id: workspaceId }, {
    active_approval_request_id: ids.approvals.currentManager,
    active_execution_plan_id: ids.plans.current,
    approval_state: 'pending',
    execution_state: 'waiting_approval',
    ai_evidence_refs: ['msg_006_3', 'peval_007', ids.approvals.currentManager, ids.approvals.currentFinance],
    updated_at: timeline.current.approval,
  });

  await upsertRows('policy_evaluations', [
    {
      id: ids.evaluations.current,
      tenant_id: tenantId,
      workspace_id: workspaceId,
      entity_type: 'case',
      action_type: 'replacement_and_goodwill_credit',
      case_id: ids.cases.current,
      input_context: {
        customer: { id: ids.customer, segment: 'vip', prior_goodwill_exceptions_180d: 2, prior_replacements_90d: 1 },
        request: { goodwill_credit_amount: 135, type: 'replacement_and_credit' },
        order: { id: ids.orders.current, total_amount: 920, status: 'delivered' },
      },
      evaluated_rules: [
        { rule_id: ids.policy.main, outcome: 'match', reason: 'Repeat luxury replacement threshold exceeded.' },
        { rule_id: ids.policy.finance, outcome: 'match', reason: 'Refund writeback requires finance validation.' },
      ],
      matched_rule_id: ids.policy.main,
      decision: 'requires_approval',
      requires_approval: 1,
      conflict_detected: 1,
      conflicting_rule_ids: [ids.policy.finance],
      reason: 'The case crosses both the manager approval and finance review thresholds.',
      created_at: timeline.current.approval,
    },
  ]);

  await upsertRows('reconciliation_issues', [
    {
      id: ids.issues.current,
      case_id: ids.cases.current,
      tenant_id: tenantId,
      workspace_id: workspaceId,
      entity_type: 'case',
      entity_id: ids.cases.current,
      conflict_domain: 'policy+finance',
      severity: 'critical',
      status: 'open',
      conflicting_systems: ['shopify', 'stripe', 'wms', 'policy_engine', 'finance'],
      expected_state: 'Replacement should wait for approval and the refund should be held until finance validates the writeback',
      actual_states: { shopify: 'delivered', stripe: 'captured', wms: 'received', customer_history: 'repeat-exception threshold exceeded', policy: 'requires human approval', finance: 'writeback pending' },
      source_of_truth_system: 'policy_engine',
      resolution_plan: 'Wait for manager approval, then validate finance writeback before closing the case.',
      detected_at: timeline.current.approval,
      resolved_at: null,
      detected_by: 'agent_qa_policy_check',
    },
  ]);

  await upsertRows('draft_replies', [
    {
      id: ids.drafts.current,
      case_id: ids.cases.current,
      conversation_id: ids.conversations.current,
      content: 'Aurora, I have reviewed the history and the policy. Your replacement is being handled, but because this is a repeat luxury exception we need a manager decision before any courtesy credit is released. I will update you as soon as both reviews are complete.',
      generated_by: 'agent_copilot',
      generated_at: timeline.current.draft,
      tone: 'empathetic',
      confidence: 0.91,
      has_policies: 1,
      citations: [ids.knowledge.articles.replacement, ids.knowledge.articles.finance],
      status: 'pending_review',
      reviewed_by: null,
      reviewed_at: null,
      sent_at: null,
      updated_at: timeline.current.draft,
      tenant_id: tenantId,
      workspace_id: workspaceId,
    },
  ]);

  await upsertRows('internal_notes', [
    {
      id: ids.notes.current,
      case_id: ids.cases.current,
      content: 'Aurora has already used two exception paths in the last six months. We should keep the tone calm, avoid promising any credit, and wait for manager plus finance confirmation.',
      created_by: 'agent_qa_policy_check',
      created_by_type: 'agent',
      created_at: timeline.current.finance,
      tenant_id: tenantId,
      workspace_id: workspaceId,
    },
  ]);

  await upsertRows('workflow_definitions', [
    {
      id: ids.workflows.definition,
      tenant_id: tenantId,
      workspace_id: workspaceId,
      name: 'Luxury exception approval flow',
      description: 'Ingests a high-value case, checks prior exceptions, routes through manager approval, and then validates finance writeback before sending the customer reply.',
      current_version_id: null,
      created_by: 'agent_copilot',
      created_at: timeline.current.order,
      updated_at: timeline.current.approval,
    },
  ]);

  await upsertRows('workflow_versions', [
    {
      id: ids.workflows.version,
      workflow_id: ids.workflows.definition,
      version_number: 1,
      status: 'published',
      nodes: [
        { id: 'ingest_case', type: 'task', label: 'Ingest case' },
        { id: 'load_history', type: 'task', label: 'Load customer history' },
        { id: 'retrieve_knowledge', type: 'task', label: 'Retrieve knowledge' },
        { id: 'inspect_evidence', type: 'task', label: 'Inspect evidence' },
        { id: 'policy_check', type: 'decision', label: 'Check luxury thresholds' },
        { id: 'manager_review', type: 'approval', label: 'Manager approval' },
        { id: 'finance_review', type: 'approval', label: 'Finance review' },
        { id: 'draft_reply', type: 'task', label: 'Draft reply' },
      ],
      edges: [
        { from: 'ingest_case', to: 'load_history' },
        { from: 'load_history', to: 'retrieve_knowledge' },
        { from: 'retrieve_knowledge', to: 'inspect_evidence' },
        { from: 'inspect_evidence', to: 'policy_check' },
        { from: 'policy_check', to: 'manager_review', condition: 'requires_approval' },
        { from: 'manager_review', to: 'finance_review', condition: 'approved' },
        { from: 'finance_review', to: 'draft_reply', condition: 'approved' },
      ],
      trigger: { type: 'case_event', event: 'case_created', case_id: ids.cases.current },
      published_by: 'user_alex',
      published_at: timeline.current.approval,
      tenant_id: tenantId,
    },
  ]);

  await patch('workflow_definitions', { id: ids.workflows.definition, tenant_id: tenantId, workspace_id: workspaceId }, { current_version_id: ids.workflows.version });

  await upsertRows('workflow_runs', [
    {
      id: ids.workflows.run,
      workflow_version_id: ids.workflows.version,
      case_id: ids.cases.current,
      tenant_id: tenantId,
      trigger_type: 'case_event',
      trigger_payload: {
        case_id: ids.cases.current,
        customer_id: ids.customer,
        order_id: ids.orders.current,
        approval_request_id: ids.approvals.currentManager,
        policy_rule_id: ids.policy.main,
      },
      status: 'running',
      current_node_id: 'manager_review',
      context: {
        customer_id: ids.customer,
        prior_goodwill_exceptions_180d: 2,
        knowledge_articles: [ids.knowledge.articles.replacement, ids.knowledge.articles.finance],
        approval_request_id: ids.approvals.currentManager,
      },
      started_at: timeline.current.approval,
      ended_at: null,
      error: null,
    },
  ]);

  await upsertRows('workflow_run_steps', [
    {
      id: 'wfrs_007_1',
      workflow_run_id: ids.workflows.run,
      node_id: 'ingest_case',
      node_type: 'task',
      status: 'completed',
      input: { case_id: ids.cases.current },
      output: { summary: 'Case ingested and linked to Aurora Salazar' },
      started_at: timeline.current.approval,
      ended_at: '2026-04-19T08:35:12+00:00',
      error: null,
    },
    {
      id: 'wfrs_007_2',
      workflow_run_id: ids.workflows.run,
      node_id: 'load_history',
      node_type: 'task',
      status: 'completed',
      input: { customer_id: ids.customer },
      output: { summary: 'Loaded two prior cases and three total orders' },
      started_at: '2026-04-19T08:35:12+00:00',
      ended_at: '2026-04-19T08:35:30+00:00',
      error: null,
    },
    {
      id: 'wfrs_007_3',
      workflow_run_id: ids.workflows.run,
      node_id: 'retrieve_knowledge',
      node_type: 'task',
      status: 'completed',
      input: { knowledge_articles: [ids.knowledge.articles.replacement, ids.knowledge.articles.finance] },
      output: { summary: 'Retrieved the luxury replacement and finance playbook articles' },
      started_at: '2026-04-19T08:35:30+00:00',
      ended_at: '2026-04-19T08:35:42+00:00',
      error: null,
    },
    {
      id: 'wfrs_007_4',
      workflow_run_id: ids.workflows.run,
      node_id: 'inspect_evidence',
      node_type: 'task',
      status: 'completed',
      input: { message_ids: ['msg_006_1', 'msg_006_4'] },
      output: { summary: 'Images and messages support the replacement request' },
      started_at: '2026-04-19T08:35:42+00:00',
      ended_at: '2026-04-19T08:35:58+00:00',
      error: null,
    },
    {
      id: 'wfrs_007_5',
      workflow_run_id: ids.workflows.run,
      node_id: 'policy_check',
      node_type: 'decision',
      status: 'completed',
      input: { rule_id: ids.policy.main, goodwill_credit_amount: 135 },
      output: { decision: 'requires_approval', reason: 'Threshold exceeded' },
      started_at: '2026-04-19T08:35:58+00:00',
      ended_at: '2026-04-19T08:36:12+00:00',
      error: null,
    },
    {
      id: 'wfrs_007_6',
      workflow_run_id: ids.workflows.run,
      node_id: 'manager_review',
      node_type: 'approval',
      status: 'running',
      input: { approval_request_id: ids.approvals.currentManager },
      output: { summary: 'Waiting for manager decision' },
      started_at: '2026-04-19T08:36:12+00:00',
      ended_at: null,
      error: null,
    },
  ]);

  await upsertRows('agents', [
    { id: 'agent_copilot', tenant_id: tenantId, name: 'Copilot', slug: 'copilot', category: 'orchestration', description: 'Primary support copilot for the demo tenant.', is_system: 1, is_locked: 0, is_active: 1, current_version_id: null, created_at: timeline.current.order, updated_at: timeline.current.approval },
    { id: 'agent_channel_ingest', tenant_id: tenantId, name: 'Channel Ingest', slug: 'channel-ingest', category: 'ingest', description: 'Ingests messages from email and support channels.', is_system: 1, is_locked: 0, is_active: 1, current_version_id: null, created_at: timeline.current.order, updated_at: timeline.current.approval },
    { id: 'agent_canonicalizer', tenant_id: tenantId, name: 'Canonicalizer', slug: 'canonicalizer', category: 'ingest', description: 'Normalizes cross-system payloads into canonical state.', is_system: 1, is_locked: 0, is_active: 1, current_version_id: null, created_at: timeline.current.order, updated_at: timeline.current.approval },
    { id: 'agent_intent_router', tenant_id: tenantId, name: 'Intent Router', slug: 'intent-router', category: 'ingest', description: 'Routes inbound intent to the correct case flow.', is_system: 1, is_locked: 0, is_active: 1, current_version_id: null, created_at: timeline.current.order, updated_at: timeline.current.approval },
    { id: 'agent_knowledge', tenant_id: tenantId, name: 'Knowledge Retriever', slug: 'knowledge-retriever', category: 'ingest', description: 'Retrieves policy articles and supporting evidence for cases.', is_system: 1, is_locked: 0, is_active: 1, current_version_id: null, created_at: timeline.current.order, updated_at: timeline.current.approval },
    { id: 'agent_qa_policy_check', tenant_id: tenantId, name: 'QA / Policy Check', slug: 'qa-policy-check', category: 'policy', description: 'Checks policies and quality thresholds before actions proceed.', is_system: 1, is_locked: 0, is_active: 1, current_version_id: null, created_at: timeline.current.order, updated_at: timeline.current.approval },
    { id: 'agent_approval_gatekeeper', tenant_id: tenantId, name: 'Approval Gatekeeper', slug: 'approval-gatekeeper', category: 'policy', description: 'Determines whether actions require manual review.', is_system: 1, is_locked: 0, is_active: 1, current_version_id: null, created_at: timeline.current.order, updated_at: timeline.current.approval },
    { id: 'agent_returns_specialist', tenant_id: tenantId, name: 'Returns Specialist', slug: 'returns-specialist', category: 'specialist', description: 'Handles return inspection, approval, and refund timing.', is_system: 0, is_locked: 0, is_active: 1, current_version_id: null, created_at: timeline.current.order, updated_at: timeline.current.approval },
    { id: 'agent_customer_history', tenant_id: tenantId, name: 'Customer History Analyst', slug: 'customer-history-analyst', category: 'analysis', description: 'Summarizes a customer’s prior orders, refunds, and approvals.', is_system: 0, is_locked: 0, is_active: 1, current_version_id: null, created_at: timeline.current.order, updated_at: timeline.current.approval },
    { id: 'agent_finance_reconciler', tenant_id: tenantId, name: 'Finance Reconciler', slug: 'finance-reconciler', category: 'finance', description: 'Checks refund writebacks, dispute risk, and ledger alignment.', is_system: 0, is_locked: 0, is_active: 1, current_version_id: null, created_at: timeline.current.order, updated_at: timeline.current.approval },
  ]);

  await upsertRows('agent_runs', [
    {
      id: ids.agentRuns.current[0],
      case_id: ids.cases.current,
      tenant_id: tenantId,
      workspace_id: workspaceId,
      agent_id: 'agent_channel_ingest',
      agent_version_id: null,
      trigger_event: 'case_created',
      trigger_type: 'case_event',
      status: 'completed',
      outcome_status: 'completed',
      confidence: 0.99,
      summary: 'Channel ingest linked the incoming email to the customer record and previous cases',
      output: { summary: 'Inbound thread normalized from email' },
      evidence_refs: ['msg_006_1'],
      execution_decision: 'proceed',
      tokens_used: 1240,
      cost_credits: 0.26,
      error: null,
      error_message: null,
      started_at: timeline.current.approval,
      ended_at: '2026-04-19T08:35:08+00:00',
      finished_at: '2026-04-19T08:35:08+00:00',
    },
    {
      id: ids.agentRuns.current[1],
      case_id: ids.cases.current,
      tenant_id: tenantId,
      workspace_id: workspaceId,
      agent_id: 'agent_canonicalizer',
      agent_version_id: null,
      trigger_event: 'case_created',
      trigger_type: 'case_event',
      status: 'completed',
      outcome_status: 'completed',
      confidence: 0.98,
      summary: 'Canonicalizer unified the order, payment, return, and customer history into one case model',
      output: { summary: 'Canonical state assembled for the luxury order' },
      evidence_refs: ['msg_006_1', 'msg_006_3', 'msg_006_5'],
      execution_decision: 'proceed',
      tokens_used: 1510,
      cost_credits: 0.31,
      error: null,
      error_message: null,
      started_at: '2026-04-19T08:35:08+00:00',
      ended_at: '2026-04-19T08:35:24+00:00',
      finished_at: '2026-04-19T08:35:24+00:00',
    },
    {
      id: ids.agentRuns.current[2],
      case_id: ids.cases.current,
      tenant_id: tenantId,
      workspace_id: workspaceId,
      agent_id: 'agent_intent_router',
      agent_version_id: null,
      trigger_event: 'case_created',
      trigger_type: 'case_event',
      status: 'completed',
      outcome_status: 'completed',
      confidence: 0.97,
      summary: 'Intent router classified the request as a high-value repeat exception with finance writeback risk',
      output: { summary: 'Routed to knowledge, policy, and finance flows' },
      evidence_refs: ['msg_006_1', 'msg_006_4'],
      execution_decision: 'proceed',
      tokens_used: 930,
      cost_credits: 0.2,
      error: null,
      error_message: null,
      started_at: '2026-04-19T08:35:24+00:00',
      ended_at: '2026-04-19T08:35:40+00:00',
      finished_at: '2026-04-19T08:35:40+00:00',
    },
    {
      id: ids.agentRuns.current[3],
      case_id: ids.cases.current,
      tenant_id: tenantId,
      workspace_id: workspaceId,
      agent_id: 'agent_customer_history',
      agent_version_id: null,
      trigger_event: 'case_created',
      trigger_type: 'case_event',
      status: 'completed',
      outcome_status: 'completed',
      confidence: 0.98,
      summary: 'History analyst found two previous cases, both of which explain the current threshold breach',
      output: { summary: 'Two prior cases and one current open case linked to Aurora' },
      evidence_refs: [ids.cases.prevApproved, ids.cases.prevRejected],
      execution_decision: 'proceed',
      tokens_used: 1110,
      cost_credits: 0.24,
      error: null,
      error_message: null,
      started_at: '2026-04-19T08:35:40+00:00',
      ended_at: '2026-04-19T08:35:55+00:00',
      finished_at: '2026-04-19T08:35:55+00:00',
    },
    {
      id: ids.agentRuns.current[4],
      case_id: ids.cases.current,
      tenant_id: tenantId,
      workspace_id: workspaceId,
      agent_id: 'agent_knowledge',
      agent_version_id: null,
      trigger_event: 'policy_check',
      trigger_type: 'case_event',
      status: 'completed',
      outcome_status: 'completed',
      confidence: 0.99,
      summary: 'Knowledge retriever surfaced the replacement and finance playbooks',
      output: { summary: 'Relevant policy articles linked to the case' },
      evidence_refs: [ids.knowledge.articles.replacement, ids.knowledge.articles.finance],
      execution_decision: 'proceed',
      tokens_used: 760,
      cost_credits: 0.15,
      error: null,
      error_message: null,
      started_at: '2026-04-19T08:35:55+00:00',
      ended_at: '2026-04-19T08:36:05+00:00',
      finished_at: '2026-04-19T08:36:05+00:00',
    },
    {
      id: ids.agentRuns.current[5],
      case_id: ids.cases.current,
      tenant_id: tenantId,
      workspace_id: workspaceId,
      agent_id: 'agent_qa_policy_check',
      agent_version_id: null,
      trigger_event: 'policy_check',
      trigger_type: 'case_event',
      status: 'completed',
      outcome_status: 'completed',
      confidence: 0.99,
      summary: 'Policy check confirmed the case requires manager and finance approval',
      output: { summary: 'Approval requested and case paused' },
      evidence_refs: [ids.policy.main, ids.policy.finance],
      execution_decision: 'hold',
      tokens_used: 1040,
      cost_credits: 0.22,
      error: null,
      error_message: null,
      started_at: '2026-04-19T08:36:05+00:00',
      ended_at: '2026-04-19T08:36:22+00:00',
      finished_at: '2026-04-19T08:36:22+00:00',
    },
    {
      id: ids.agentRuns.current[6],
      case_id: ids.cases.current,
      tenant_id: tenantId,
      workspace_id: workspaceId,
      agent_id: 'agent_finance_reconciler',
      agent_version_id: null,
      trigger_event: 'approval_requested',
      trigger_type: 'approval_event',
      status: 'running',
      outcome_status: 'running',
      confidence: 0.94,
      summary: 'Finance reconciler is waiting for manager approval before validating the writeback',
      output: { summary: 'Finance review queued behind manager approval' },
      evidence_refs: [ids.approvals.currentFinance, ids.policy.finance],
      execution_decision: 'pause',
      tokens_used: 620,
      cost_credits: 0.12,
      error: null,
      error_message: null,
      started_at: '2026-04-19T08:36:22+00:00',
      ended_at: null,
      finished_at: null,
    },
    {
      id: ids.agentRuns.current[7],
      case_id: ids.cases.current,
      tenant_id: tenantId,
      workspace_id: workspaceId,
      agent_id: 'agent_approval_gatekeeper',
      agent_version_id: null,
      trigger_event: 'approval_requested',
      trigger_type: 'approval_event',
      status: 'running',
      outcome_status: 'running',
      confidence: 0.95,
      summary: 'Approval gatekeeper is waiting for the manager decision on the luxury replacement',
      output: { summary: 'Approval request pending in inbox' },
      evidence_refs: [ids.approvals.currentManager, ids.evaluations.current],
      execution_decision: 'pause',
      tokens_used: 760,
      cost_credits: 0.16,
      error: null,
      error_message: null,
      started_at: '2026-04-19T08:36:24+00:00',
      ended_at: null,
      finished_at: null,
    },
    {
      id: ids.agentRuns.current[8],
      case_id: ids.cases.current,
      tenant_id: tenantId,
      workspace_id: workspaceId,
      agent_id: 'agent_returns_specialist',
      agent_version_id: null,
      trigger_event: 'return_registered',
      trigger_type: 'case_event',
      status: 'completed',
      outcome_status: 'completed',
      confidence: 0.96,
      summary: 'Returns specialist confirmed the return is valid, but it remains blocked by policy',
      output: { summary: 'Return accepted, resolution still waiting on approval' },
      evidence_refs: [ids.returns.current, ids.policy.main],
      execution_decision: 'hold',
      tokens_used: 930,
      cost_credits: 0.19,
      error: null,
      error_message: null,
      started_at: '2026-04-19T08:36:26+00:00',
      ended_at: '2026-04-19T08:36:44+00:00',
      finished_at: '2026-04-19T08:36:44+00:00',
    },
    {
      id: ids.agentRuns.current[9],
      case_id: ids.cases.current,
      tenant_id: tenantId,
      workspace_id: workspaceId,
      agent_id: 'agent_copilot',
      agent_version_id: null,
      trigger_event: 'reply_requested',
      trigger_type: 'case_event',
      status: 'completed',
      outcome_status: 'completed',
      confidence: 0.98,
      summary: 'Copilot drafted the customer update and the manager-facing summary',
      output: { summary: 'Reply explains the approval wait and next steps' },
      evidence_refs: [ids.drafts.current, ids.notes.current],
      execution_decision: 'proceed',
      tokens_used: 1680,
      cost_credits: 0.36,
      error: null,
      error_message: null,
      started_at: '2026-04-19T08:36:44+00:00',
      ended_at: '2026-04-19T08:37:10+00:00',
      finished_at: '2026-04-19T08:37:10+00:00',
    },
  ]);

  await upsertRows('customer_activity', [
    { id: 'ca_006_1', customer_id: ids.customer, tenant_id: tenantId, type: 'case_created', system: 'email', level: 'info', title: 'New luxury exception case opened', content: 'Aurora emailed the support team about a missing premium accessory and a damaged insert.', metadata: { case_id: ids.cases.current }, source: 'email', occurred_at: timeline.current.msg1 },
    { id: 'ca_006_2', customer_id: ids.customer, tenant_id: tenantId, type: 'policy_hold', system: 'policy-engine', level: 'warning', title: 'Manager approval required', content: 'The case exceeded the repeat exception threshold and was escalated to a human.', metadata: { approval_request_id: ids.approvals.currentManager }, source: 'policy_engine', occurred_at: timeline.current.approval },
    { id: 'ca_006_3', customer_id: ids.customer, tenant_id: tenantId, type: 'finance_hold', system: 'finance', level: 'warning', title: 'Finance writeback pending', content: 'Refund writeback is waiting on finance validation after manager approval.', metadata: { approval_request_id: ids.approvals.currentFinance }, source: 'finance', occurred_at: timeline.current.finance },
    { id: 'ca_006_4', customer_id: ids.customer, tenant_id: tenantId, type: 'approved_case', system: 'support', level: 'info', title: 'Previous replacement approved', content: 'The earlier replacement case was approved and written back cleanly.', metadata: { case_id: ids.cases.prevApproved }, source: 'support', occurred_at: timeline.prev1.approval },
    { id: 'ca_006_5', customer_id: ids.customer, tenant_id: tenantId, type: 'rejected_credit', system: 'support', level: 'info', title: 'Previous courtesy credit rejected', content: 'The second prior case was closed after the extra courtesy credit was rejected.', metadata: { case_id: ids.cases.prevRejected }, source: 'support', occurred_at: timeline.prev2.approval },
  ]);

  await upsertRows('webhook_events', [
    { id: ids.webhooks.current[0], connector_id: 'conn_shopify', tenant_id: tenantId, source_system: 'shopify', event_type: 'orders/create', raw_payload: { order_id: 'ORD-99023', customer_email: 'aurora.salazar@nimbusatelier.com', tags: ['vip', 'luxury', 'repeat-customer'] }, received_at: '2026-04-19T08:02:40+00:00', processed_at: '2026-04-19T08:02:58+00:00', status: 'processed', canonical_event_id: 'ce_007_1', dedupe_key: 'shopify:orders/create:ORD-99023' },
    { id: ids.webhooks.current[1], connector_id: 'conn_stripe', tenant_id: tenantId, source_system: 'stripe', event_type: 'payment_intent.succeeded', raw_payload: { payment_id: ids.payments.current, amount: 920, currency: 'USD' }, received_at: '2026-04-19T08:04:00+00:00', processed_at: '2026-04-19T08:04:15+00:00', status: 'processed', canonical_event_id: 'ce_007_2', dedupe_key: 'stripe:payment_intent.succeeded:pi_99023' },
    { id: ids.webhooks.current[2], connector_id: 'conn_wms', tenant_id: tenantId, source_system: 'wms', event_type: 'return.received', raw_payload: { return_id: ids.returns.current, condition: 'opened_and_used', serial_mismatch: true }, received_at: '2026-04-19T08:12:30+00:00', processed_at: '2026-04-19T08:12:42+00:00', status: 'processed', canonical_event_id: 'ce_007_3', dedupe_key: 'wms:return.received:RT-99023' },
    { id: ids.webhooks.current[3], connector_id: 'conn_intercom', tenant_id: tenantId, source_system: 'email', event_type: 'message.created', raw_payload: { conversation_id: ids.conversations.current, sender: 'aurora.salazar@nimbusatelier.com' }, received_at: '2026-04-19T08:05:00+00:00', processed_at: '2026-04-19T08:05:05+00:00', status: 'processed', canonical_event_id: 'ce_007_4', dedupe_key: 'email:message.created:conv_006:1' },
    { id: ids.webhooks.current[4], connector_id: null, tenant_id: tenantId, source_system: 'policy-engine', event_type: 'policy.violation', raw_payload: { rule_id: ids.policy.main, outcome: 'requires_approval' }, received_at: '2026-04-19T08:35:00+00:00', processed_at: '2026-04-19T08:35:07+00:00', status: 'processed', canonical_event_id: 'ce_007_5', dedupe_key: 'policy-engine:policy.violation:case_006' },
    { id: ids.webhooks.current[5], connector_id: 'conn_intercom', tenant_id: tenantId, source_system: 'support', event_type: 'approval.requested', raw_payload: { approval_request_id: ids.approvals.currentManager, case_id: ids.cases.current }, received_at: '2026-04-19T08:35:10+00:00', processed_at: '2026-04-19T08:35:15+00:00', status: 'processed', canonical_event_id: 'ce_007_6', dedupe_key: 'support:approval.requested:apr_023' },
    { id: ids.webhooks.current[6], connector_id: null, tenant_id: tenantId, source_system: 'finance', event_type: 'approval.requested', raw_payload: { approval_request_id: ids.approvals.currentFinance, case_id: ids.cases.current }, received_at: '2026-04-19T08:39:00+00:00', processed_at: '2026-04-19T08:39:08+00:00', status: 'processed', canonical_event_id: 'ce_007_7', dedupe_key: 'finance:approval.requested:apr_024' },
  ]);

  await upsertRows('canonical_events', [
    { id: 'ce_007_1', dedupe_key: 'shopify:orders/create:ORD-99023', tenant_id: tenantId, workspace_id: workspaceId, source_system: 'shopify', source_entity_type: 'order', source_entity_id: 'ORD-99023', event_type: 'order_created', event_category: 'inbox', occurred_at: '2026-04-19T08:02:40+00:00', ingested_at: '2026-04-19T08:02:58+00:00', processed_at: '2026-04-19T08:02:58+00:00', canonical_entity_type: 'order', canonical_entity_id: ids.orders.current, correlation_id: ids.cases.current, case_id: ids.cases.current, normalized_payload: { order_id: ids.orders.current, customer_id: ids.customer, status: 'open' }, confidence: 0.99, mapping_version: '1.0', status: 'processed', updated_at: '2026-04-19T08:02:58+00:00' },
    { id: 'ce_007_2', dedupe_key: 'stripe:payment_intent.succeeded:pi_99023', tenant_id: tenantId, workspace_id: workspaceId, source_system: 'stripe', source_entity_type: 'payment', source_entity_id: ids.payments.current, event_type: 'payment_captured', event_category: 'payments', occurred_at: '2026-04-19T08:04:00+00:00', ingested_at: '2026-04-19T08:04:15+00:00', processed_at: '2026-04-19T08:04:15+00:00', canonical_entity_type: 'payment', canonical_entity_id: ids.payments.current, correlation_id: ids.cases.current, case_id: ids.cases.current, normalized_payload: { payment_id: ids.payments.current, amount: 920, status: 'captured' }, confidence: 0.99, mapping_version: '1.0', status: 'processed', updated_at: '2026-04-19T08:04:15+00:00' },
    { id: 'ce_007_3', dedupe_key: 'wms:return.received:RT-99023', tenant_id: tenantId, workspace_id: workspaceId, source_system: 'wms', source_entity_type: 'return', source_entity_id: ids.returns.current, event_type: 'return_received', event_category: 'returns', occurred_at: '2026-04-19T08:12:30+00:00', ingested_at: '2026-04-19T08:12:42+00:00', processed_at: '2026-04-19T08:12:42+00:00', canonical_entity_type: 'return', canonical_entity_id: ids.returns.current, correlation_id: ids.cases.current, case_id: ids.cases.current, normalized_payload: { return_id: ids.returns.current, inspection_status: 'pending_review' }, confidence: 0.98, mapping_version: '1.0', status: 'processed', updated_at: '2026-04-19T08:12:42+00:00' },
    { id: 'ce_007_4', dedupe_key: 'email:message.created:conv_006:1', tenant_id: tenantId, workspace_id: workspaceId, source_system: 'email', source_entity_type: 'message', source_entity_id: 'msg_006_1', event_type: 'message_received', event_category: 'inbox', occurred_at: '2026-04-19T08:05:00+00:00', ingested_at: '2026-04-19T08:05:05+00:00', processed_at: '2026-04-19T08:05:05+00:00', canonical_entity_type: 'conversation', canonical_entity_id: ids.conversations.current, correlation_id: ids.cases.current, case_id: ids.cases.current, normalized_payload: { conversation_id: ids.conversations.current, message_id: 'msg_006_1' }, confidence: 0.97, mapping_version: '1.0', status: 'processed', updated_at: '2026-04-19T08:05:05+00:00' },
    { id: 'ce_007_5', dedupe_key: 'policy-engine:policy.violation:case_006', tenant_id: tenantId, workspace_id: workspaceId, source_system: 'policy-engine', source_entity_type: 'case', source_entity_id: ids.cases.current, event_type: 'policy_violation_detected', event_category: 'approvals', occurred_at: '2026-04-19T08:35:00+00:00', ingested_at: '2026-04-19T08:35:07+00:00', processed_at: '2026-04-19T08:35:07+00:00', canonical_entity_type: 'case', canonical_entity_id: ids.cases.current, correlation_id: ids.cases.current, case_id: ids.cases.current, normalized_payload: { rule_id: ids.policy.main, decision: 'requires_approval' }, confidence: 1, mapping_version: '1.0', status: 'processed', updated_at: '2026-04-19T08:35:07+00:00' },
    { id: 'ce_007_6', dedupe_key: 'support:approval.requested:apr_023', tenant_id: tenantId, workspace_id: workspaceId, source_system: 'support', source_entity_type: 'approval_request', source_entity_id: ids.approvals.currentManager, event_type: 'approval_requested', event_category: 'approvals', occurred_at: '2026-04-19T08:35:10+00:00', ingested_at: '2026-04-19T08:35:15+00:00', processed_at: '2026-04-19T08:35:15+00:00', canonical_entity_type: 'approval_request', canonical_entity_id: ids.approvals.currentManager, correlation_id: ids.cases.current, case_id: ids.cases.current, normalized_payload: { approval_request_id: ids.approvals.currentManager, status: 'pending' }, confidence: 0.97, mapping_version: '1.0', status: 'processed', updated_at: '2026-04-19T08:35:15+00:00' },
    { id: 'ce_007_7', dedupe_key: 'finance:approval.requested:apr_024', tenant_id: tenantId, workspace_id: workspaceId, source_system: 'finance', source_entity_type: 'approval_request', source_entity_id: ids.approvals.currentFinance, event_type: 'approval_requested', event_category: 'approvals', occurred_at: '2026-04-19T08:39:00+00:00', ingested_at: '2026-04-19T08:39:08+00:00', processed_at: '2026-04-19T08:39:08+00:00', canonical_entity_type: 'approval_request', canonical_entity_id: ids.approvals.currentFinance, correlation_id: ids.cases.current, case_id: ids.cases.current, normalized_payload: { approval_request_id: ids.approvals.currentFinance, status: 'pending' }, confidence: 0.97, mapping_version: '1.0', status: 'processed', updated_at: '2026-04-19T08:39:08+00:00' },
  ]);

  await upsertRows('order_events', [
    { id: 'oe_021_1', order_id: ids.orders.prevApproved, type: 'order_placed', content: 'Order ORD-99021 placed by Aurora Salazar', system: 'Shopify', time: timeline.prev1.order, tenant_id: tenantId },
    { id: 'oe_021_2', order_id: ids.orders.prevApproved, type: 'payment_captured', content: 'Payment captured successfully', system: 'Stripe', time: timeline.prev1.order2, tenant_id: tenantId },
    { id: 'oe_021_3', order_id: ids.orders.prevApproved, type: 'delivered', content: 'Carrier confirmed delivery at the customer address', system: 'Carrier', time: timeline.prev1.order3, tenant_id: tenantId },
    { id: 'oe_021_4', order_id: ids.orders.prevApproved, type: 'replacement_closed', content: 'Approved replacement closed after manager review', system: 'OMS', time: timeline.prev1.order4, tenant_id: tenantId },
    { id: 'oe_022_1', order_id: ids.orders.prevRejected, type: 'order_placed', content: 'Order ORD-99022 placed by Aurora Salazar', system: 'Shopify', time: timeline.prev2.order, tenant_id: tenantId },
    { id: 'oe_022_2', order_id: ids.orders.prevRejected, type: 'payment_captured', content: 'Payment captured successfully', system: 'Stripe', time: timeline.prev2.order2, tenant_id: tenantId },
    { id: 'oe_022_3', order_id: ids.orders.prevRejected, type: 'return_requested', content: 'Return requested through support', system: 'Support', time: timeline.prev2.order3, tenant_id: tenantId },
    { id: 'oe_022_4', order_id: ids.orders.prevRejected, type: 'policy_hold', content: 'Extra courtesy credit was held for review', system: 'System', time: timeline.prev2.order4, tenant_id: tenantId },
    { id: 'oe_023_1', order_id: ids.orders.current, type: 'order_placed', content: 'Order ORD-99023 placed by Aurora Salazar', system: 'Shopify', time: timeline.current.order, tenant_id: tenantId },
    { id: 'oe_023_2', order_id: ids.orders.current, type: 'payment_authorized', content: 'Payment authorized — $920.00', system: 'Stripe', time: timeline.current.order2, tenant_id: tenantId },
    { id: 'oe_023_3', order_id: ids.orders.current, type: 'payment_captured', content: 'Payment captured successfully', system: 'Stripe', time: timeline.current.order3, tenant_id: tenantId },
    { id: 'oe_023_4', order_id: ids.orders.current, type: 'warehouse_picked', content: 'Warehouse picked and packed the premium shipment', system: 'WMS', time: timeline.current.order4, tenant_id: tenantId },
    { id: 'oe_023_5', order_id: ids.orders.current, type: 'label_created', content: 'Shipping label created — DHL-99023X', system: 'Carrier', time: timeline.current.order5, tenant_id: tenantId },
    { id: 'oe_023_6', order_id: ids.orders.current, type: 'delivered', content: 'Parcel delivered to the customer address', system: 'Carrier', time: timeline.current.order6, tenant_id: tenantId },
    { id: 'oe_023_7', order_id: ids.orders.current, type: 'issue_reported', content: 'Customer reported missing premium accessory and damaged insert', system: 'Email', time: timeline.current.order7, tenant_id: tenantId },
    { id: 'oe_023_8', order_id: ids.orders.current, type: 'policy_hold', content: 'Policy engine held the replacement and courtesy credit for manager review', system: 'System', time: timeline.current.order8, tenant_id: tenantId },
  ]);

  await upsertRows('payment_events', [
    { id: 'pe_021_1', payment_id: ids.payments.prevApproved, type: 'authorized', content: 'Payment authorized — $320.00', system: 'Stripe', time: timeline.prev1.payment1, tenant_id: tenantId },
    { id: 'pe_021_2', payment_id: ids.payments.prevApproved, type: 'refund_succeeded', content: 'Courtesy refund of $30 succeeded', system: 'Stripe', time: timeline.prev1.approval, tenant_id: tenantId },
    { id: 'pe_022_1', payment_id: ids.payments.prevRejected, type: 'authorized', content: 'Payment authorized — $468.00', system: 'Stripe', time: timeline.prev2.payment1, tenant_id: tenantId },
    { id: 'pe_022_2', payment_id: ids.payments.prevRejected, type: 'captured', content: 'Payment captured successfully', system: 'Stripe', time: timeline.prev2.payment2, tenant_id: tenantId },
    { id: 'pe_022_3', payment_id: ids.payments.prevRejected, type: 'refund_requested', content: 'Extra courtesy credit requested and reviewed', system: 'System', time: timeline.prev2.order4, tenant_id: tenantId },
    { id: 'pe_022_4', payment_id: ids.payments.prevRejected, type: 'refund_rejected', content: 'Finance rejected the extra courtesy credit', system: 'Finance', time: timeline.prev2.approval, tenant_id: tenantId },
    { id: 'pe_023_1', payment_id: ids.payments.current, type: 'authorized', content: 'Payment authorized — $920.00', system: 'Stripe', time: timeline.current.payment1, tenant_id: tenantId },
    { id: 'pe_023_2', payment_id: ids.payments.current, type: 'captured', content: 'Payment captured successfully', system: 'Stripe', time: timeline.current.payment2, tenant_id: tenantId },
    { id: 'pe_023_3', payment_id: ids.payments.current, type: 'refund_requested', content: 'Refund requested pending manager approval', system: 'System', time: timeline.current.payment3, tenant_id: tenantId },
    { id: 'pe_023_4', payment_id: ids.payments.current, type: 'finance_hold', content: 'Refund writeback is paused until finance validates the approval', system: 'Finance', time: timeline.current.payment4, tenant_id: tenantId },
  ]);

  await upsertRows('return_events', [
    { id: 're_021_1', return_id: ids.returns.prevApproved, type: 'received', content: 'Warehouse received the returned item', system: 'WMS', time: timeline.prev1.return1, tenant_id: tenantId },
    { id: 're_021_2', return_id: ids.returns.prevApproved, type: 'inspected', content: 'Inspection completed with no blockers', system: 'WMS', time: timeline.prev1.return2, tenant_id: tenantId },
    { id: 're_021_3', return_id: ids.returns.prevApproved, type: 'refund_succeeded', content: 'Approved credit settled and closed', system: 'Stripe', time: timeline.prev1.approval, tenant_id: tenantId },
    { id: 're_022_1', return_id: ids.returns.prevRejected, type: 'received', content: 'Warehouse received the returned item', system: 'WMS', time: timeline.prev2.return1, tenant_id: tenantId },
    { id: 're_022_2', return_id: ids.returns.prevRejected, type: 'inspected', content: 'Inspection completed with a minor packaging defect', system: 'WMS', time: timeline.prev2.return2, tenant_id: tenantId },
    { id: 're_022_3', return_id: ids.returns.prevRejected, type: 'policy_hold', content: 'Extra courtesy credit paused while finance reviewed the request', system: 'System', time: timeline.prev2.approval, tenant_id: tenantId },
    { id: 're_023_1', return_id: ids.returns.current, type: 'created', content: 'Return created in the support flow', system: 'Support', time: timeline.current.return1, tenant_id: tenantId },
    { id: 're_023_2', return_id: ids.returns.current, type: 'received', content: 'Warehouse marked the item as received', system: 'WMS', time: timeline.current.return2, tenant_id: tenantId },
    { id: 're_023_3', return_id: ids.returns.current, type: 'policy_hold', content: 'Courtesy credit paused until manager review completes', system: 'System', time: timeline.current.return3, tenant_id: tenantId },
  ]);

  await upsertRows('refunds', [
    { id: 'refund_021', external_refund_id: 'rf_021', payment_id: ids.payments.prevApproved, order_id: ids.orders.prevApproved, customer_id: ids.customer, tenant_id: tenantId, amount: 30, currency: 'USD', type: 'partial', status: 'settled', reason: 'Approved courtesy correction', initiated_by: 'copilot', initiated_by_type: 'agent', approval_request_id: ids.approvals.prevApproved, idempotency_key: 'refund-pay-021', created_at: timeline.prev1.approval, updated_at: timeline.prev1.approval },
    { id: 'refund_022', external_refund_id: 'rf_022', payment_id: ids.payments.prevRejected, order_id: ids.orders.prevRejected, customer_id: ids.customer, tenant_id: tenantId, amount: 55, currency: 'USD', type: 'partial', status: 'rejected', reason: 'Rejected extra courtesy credit', initiated_by: 'agent_qa_policy_check', initiated_by_type: 'agent', approval_request_id: ids.approvals.prevRejected, idempotency_key: 'refund-pay-022', created_at: timeline.prev2.approval, updated_at: timeline.prev2.approval },
    { id: 'refund_023', external_refund_id: 'rf_023', payment_id: ids.payments.current, order_id: ids.orders.current, customer_id: ids.customer, tenant_id: tenantId, amount: 135, currency: 'USD', type: 'partial', status: 'pending', reason: 'Goodwill credit awaiting manager approval', initiated_by: 'agent_qa_policy_check', initiated_by_type: 'agent', approval_request_id: ids.approvals.currentManager, idempotency_key: 'refund-pay-023', created_at: timeline.current.approval, updated_at: timeline.current.approval },
  ]);

  await upsertRows('case_knowledge_links', [
    { id: 'ckl_007_1', case_id: ids.cases.current, article_id: ids.knowledge.articles.replacement, tenant_id: tenantId, relevance_score: 0.99, created_at: timeline.current.approval },
    { id: 'ckl_007_2', case_id: ids.cases.current, article_id: ids.knowledge.articles.finance, tenant_id: tenantId, relevance_score: 0.96, created_at: timeline.current.finance },
  ]);

  const verification = await supabase
    .from('cases')
    .select('id, case_number, status, approval_state, execution_state, customer_id, active_approval_request_id, active_execution_plan_id')
    .in('id', [ids.cases.prevApproved, ids.cases.prevRejected, ids.cases.current]);

  if (verification.error) throw new Error(verification.error.message);

  console.log(JSON.stringify({
    ok: true,
    injected_cases: verification.data,
    approvals: 4,
    knowledge_links: 2,
    workflow_run: ids.workflows.run,
    agent_runs: ids.agentRuns.current.length,
  }, null, 2));
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
